### ISSUE TITLE
mmaps_generator compile error (Ubuntu)

### ISSUE THREAD

**Issue by Talmeron** [ProjectSkyfire/SkyFire.548#311]
Linking CXX executable mmaps_generator
/usr/bin/ld: ../../server/shared/libshared.a(Util.cpp.o): undefined reference to symbol 'pthread_getspecific@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: **\* [src/tools/mmaps_generator/mmaps_generator] Error 1
make[1]: **\* [src/tools/mmaps_generator/CMakeFiles/mmaps_generator.dir/all] Error 2
make: **\* [all] Error 2

**Comment by Shoxxo** [comment]
how you have resolve it, i have atm same issue...

**Comment by AriDEV** [comment]
"-L/lib64 -lpthread"

**Comment by Shoxxo** [comment]
Thank you Ari :)
