### ISSUE TITLE
error Quest system

### ISSUE THREAD

**Issue by zgn1988** [ProjectSkyfire/SkyFire.548#345]
![wowscrnshot_070314_175757](https://cloud.githubusercontent.com/assets/417389/3470438/5c9293da-02ba-11e4-9ff9-0749b78cf793.jpg)

log:

Error in CMSG_QUESTGIVER_CHOOSE_REWARD: player Roga (guid 11) tried to get invalid reward (73215) (possible packet-hacking detected)

**Comment by zamalaev** [comment]
no
