### ISSUE TITLE
learn all my class bug

### ISSUE THREAD

**Issue by sciasfreelancer** [ProjectSkyfire/SkyFire.548#513]
Prevented sending disabled opcode [SMSG_SET_FLAT_SPELL_MODIFIER 0x0 (0)] to [Player: Sciasgnome (Guid: 5, Account: 1)]
Prevented sending disabled opcode [SMSG_SET_FLAT_SPELL_MODIFIER 0x0 (0)] to [Player: Sciasgnome (Guid: 5, Account: 1)]
Prevented sending disabled opcode [SMSG_SET_FLAT_SPELL_MODIFIER 0x0 (0)] to [Player: Sciasgnome (Guid: 5, Account: 1)]
Prevented sending disabled opcode [SMSG_SET_FLAT_SPELL_MODIFIER 0x0 (0)] to [Player: Sciasgnome (Guid: 5, Account: 1)]
Prevented sending disabled opcode [SMSG_SET_FLAT_SPELL_MODIFIER 0x0 (0)] to [Player: Sciasgnome (Guid: 5, Account: 1)]
Prevented sending disabled opcode [SMSG_SET_FLAT_SPELL_MODIFIER 0x0 (0)] to [Player: Sciasgnome (Guid: 5, Account: 1)]
Prevented sending disabled opcode [SMSG_SET_PCT_SPELL_MODIFIER 0x0 (0)] to [Player: Sciasgnome (Guid: 5, Account: 1)]
Prevented sending disabled opcode [SMSG_SET_PCT_SPELL_MODIFIER 0x0 (0)] to [Player: Sciasgnome (Guid: 5, Account: 1)]
Prevented sending disabled opcode [SMSG_SET_PCT_SPELL_MODIFIER 0x0 (0)] to [Player: Sciasgnome (Guid: 5, Account: 1)]
Prevented sending disabled opcode [SMSG_SET_FLAT_SPELL_MODIFIER 0x0 (0)] to [Player: Sciasgnome (Guid: 5, Account: 1)]
Prevented sending disabled opcode [SMSG_SET_PCT_SPELL_MODIFIER 0x0 (0)] to [Player: Sciasgnome (Guid: 5, Account: 1)]
Prevented sending disabled opcode [SMSG_SET_FLAT_SPELL_MODIFIER 0x0 (0)] to [Player: Sciasgnome (Guid: 5, Account: 1)]
Prevented sending disabled opcode [SMSG_SET_FLAT_SPELL_MODIFIER 0x0 (0)] to [Player: Sciasgnome (Guid: 5, Account: 1)]
Command: .learn all my class [Player: Sciasgnome (Guid: 5) (Account: 1) X: -4990.589844 Y: 757.780640 Z: 288.484802 Map: 0 (Восточные королевства) Area: 5495 (Гномреган) Zone: Дун Морог Selected player: Sciasgnome (GUID: 5)]
Segmentation fault

.learn all my class causes "segmentation fault" and then worldserver shutdowns.

**Comment by DrEhsan** [comment]
please submit the crash log in debug mode

**Comment by sciasfreelancer** [comment]
Apperantly I don't know how to do that, but you can enter dwarf race and type .level 255 .learn all my class and you instantly will get the crash :)

**Comment by AriDEV** [comment]
did u tryed it with level 90 dwarf ? the problem is there are no spells in the dbc for level91+ dwarfs. so u cant lern somthing that dont exists for such level ^^

**Comment by SkyFire** [comment]
Can't reproduce. This may have been addressed already. Make a new report if needed.
