### ISSUE TITLE
Pandarian NPC & movement sequence

### ISSUE THREAD

**Issue by sciasfreelancer** [ProjectSkyfire/SkyFire.548#514]
Unit::WriteMovementInfo: No movement sequence found for opcode [SMSG_SPLINE_MOVE_UNROOT 0x0 (0)]
Unit::WriteMovementInfo: No movement sequence found for opcode [SMSG_SPLINE_MOVE_UNROOT 0x0 (0)]
Unit::WriteMovementInfo: No movement sequence found for opcode [SMSG_SPLINE_MOVE_SET_RUN_MODE 0x0 (0)]

================
Pandarian mobs dont exist after going thurther, not spawned or not read from dbc ?

**Comment by ProjectcoreDevs** [comment]
not spawned

**Comment by AriDEV** [comment]
blame fire fox for auto adding labels Q.Q

**Comment by DrEhsan** [comment]
lol

**Comment by ProjectcoreDevs** [comment]
SPLINE_MOVE opcodes are now fixed...
