### ISSUE TITLE
worldserver.exe crash 

### ISSUE THREAD

**Issue by demooo** [ProjectSkyfire/SkyFire.548#516]
Arrival to instance raid 10man   worldserver.exe The crash is and can't Change raid mod for 10man hc or 25man norm and hc 

enter  instances Icc  , Rs , Toc , ulduar , and ... worldserver.exe crash
I am grateful to examine this topic

Thanks a lot

**Comment by RedSonja** [comment]
I am not sure what I am doing wrong, I can get it to run on my personal computer but the worldserver.exe crashes in appx 10-15 seconds on my server machine. Any ideas?  The dbs, core, and configs are all identical except for the address, since they are different machines and ips.

**Comment by akrom23** [comment]
Post crashlog.

**Comment by RedSonja** [comment]
Revision: SkyFire 5.x.x rev. 1ccd1354eb34 2015-01-25 16:33:12 -0600 (master branch) (Win32, RelWithDebInfo)
Date 28:1:2015. Time 12:23 
//=====================================================
*** Hardware ***
Processor: Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz
Number Of Processors: 4
Physical Memory: 4194303 KB (Available: 4194303 KB)
Commit Charge Limit: 4194303 KB

*** Operation System ***
Windows 7 Professional Service Pack 1 (Version 6.1, Build 7601)

//=====================================================
Exception code: C0000005 ACCESS_VIOLATION
Fault address:  007CBC25 01:0063AC25 T:\MoPworld\worldserver.exe

Registers:
EAX:0759B2B8
EBX:000000C8
ECX:00000000
EDX:000000C8
ESI:2EF90A98
EDI:000000C8
CS:EIP:0023:007CBC25
SS:ESP:002B:36B2FB44  EBP:36B2FB9C
DS:002B  ES:002B  FS:0053  GS:002B
Flags:00010246

Call stack:

**Comment by alterego21** [comment]
Compile in debug. Then post on pastebin.  Send only the link.

**Comment by RedSonja** [comment]
The weird thing is it doesn't crash at all on my personal computer, and everything is the same but the ip.

**Comment by akrom23** [comment]
As @alterego21 said, compile in debug (or in RelWithDebInfo) and then send link to crashlog.

**Comment by RedSonja** [comment]
http://pastebin.com/n3Xwp25X  is in RelWithDebInfo

**Comment by RedSonja** [comment]
I got it to run, but now cannot login using RealmServerPort =3725 any one have an idea?
Just to be clear 3724 is already being used.

**Comment by akrom23** [comment]
"This paste has been removed!"

**Comment by demooo** [comment]
How do you say had to do with the topic?
What is the port to crash instance or Change raid mod ? !!!!!!!!!!
Or compile in debug (or in RelWithDebInfo) ؟!!!!!!!!!!!! 
:O

**Comment by demooo** [comment]
It seems the problem has not anyone noticed?
Or it did not matter to anyone?
Or low intelligence level?
Skyfire or not it's important that I have not said anything to fix it

**Comment by AriDEV** [comment]
@demooo 
1.) thanks for your report, 
2.) there cant be a crash at entering dungeons or raids at skyfire cause they are disabled if u are not using skyfire core but a custom core, make sure to use skyfire core. instead of custom branched core.
3.) it can take time to test issues and fix them.
4.) be patient.

:)

**Comment by AriDEV** [comment]
@RedSonja pls dont merge 2 different issues into 1 open your own issue :)

**Comment by Zerixx** [comment]
Probably same old shit, different day. We see this all the time. Wait for a fix.

**Comment by DrEhsan** [comment]
“We are all born ignorant, but one must work hard to remain stupid.”
> Benjamin Franklin
