### ISSUE TITLE
Spell object/creature player model visibility

### ISSUE THREAD

**Issue by DoodleZero** [ProjectSkyfire/SkyFire.548#517]
Spells which "spawn visual objects/creature player model" (Ex. Healing Sphere, Frozen Orb, Ursol's Vortex, Rune of Power, Angelic Feather...Mirror Images etc) doesn't show any visual effect, for example spell Healing Sphere should to spawn green orb (visual object), or mirror images (should to spawn creatures which have same model like your character...) and they spawn them but object/creature is invisible.

If you need more informations feel free to ask me.
Any suggestion for fix is welcome.

Core revision: a434d2d

**Comment by shocky4** [comment]
Confirmed, it's pretty much spells that are area triggers or spells that are spawned, quite an annoying issue, tried to fix it myself but no luck yet

**Comment by Goatform** [comment]
Confirmed!

**Comment by Linwood-WP** [comment]
No news ?
