### ISSUE TITLE
spirit healer not working

### ISSUE THREAD

**Issue by dree22** [ProjectSkyfire/SkyFire.548#519]
spirit healer not working pls help me and my body does not appear on the map to revive
pd: I not use repack map .sorry my bad english
ss
http://i.imgur.com/6MoLas3.jpg?1
http://i.imgur.com/VySADhR.jpg?1
http://i.imgur.com/WKWrtc1.jpg?1
http://i.imgur.com/RygeF3w.jpg?1
http://i.imgur.com/ZGXOoYW.jpg?1

**Comment by ProjectcoreDevs** [comment]
fixed here : https://github.com/ProjectSkyfire/SkyFire.548/pull/520
