### ISSUE TITLE
Please update the rename opcode

### ISSUE THREAD

**Issue by RAlexis** [ProjectSkyfire/SkyFire.548#521]
Hey. It's 0x000 right now, if you could update the opcode value & strucure that'd be great! Thanks!

**Comment by ProjectcoreDevs** [comment]
we update the opcode with structure ! :)

**Comment by RAlexis** [comment]
Thaks @ProjectcoreDevs.

**Comment by RAlexis** [comment]
Any update?

**Comment by ProjectcoreDevs** [comment]
on one week +100 opcode added with structure ! it's a good work i think !

**Comment by RAlexis** [comment]
I understand, but I mean SMSG_CHAR_RENAME.

**Comment by ProjectcoreDevs** [comment]
ah, for this opcode... ok, i will update it for close this issue :)

**Comment by ProjectcoreDevs** [comment]
update in 64a1cf531631b04ded5b7f0b361fef1b5590996e

**Comment by RAlexis** [comment]
Thank you!
