### ISSUE TITLE
bug learn proff

### ISSUE THREAD

**Issue by dree22** [ProjectSkyfire/SkyFire.548#522]
ss
http://i.imgur.com/wZpZ2g4.jpg?1

pls help me

greatz

**Comment by ProjectcoreDevs** [comment]
You cant learn or other bug? with somes details it's so much !

**Comment by dree22** [comment]
i cant learn primary professions

**Comment by Rushor** [comment]
what happens if you click on learn?

**Comment by dree22** [comment]
leaves no click, because by clicking learns nothing, you can only learn  secondary professions example: kitchen

sorry my bad english

help me

**Comment by dree22** [comment]
fix?

**Comment by alterego21** [comment]
Wtf. Keep your panties on. Someone will get to it. We are not your personal
coders.

**Comment by dree22** [comment]
sorry men

**Comment by AriDEV** [comment]
@alterego21 why so toxic ? ^^

**Comment by ProjectcoreDevs** [comment]
i'm ok with @alterego21! the trainer system need a rewrite and the secondary trainer work because he use spell_learn_spell opcode. primary use trainer_buy_result (not sure i don't have the time for look it)

**Comment by ProjectcoreDevs** [comment]
fixed now in build c573446791a11616d8c78bc72dd69057b3b08ac9
