### ISSUE TITLE
 problems with permissions of player accounts

### ISSUE THREAD

**Issue by dree22** [ProjectSkyfire/SkyFire.548#523]
Players have the following commands GM:
account lvl 0:
.modify
.npc
.anounce
.pet
.quest
.mute
.ban
.server
.kick
these permits were coming so with the code, how can fix this?

**Comment by Rushor** [comment]
increase the permission for these commands and they will not be available for player.

**Comment by mayorCuba** [comment]
look at the command table and put the security field 6, 8, 10 where ever

**Comment by alterego21** [comment]
I will have a look at it. The sql table needs an update. I'm traveling
right now so when I get done I will look.

**Comment by dree22** [comment]
thx guys:D

**Comment by SkyFire** [comment]
Already addressed.
