### ISSUE TITLE
Quest Life Savings

### ISSUE THREAD

**Issue by RedSonja** [ProjectSkyfire/SkyFire.548#528]
Go to turn in the quest with Trade Prince Gallywix, and it tries to take you to a cut screen that is not available. The screen goes black and you can not get it back, Tried relogging, cleaning cache the screeen stays black.

http://www.wowhead.com/quest=14126/life-savings

**Comment by danlapps** [comment]
i dont have DB access right now but do quest cast http://www.wowhead.com/spell=91847/life-savings-quest-complete on complete ?

**Comment by danlapps** [comment]
spell does Effect #1
Apply Aura: Screen Effect (803)  

might be related

**Comment by AriDEV** [comment]
https://github.com/ProjectSkyfire/SkyFire.548/commit/dd43b8c5068b73b4ed0222fdb0947a766e43fdac
