### ISSUE TITLE
Expansion problem

### ISSUE THREAD

**Issue by dree22** [ProjectSkyfire/SkyFire.548#531]
I have a problem with the expansions, it says that i need catacysm, pandaria and tbc, neither go to outlands, northrend, catacysm maps, pandaria maps, help please
http://i.imgur.com/xCKnYC7.jpg
http://i.imgur.com/dviNbvE.jpg
pls help me

**Comment by Exodius** [comment]
I believe you didn't set proper "Expansion Addon Level" to the account.
Bring up the console and type
```
.account set addon 5
```
I believe that value is 5.

**Comment by dree22** [comment]
thx you

**Comment by ProjectcoreDevs** [comment]
resolved
