### ISSUE TITLE
Crash when entering a dungeon

### ISSUE THREAD

**Issue by Deftor** [ProjectSkyfire/SkyFire.548#535]
At the entrance to the cave , for example Siege of Orgrimmar , worldserver crash. (just tested Icecrown Citadel and others .) Already had a similar problem , but the solution was not. Can I find out when it will be fixed or could you tell me what could be the problem?

Sorry for the English!

**Comment by ProjectcoreDevs** [comment]
you have a debug log file? 10 end lines of server.log

**Comment by ProjectcoreDevs** [comment]
fixed 76558d57b92db964c5b6f71801d6ca4e6931b9d3
