### ISSUE TITLE
[CRASH] Worldserver.exe - Logging in

### ISSUE THREAD

**Issue by Shandu** [ProjectSkyfire/SkyFire.548#537]
Hi,

I created a dwarf mage, tried to login into game, but worldserver.exe get crashed (almost finished loadingscreen) - showing up some unknown opcodes.

Rev: 21210edde1276bab4d240743107f825d2bd784c2

No defined handler for opcode [UNKNOWN OPCODE 0x68 (104)] sent by [Player: Olaf (Guid: 2, Account: 2)]

**Comment by ProjectcoreDevs** [comment]
yes the 0x0068 is CMSG_UPDATE_ACCOUNT_DATA i will work on. but it's not the reason for the crash . can you read the end of file "server.log" and copy/paste the 10 end line of this file here plz .

**Comment by Shandu** [comment]
unfortunetly he only wrote 1 line into server.log and that was:
"No defined handler for opcode [UNKNOWN OPCODE 0x68 (104)] sent by [Player: Olaf (Guid: 2, Account: 2)]"

If you wish, I can try to reproduce this in debug mode...

**Comment by ProjectcoreDevs** [comment]
hum... i don't have a problem with dwarf mage ... you have the new database? release 9?

**Comment by Shandu** [comment]
yea downloaded, and applied all updates from /sql/updates...
I'm using maps & dbc from Apex (5.4.8) maybe it is problem of that?

**Comment by ProjectcoreDevs** [comment]
ok... i think, it's apex files problem, i ve tryed all race on server here, i don't have error... if you can, execute in debug mod for look the error ! here i can't help you. i push a new update for database now, execute it and retry.

**Comment by Shandu** [comment]
Thanks, I will try. Unfortunetly I don't have a full downloaded 5.4.8 client, that means I will have probably problems find 5.4.8 DBC for Skyfire.

**Comment by Shandu** [comment]
I redownloaded now 5.4.8 , now after connecting his showing me realm is offline, but auth & worldserver.exe still running, any idea?

**Comment by ProjectcoreDevs** [comment]
look in realmlist database: gamebuild= 18414, adress 127.0.0.1, if is good, look on worldserver.conf = RealmID = 1

**Comment by Shandu** [comment]
already chcked, everything is setting up right. After logging into account, realmlist appears and shows realm offline :/
worldserver.conf:
RealmID = 1

logon_realmlist:
address = 127.0.0.1
gamebuild = 18414

**Comment by ProjectcoreDevs** [comment]
for help you can /w on irc channel #project_skyfire you can use rizon.net/chat for connect or others app

**Comment by zamalaev** [comment]
confirm

log: Unable to retrieve class or race data

last rev

**Comment by ProjectcoreDevs** [comment]
update your auth.sql !
