### ISSUE TITLE
problem pls help

### ISSUE THREAD

**Issue by dree22** [ProjectSkyfire/SkyFire.548#538]
I've got some issues with pandaria. I cant go to any of the expansions of TBC, Wotlk, Cataclysm or Pandaria. You see, when I want to cross the dark portal it doesn't work at all, and the teleports doesnt wort neither

**Comment by ProjectcoreDevs** [comment]
what version you use ? last database? last core? or a repack?

**Comment by dree22** [comment]
last db and last core

**Comment by ProjectcoreDevs** [comment]
disconnect the worldserver.exe and go on database (auth) go in table account and set the column "expansion" to 5 on the account... normaly it's the default value !

**Comment by dree22** [comment]
I'll try this, let you know if it works

**Comment by dree22** [comment]
it didn't work out.. And when the players try to go across the dark portal it doesn't load the map. The error that throws its this one:
Prevented sending disabled opcode [SMSG_TRANSFER_ABORTED 0x0 (0)] to [Player: Test (Guid: 820, Account: 2)]
Prevented sending disabled opcode [SMSG_TRANSFER_ABORTED 0x0 (0)] to [Player: Test (Guid: 820, Account: 2)]
Prevented sending disabled opcode [SMSG_TRANSFER_ABORTED 0x0 (0)] to [Player: Test (Guid: 820, Account: 2)]
Prevented sending disabled opcode [SMSG_TRANSFER_ABORTED 0x0 (0)] to [Player: Test (Guid: 820, Account: 2)]

**Comment by dree22** [comment]
Prevented sending disabled opcode 
Prevented sending disabled opcode [SMSG_TRANSFER_ABORTED 0x0 (0)] to [Player: Test (Guid: 820, Account: 2)]
Prevented sending disabled opcode [SMSG_TRANSFER_ABORTED 0x0 (0)] to [Player: Test (Guid: 820, Account: 2)]
Prevented sending disabled opcode [SMSG_TRANSFER_ABORTED 0x0 (0)] to [Player: Test (Guid: 820, Account: 2)]
Prevented sending disabled opcode [SMSG_TRANSFER_ABORTED 0x0 (0)] to [Player: Test (Guid: 820, Account: 2)]

**Comment by ProjectcoreDevs** [comment]
what s the error in game? 
Prevented sending disabled opcode [SMSG_TRANSFER_ABORTED 0x0 (0)] to [Player: Test (Guid: 820, Account: 2)] is not one error it's just one opcode not active i will work on.

**Comment by dree22** [comment]
error in console 
http://i.imgur.com/xCKnYC7.jpg

**Comment by ProjectcoreDevs** [comment]
try with the new update. compile the new core. I've tested, he work correcly ! i have update SMSG_TRANSFER_ABORTED, he show now the reason normaly.

**Comment by dree22** [comment]
Thanks proyectoredevs, the issue has been solved I really aprecciate it.

**Comment by ProjectcoreDevs** [comment]
:) good day
