### ISSUE TITLE
BDK spec worldserver crash

### ISSUE THREAD

**Issue by SmythX** [ProjectSkyfire/SkyFire.548#541]
When player try to learn blood spec as death knight he cause server crash.

Step to reproduce:
1. Create DK
2. Choose Blood Specialization
Result = Server Crash

Older reports:
#469 
#486 

Core:  adbdbf0

**Comment by Zhelyazkov** [comment]
http://pastebin.com/raw.php?i=H6R4rKHp

**Comment by Goatform** [comment]
Yeah, it's Improved Blood Presence aura. I simply added that aura into "disables" table and I temporary solved crash.

**Comment by Zhelyazkov** [comment]
Same here..

**Comment by Zhelyazkov** [comment]
The issue is, it's not just 1 spell.. also noticed it does the same thing for Conversion and some monk spell

**Comment by Goatform** [comment]
I don't have worldcrash with other classes specializations, only with blood dk spec.

**Comment by Zhelyazkov** [comment]
Try Conversion talent

**Comment by Goatform** [comment]
Yeah Conversion crash core too but that's not same issue, I mean crashlog.

**Comment by caffeine239** [comment]
Debug core for crash and u should be able to fix

**Comment by Zhelyazkov** [comment]
No its exactly the same, trust me

**Comment by Goatform** [comment]
I'm a bit confused because I don't know why Improved Blood Presence use m_enchantDuration

**Comment by Zhelyazkov** [comment]
Indeed, it really is..

**Comment by Hmmaster** [comment]
it seems its doing some thing with m_values that makes it unstable

**Comment by Goatform** [comment]
Hmm I found something interesting, look at this: https://github.com/ProjectSkyfire/SkyFire.548/blob/master/src/server/game/Entities/Object/Object.cpp#L341-L383
