### ISSUE TITLE
Tunneling Worm Kezahn Add missing Loot !

### ISSUE THREAD

**Issue by Shoxxo** [ProjectSkyfire/SkyFire.548#542]
``` sql
UPDATE `creature_template` SET `lootid`=34865 WHERE `entry`=34865;
DELETE FROM `creature_loot_template` WHERE `entry`=34865;
INSERT INTO `creature_loot_template` (`entry`,`item`,`ChanceOrQuestChance`,`lootmode`,`groupid`,`mincountOrRef`,`maxcount`) VALUES
(34865, 828, 0.5, 1, 0, 1, 1),
(34865, 1411, 0.5, 1, 0, 1, 1),
(34865, 23333, 0.5, 1, 0, 1, 1),
(34865, 1431, 0.5, 1, 0, 1, 1),
(34865, 2589, 0.5, 1, 0, 1, 1),
(34865, 5571, 0.5, 1, 0, 1, 1),
(34865, 805, 0.5, 1, 0, 1, 1),
(34865, 5572, 0.5, 1, 0, 1, 1),
(34865, 4469, 0.5, 1, 0, 1, 1),
(34865, 55983, 25, 1, 0, 1, 1),
(34865, 55973, 75, 1, 0, 1, 1);
```

Added Missing Loot from Kezahn Quest Mob Tunneling Worm.

**Comment by AriDEV** [comment]
VALUES (34865, 11111, 0.1, 1, 0, -11111, 1), -- should be used instead the bags instead of the equip u should use world drop reference for level 1 mobs, and just add a simple 2 entrys for the inert.

**Comment by Xunil1337** [comment]
http://www.wowhead.com/npc=34865/tunneling-worm

All okay ! My Fix is same in TrinityCore and Accepted !

**Comment by AriDEV** [comment]
u should not use wowhead for world drops, wowhead is good for creature loot but not for referencing world drops. remember evrything that is lower then 1% is a world drop taken from a referenced table because it dont drop evrytime and if it drop the chance is low that the player is using wowhead addon.

**Comment by Xunil1337** [comment]
if it is possible and you can write in german pls tell me that in german via pm... I have an appointment tomorrow to go to the court, so I'm going to sleep now!

**Comment by AriDEV** [comment]
http://www.wowhead.com/npc=42185,
http://www.wowhead.com/npc=37112,
schau dir mal diese npcs an.
wenn du denn loot als referenceloot fur world drop gibst kannst du mit deinen fix gleich mehrere
fixen ohne grosen aufwand indem du gleich mehreren den reference loot table aufrufs .) anstadt jedem mob einzeln die gleichen loots rein zu stopfen .)

**Comment by AriDEV** [comment]
und sind sicherlich noch mehrere 100+ mobs mit gleichen table .)

**Comment by Xunil1337** [comment]
Das ist genial... Da ich eh nicht pennen kann, kann ich ja am iPad noch was lernen
