### ISSUE TITLE
Missing Scripts for legendary back.

### ISSUE THREAD

**Issue by Shoxxo** [ProjectSkyfire/SkyFire.548#543]
https://github.com/ProjectSkyfire/SkyFire.548/commit/6d8f47c75dce146ef209ba61e613a966f635fc87

Script File : https://github.com/ProjectSkyfire/SkyFire.548/blob/master/src/server/scripts/Spells/spell_item.cpp

Items : http://www.wowhead.com/items=4?filter=qu=5;sl=16

This are the items... We Can not use it withoud a fix ...

**Comment by JunkyBulgaria** [comment]
The core is not even playable yet due to the missing opcodes.. why would you want these cloaks scripted?
