### ISSUE TITLE
Quests

### ISSUE THREAD

**Issue by Nuppi** [ProjectSkyfire/SkyFire.548#547]
questing are not feasible. they always catch resist from scratch. as if there is a timer is running.

**Comment by Rawaho** [comment]
@Nuppi there are multiple issues with the quest system that I'll have to resolve.

**Comment by RedSonja** [comment]
How much work would it be to take the quest_template and add the fields back in that are there in for example (trinity's ) and remove the quest_objective and quest_objective_effects. I have found that having the extra tables for this seems to complicate things a lot. I am just asking and would be willing to help when and where I can.

**Comment by Rawaho** [comment]
@RedSonja that would be stupid, no point going backwards, just need to correct a few issues the system has. 
You shouldn't need to touch the quest template and quest objective tables, all but a few quests are missing from the tables.

**Comment by RedSonja** [comment]
Did I understand you correctly, "all but a few quests are missing"? I do know that the starting zone quests are a total clusterf.... atm  I have worked with trinity for many years, and the changes in the db in that area just seems like more work than it should be. As for being stupid, actually learning as you go is not being stupid, if you have to go backward to fix something or make it better only helps the end result does it not?

**Comment by Rawaho** [comment]
@RedSonja what I meant was, most of the quest data is already in the database and was dumped from retail when it was on patch 5.4.7, you shouldn't need to change any of it.
The way the quest system worked changed in MoP, no need to keep legacy systems around; the new system can do exactly what the old system did but it's more Blizzlike, nothing wrong with that.

**Comment by RedSonja** [comment]
Ok however, the starter quests are completely bugged in all areas. Some do work yes but for the most part they don't. Npcs are giving all quests in some cases instead of them being in any kind of order. Where other Npcs are giving quests that should not be gotten either by class or race etc..There is no phasing in a lot of the beginning areas at all. I am all for Blizzlike and was only offering a suggestion and possible help.

**Comment by ffdevill** [comment]
@RedSonja that has to do with prerq quest as well as race/class in the quest template database has nothing to do wit the new structure. so if you want to fix the quest givers have all the quests and not in order you need to start there. hope that helps

**Comment by ffdevill** [comment]
also we will be doing a bit of work DB side and shearing them here as well so as to help with where and what we can. I say we not as in Skyfire I have a small group here at home who will be helping with this.
