### ISSUE TITLE
Rogue Talents

### ISSUE THREAD

**Issue by Nuppi** [ProjectSkyfire/SkyFire.548#549]
Hi
Rogue Talents lvl 15 Nightstalker  Server Crash.

**Comment by blindspell** [comment]
build the core in relwithdebinfo or debug mode and post your crashlog so you can help the team to resolve your issue

**Comment by Goatform** [comment]
Yeah as @blindspell said, give us more details such as crashlogs and tips to reproduce crash.

**Comment by Goatform** [comment]
but I think that is same as #541

**Comment by SkyFire** [comment]
Still would need a crashlog

**Comment by Goatform** [comment]
Yeah, I agree with you.
