### ISSUE TITLE
Raid Difficulty move Server error

### ISSUE THREAD

**Issue by World-of-Midgard** [ProjectSkyfire/SkyFire.548#550]
hello
I have a problem with Raid Difficulty.
If I put 10 players on players from 20 or 10 Player (Heroic) on 10 player wants I get a server error.
there can anyone tell me how to fix this?

http://img4.fotos-hochladen.net/uploads/instanzfehlerpmflrvhk49.jpg
sorry for my bad eng.

**Comment by AriDEV** [comment]
u cant change difficulties in raid u need to go out of raid and then change the difficulty :dash:

**Comment by Nuppi** [comment]
the same here, which set more than 10 normal and the server crach

**Comment by DeActiveDev** [comment]
with In the entry instance don't have  problem  and  server crach ?

**Comment by World-of-Midgard** [comment]
it is normally from 10 to 20 or HC and dan back to 10 players normally crashes the server from
