### ISSUE TITLE
leave party crash server

### ISSUE THREAD

**Issue by dree22** [ProjectSkyfire/SkyFire.548#554]
check pls

leave party crash server

regards

**Comment by blindspell** [comment]
provide crash log (make sure you have build the core in releasewithdebinfo or just debug)

**Comment by imbavirus** [comment]
Here's the crash log for the issue:
http://pastebin.com/Jdib53BM

Appears to be a problem with Instance resets, I'm not sure if its related but when I join a group it says "Dungeon Difficulty: 10 player Heroic", 

I also used to be able to enter instances previously but after applying some fixes found on here recently I get a crash when entering an instance too with the following crash log: 
http://pastebin.com/SFmfmrqM

I'm not sure if all the stuff I mentioned are related but it seems to be all pointing back to an issue with dungeon/raid difficulty.
