### ISSUE TITLE
There's no NPC in This maps

### ISSUE THREAD

**Issue by dree22** [ProjectSkyfire/SkyFire.548#555]
There's no Npc in no one of this maps: Silithus,felwood,the wandering isle,gilneas city, Feralas, Un'goro crater, Desolace & Hyjal, may you help me please?

regards

**Comment by ProjectcoreDevs** [comment]
need database update, the database is very broken, if you have others informations, post it for debug...

**Comment by cavaclub** [comment]
well seems all wild life and NPCs...
