### ISSUE TITLE
SMSG_GUILD_EVENT error

### ISSUE THREAD

**Issue by frozen4** [ProjectSkyfire/SkyFire.548#557]
can not add guild rank
when i try to add guild rank the server log this message
Prevented sending disabled opcode [SMSG_GUILD_EVENT 0x0 (0)] to player

**Comment by Rawaho** [comment]
@frozen4 SMSG_GUILD_EVENT is obsolete in this patch, an opcode will need to be added.

**Comment by DeActiveDev** [comment]
SMSG_GUILD_EVENT,                        0x1B69

**Comment by Rawaho** [comment]
@DeActiveDev there is no single opcode anymore, each event has its own.

**Comment by ProjectcoreDevs** [comment]
confirmed it's ClientGuildEventRanksUpdated i don't have SMSG_GUILD_EVENT on my list ... i think it's obsolete i'm ok with rawaho i will look your error with the guild rank
