### ISSUE TITLE
vehicles not working

### ISSUE THREAD

**Issue by xehanort563** [ProjectSkyfire/SkyFire.548#561]
The core has a huge problem.
It is the vehicle bug all of them arent working it would be really nice if the skyfire team could look at this problem because it ruins the whole experience at some quests, and you cant play normal anymore in some places
yours faithfully xehanort

**Comment by Zerixx** [comment]
Is this really a "huge problem"?

**Comment by World-of-Midgard** [comment]
yes it is, it lacks the spellbar at all.
Cannon will not get the vehicle Ulduar will not do.

lined many quest are not feasible even at the start area todesritter can not make it to the end.

**Comment by ProjectcoreDevs** [comment]
i don't know the problem, you have the exemple?i know the problem is the vehicle but what is the problem exacly?actionbar? can you find the name of quest or pnj ect...for help easly??

**Comment by World-of-Midgard** [comment]
hello
I once small cutout on images what I mean
http://www.fotos-hochladen.net/uploads/wowscrnshot032ukwap0nqsr.jpg
http://www.fotos-hochladen.net/uploads/wowscrnshot032uoiqargx16.jpg
http://www.fotos-hochladen.net/uploads/wowscrnshot0321ks64gnfbt.jpg
http://www.fotos-hochladen.net/uploads/wowscrnshot032dux0klej8g.jpg

I think it is very important that these things are working correctly.

It was only a small part I would like to show. The problem all vehicles.
sorry for my bad english.

Also a thank you to your team that you work even more and this version.
Please continue.

**Comment by Zerixx** [comment]
I don't know about you, but it seems to me that vehicle packets haven't been touched in ages. You ought to get on that.

**Comment by caffeine239** [comment]
You ought too

**Comment by World-of-Midgard** [comment]
be careful xehanort hacked the database of our team  :(

**Comment by ProjectcoreDevs** [comment]
test with = c5b4d534c30464efee041323964880de477db72e

**Comment by AriDEV** [comment]
https://github.com/ProjectSkyfire/SkyFire.548/commit/77195e2dd5c8bffc08e4b87833b3a17141216f4b
