### ISSUE TITLE
Enter Instance bug

### ISSUE THREAD

**Issue by demooo** [ProjectSkyfire/SkyFire.548#562]
hi : when player go in the instance server crashed , i think this problem is for  ( bool InstanceMap::AddPlayerToMap(Player\* player) ) or place save player for enter instance maps  ,  because if we disable in the map.cpp, line 2803 ( ASSERT(playerBind->save == mapSave); ) now can go in the instance but any npc and objects not appear , i see some another sources for this problem have identical with doungen ( custom code) , this case In another topics , maybe for handler we have crash( likely ) , I will be grateful if check and fixing .

**Comment by Flameshot** [comment]
Still present, but why?

**Comment by SkyFire** [comment]
Fix it.
