### ISSUE TITLE
Throne of Thunder Instance 

### ISSUE THREAD

**Issue by World-of-Midgard** [ProjectSkyfire/SkyFire.548#563]
Unfortunately, you can not get into the instance Throne of Thunder.
I have just teleported into

"MoguIslandLootRoom" .go -470 1106 155 1135
after loading the instance there is always a server failure
http://www.fotos-hochladen.net/uploads/wowscrnshot032m3xe9obj41.jpg

can this be repaired?

**Comment by Ulduar** [comment]
Need add instance_template for enter.
``` SQL
DELETE FROM `instance_template` WHERE `map` = 1098;
INSERT INTO `instance_template` (`map`, `parent`, `allowMount`) VALUES
(1098, 870, 0); -- Throne of Thunder Raid. AllowMount = true
```

**Comment by Ulduar** [comment]
@AriDEV please, you can add sql from second post in database?
