### ISSUE TITLE
_BroadcastEvent  

### ISSUE THREAD

**Issue by frozen4** [ProjectSkyfire/SkyFire.548#564]
the opcode SMSG_GUILD_EVENT is obsolete  so the _BroadcastEvent  is also obsolete  

SetRankInfo,  LeaveMember, RemoveMember, UpdateMemberRank, MemberWithdrawMoney, MemberLogout, SendLoginInfo, AddMember, DeleteMember will log message

 Prevented sending disabled opcode [SMSG_GUILD_EVENT 0x0 (0)] to player

**Comment by ProjectcoreDevs** [comment]
Yes i work on! But it's replaced by smsg_guild_update_roster
