### ISSUE TITLE
monk bug

### ISSUE THREAD

**Issue by dree22** [ProjectSkyfire/SkyFire.548#565]
Monk has a problem when exiting the game gets stuck unable to move only forward back any solution or idea about this bug, greetings.
ss:
http://i.imgur.com/kQVjKy4.jpg
http://i.imgur.com/4DdZkE0.jpg

**Comment by Kr4v3n5** [comment]
^^, stance bug

**Comment by Anddrw** [comment]
> AriDEV closed this on 17 May 2015

Same problem here.

**Comment by Shoxxo** [comment]
Please submit us the Debug Log ! Than we can see what happens.
