### ISSUE TITLE
Dungeon Finder has problems

### ISSUE THREAD

**Issue by dree22** [ProjectSkyfire/SkyFire.548#566]
Dungeon Finder does not work because when squeezed does not initiate any function (tank - dps - heler) does not appear the eye and can not do dungeons with the search

greetings

ss

http://i.imgur.com/AKEBqZS.jpg

**Comment by ProjectcoreDevs** [comment]
alls opcodes for the finder are not implemented ! it's not a priority !

**Comment by Atis6** [comment]
Something new with this? Will work?

**Comment by ProjectcoreDevs** [comment]
work in progress on the dev_lfg_system branch...
