### ISSUE TITLE
counter resets quest preventing finish the mission

### ISSUE THREAD

**Issue by dree22** [ProjectSkyfire/SkyFire.548#567]
There is a problem with the counter missions, this is  reset when you need to kill npc,  for example:  a mission asks me to kill 10 pigs, and when I'm at 6th but 7th counts it as the first, any idea  or fix pls

greetings

**Comment by Rawaho** [comment]
I know what's causing the issue, I'll get around to correcting it soon.

**Comment by dree22** [comment]
Thx men

**Comment by AriDEV** [comment]
Should be fixed here:
https://github.com/ProjectSkyfire/SkyFire.548/commit/fcfee67d22b86666ccbe7ba78f94f4384205ab1b
