### ISSUE TITLE
flight master bug

### ISSUE THREAD

**Issue by dree22** [ProjectSkyfire/SkyFire.548#568]
when taking a flight path all goes well, but when exiting the game's character returns to the world in flight and the previous route that took
example: I take the flight path of orgrimmar to Tanaris, I leave the game and when I return to the world the character is flying towards orgrimmar and keeps flying mount set

greetings

**Comment by Zerixx** [comment]
Quite possibly it's clearing the taxi data (or destination) on logout, instead of it finishing the process. Not sure, but it's likely.

**Comment by merydwin** [comment]
Missing client movement packet for spline sync

**Comment by SkyFire** [comment]
Confirmed.

**Comment by madmax765** [comment]
Hope to see this fixed soon :D

**Comment by Goatform** [comment]
Could you make some fixes instead of begging others to fix them for you.

**Comment by madmax765** [comment]
I dont know, lets ask your mom

**Comment by madmax765** [comment]
Who's  begging  (_!_) Hole ? I just said it would be nice.

**Comment by Goatform** [comment]
Most of you. Whatever, I do not want to compete with nobody especially with guys like you. I just wanted to say that it will be better to fix something by yourself and push some fixes on this repo instead of pulling other guys for sleeve to fix something for you guys. Also, let's not talk about this anymore.

**Comment by madmax765** [comment]
Then why you still talking about it for. Maybe some guys like me dont have the Freking time like you mama boy

**Comment by SkyFire** [comment]
Seems to be a borked packet structure in the spline system. I will try and fix when I get home.

**Comment by AriDEV** [comment]
@Goatform well stop acting like if u would fix something... madmax have his right to add a confirm and a hope.

**Comment by Goatform** [comment]
@madmax765, probably. @AriDEV, I don't act like I will fix something or not, however I'd never set myself in that position to do something like that, Whatever, I said that I do not want to compete with anyone so just let's simply forget this...

**Comment by madmax765** [comment]
I thought you was going to drop it, you keep crying on and on.. you sated by you know my life. well you dont mama boy... So why dont you drop it... like your mama dose. Here let me scrach me Goatform @ss

And thankyou skyfire for trying to fix it
