### ISSUE TITLE
error compile

### ISSUE THREAD

**Issue by zamalaev** [ProjectSkyfire/SkyFire.548#570]
[ 24%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Commands/cs_go.cpp.o
/home/wow/5.4.8/src/server/scripts/Commands/cs_go.cpp: In static member function ‘static bool go_commandscript::HandleGoCreatureCommand(ChatHandler*, const char*)’:
/home/wow/5.4.8/src/server/scripts/Commands/cs_go.cpp:117:131: error: unable to find string literal operator ‘operator"" _LIKE_’

[ 25%] Building CXX object src/server/game/CMakeFiles/game.dir/Entities/Transport/Transport.cpp.o
/home/wow/5.4.8/src/server/game/Entities/Unit/Unit.cpp: In member function ‘void Unit::OutDebugInfo() const’:
/home/wow/5.4.8/src/server/game/Entities/Unit/Unit.cpp:16539:5: error: unable to find string literal operator ‘operator"" UI64FMTD’

last rev

**Comment by Zerixx** [comment]
What version of Visual Studio are you using?

**Comment by Vincent-Michael** [comment]
try:
```diff
-TC_LOG_INFO("entities.unit", "OwnerGUID " UI64FMTD ", MinionGUID " UI64FMTD ", CharmerGUID " UI64FMTD ", CharmedGUID "UI64FMTD, GetOwnerGUID(), GetMinionGUID(), GetCharmerGUID(), GetCharmGUID());
+TC_LOG_INFO("entities.unit", "OwnerGUID " UI64FMTD ", MinionGUID " UI64FMTD ", CharmerGUID " UI64FMTD ", CharmedGUID " UI64FMTD, GetOwnerGUID(), GetMinionGUID(), GetCharmerGUID(), GetCharmGUID());
```

**Comment by zamalaev** [comment]
Zerixx debian 6

**Comment by AriDEV** [comment]
should be fixed
