### ISSUE TITLE
auth problem?

### ISSUE THREAD

**Issue by zamalaev** [ProjectSkyfire/SkyFire.548#572]
![default](https://cloud.githubusercontent.com/assets/417389/6942315/61a16ddc-d88f-11e4-8c0e-1c603515610b.JPG)

server log: Unable to retrieve class or race data

core: last rev
DB: full 9 + updates
client 5.4.8 18414

**Comment by ProjectcoreDevs** [comment]
Update your auth database

**Comment by zamalaev** [comment]
ProjectcoreDevs, auth_database full!

**Comment by Goatform** [comment]
I think that it's your client issue (if it's Russian)

**Comment by zamalaev** [comment]
Goatform, Hm...... 
![default](https://cloud.githubusercontent.com/assets/417389/6943070/49164d5a-d894-11e4-86a3-23d3ee6fd702.JPG)

**Comment by ProjectcoreDevs** [comment]
look in your auth database if you have a table realm_classes & realm_races

**Comment by Goatform** [comment]
Hmm strange, everything works well for me.

**Comment by zamalaev** [comment]
close)) worldserver skyfire and authserver trinitycore + path build version 5.4.8 not work
