### ISSUE TITLE
Quest System

### ISSUE THREAD

**Issue by zamalaev** [ProjectSkyfire/SkyFire.548#573]
![default](https://cloud.githubusercontent.com/assets/417389/6945455/8551aefa-d8a2-11e4-80c3-9289574e394b.JPG)

log: Error in CMSG_QUESTGIVER_CHOOSE_REWARD: player Panda (guid 1) tried to get invalid reward (73214) (possible packet-hacking detected)

not quest complete

https://github.com/KWTeam/SkyFire.548/commit/44b898a6bb433a56ed034dd34a1cdbfe401b6e1b some fixed panda quest

**Comment by zamalaev** [comment]
https://github.com/ProjectSkyfire/SkyFire.548/issues/345

**Comment by H4D3S** [comment]
https://github.com/TrinityCore/TrinityCore/commit/d9e941dde3cc6105d5cd68ae3da55e4a7efcb244
