### ISSUE TITLE
world database

### ISSUE THREAD

**Issue by fatiima** [ProjectSkyfire/SkyFire.548#575]
hello.i cant download world database
this link is broken
http://www.projectskyfire.org/index.php?/files/

**Comment by MrLeaker** [comment]
Looool

**Comment by SkyFire** [comment]
You need to make a forum account to see the download link

**Comment by fatiima** [comment]
LOL?

i tried to register but this errro appear
in security check
URL of your website is incorrect, please check the URL of your website at www.keycaptcha.com


so where should i ask?

**Comment by SkyFire** [comment]
Registration fixed on forum

**Comment by fatiima** [comment]
ty

**Comment by SkyFire** [comment]
Fixed the latest download link. try it again
