### ISSUE TITLE
Dungeon Finder

### ISSUE THREAD

**Issue by Atis6** [ProjectSkyfire/SkyFire.548#578]
The DF opcodes still missing ?

**Comment by AriDEV** [comment]
is this a chat or a bugtracker ?

**Comment by Atis6** [comment]
So .. The DF isn't works of missing opcodes.

**Comment by AriDEV** [comment]
atilla toto neni chat ak si chces pisat tak pridi na skyfire irc...

**Comment by Atis6** [comment]
Prepácte.

**Comment by alterego21** [comment]
Engrish please.
