### ISSUE TITLE
Character Inspection don't work

### ISSUE THREAD

**Issue by gtmx1234** [ProjectSkyfire/SkyFire.548#580]
I have notice that if you try to inspect another player nothing will show up. So i think it is something wrong with the packet structure and it need a fix.

**Comment by Atis6** [comment]
Confirmed. Disabled opcode.
Prevented sending disabled opcode [SMSG_INSPECT_TALENT 0x0 (0)] to [Player: Test (Guid: 7, Account: 4)]
