### ISSUE TITLE
Some Opcode errors

### ISSUE THREAD

**Issue by Atis6** [ProjectSkyfire/SkyFire.548#581]
Received unhandled opcode [CMSG_REQUEST_CEMETERY_LIST 0x6E4 (1764)] from [Player: Aaron (Guid: 5, Account: 3)]
No defined handler for opcode [UNKNOWN OPCODE 0x1F1 (497)] sent by [Player: Aaron (Guid: 5, Account: 3)]
No defined handler for opcode [UNKNOWN OPCODE 0x1F1 (497)] sent by [Player: Aaron (Guid: 5, Account: 3)]
No defined handler for opcode [UNKNOWN OPCODE 0x1F1 (497)] sent by [Player: Aaron (Guid: 5, Account: 3)]
No defined handler for opcode [UNKNOWN OPCODE 0x1F1 (497)] sent by [Player: Aaron (Guid: 5, Account: 3)]
No defined handler for opcode [UNKNOWN OPCODE 0x1F1 (497)] sent by [Player: Aaron (Guid: 5, Account: 3)]
Unit::WriteMovementInfo: No movement sequence found for opcode [SMSG_MOVE_UPDATE_RUN_SPEED 0x0 (0)]
Prevented sending disabled opcode [SMSG_UPDATE_INSTANCE_OWNERSHIP 0x0 (0)] to [Player: Aaron (Guid: 5, Account: 3)]
No defined handler for opcode [CMSG_MOVE_FORCE_RUN_SPEED_CHANGE_ACK 0x10F3 (4339)] sent by [Player: Aaron (Guid: 5, Account: 3)]
No defined handler for opcode [UNKNOWN OPCODE 0x115B (4443)] sent by [Player: Aaron (Guid: 5, Account: 3)]
Prevented sending disabled opcode [SMSG_EQUIPMENT_SET_LIST 0x0 (0)] to [Player: Aaron (Guid: 5, Account: 3)]
Prevented sending disabled opcode [SMSG_LOAD_CUF_PROFILES 0x0 (0)] to [Player: Aaron (Guid: 5, Account: 3)]
No defined handler for opcode [UNKNOWN OPCODE 0x1A87 (6791)] sent by [Player: Aaron (Guid: 5, Account: 3)]
No defined handler for opcode [UNKNOWN OPCODE 0x640 (1600)] sent by [Player: Aaron (Guid: 5, Account: 3)]
No defined handler for opcode [UNKNOWN OPCODE 0x6F5 (1781)] sent by [Player: Aaron (Guid: 5, Account: 3)]
No defined handler for opcode [UNKNOWN OPCODE 0x77B (1915)] sent by [Player: Aaron (Guid: 5, Account: 3)]
No defined handler for opcode [UNKNOWN OPCODE 0x1F9E (8094)] sent by [Player: Aaron (Guid: 5, Account: 3)]
No defined handler for opcode [UNKNOWN OPCODE 0x44E (1102)] sent by [Player: Aaron (Guid: 5, Account: 3)]
No defined handler for opcode [UNKNOWN OPCODE 0x365 (869)] sent by [Player: Aaron (Guid: 5, Account: 3)]
No defined handler for opcode [UNKNOWN OPCODE 0x32D (813)] sent by [Player: Aaron (Guid: 5, Account: 3)]
No defined handler for opcode [UNKNOWN OPCODE 0x6B (107)] sent by [Player: Aaron (Guid: 5, Account: 3)]
No defined handler for opcode [UNKNOWN OPCODE 0x14DB (5339)] sent by [Player: Aaron (Guid: 5, Account: 3)]
No defined handler for opcode [UNKNOWN OPCODE 0x5E1 (1505)] sent by [Player: Aaron (Guid: 5, Account: 3)]
No defined handler for opcode [UNKNOWN OPCODE 0xA87 (2695)] sent by [Player: Aaron (Guid: 5, Account: 3)]
No defined handler for opcode [UNKNOWN OPCODE 0x1F89 (8073)] sent by [Player: Aaron (Guid: 5, Account: 3)]
No defined handler for opcode [UNKNOWN OPCODE 0x15A9 (5545)] sent by [Player: Aaron (Guid: 5, Account: 3)]
No defined handler for opcode [UNKNOWN OPCODE 0xCF0 (3312)] sent by [Player: Aaron (Guid: 5, Account: 3)]
No defined handler for opcode [UNKNOWN OPCODE 0x1203 (4611)] sent by [Player: Aaron (Guid: 5, Account: 3)]
Received unhandled opcode [CMSG_REQUEST_CEMETERY_LIST 0x6E4 (1764)] from [Player: Aaron (Guid: 5, Account: 3)]
Prevented sending disabled opcode [SMSG_CHAT_PLAYER_NOT_FOUND 0x0 (0)] to [Player: Aaron (Guid: 5, Account: 3)]

**Comment by SkyFire** [comment]
These are not errors. There just not complete yet.
