### ISSUE TITLE
Crash worldserver ?

### ISSUE THREAD

**Issue by devastates** [ProjectSkyfire/SkyFire.548#589]
Revision: SkyFire 5.x.x rev. ecbb59d029da+ 2015-06-30 07:28:43 +0200 (master branch) (Win32, Release)
Date 30:6:2015. Time 12:1 
//=====================================================
*** Hardware ***
Processor: Intel(R) Core(TM) i3-4005U CPU @ 1.70GHz
Number Of Processors: 4
Physical Memory: 4194303 KB (Available: 3887096 KB)
Commit Charge Limit: 4194303 KB

*** Operation System ***
Windows 8 Professional (Version 6.2, Build 9200)

//=====================================================
Exception code: C0000005 ACCESS_VIOLATION
Fault address:  014C51D4 01:003F41D4 C:\Skyfire\SkyFire.548\Build\bin\Release\worldserver.exe

Registers:
EAX:00000261
EBX:0182491C
ECX:5D770D3D
EDX:01DA6409
ESI:01824A30
EDI:01824AB0
CS:EIP:0023:014C51D4
SS:ESP:002B:0DCDE808  EBP:0DCDF818
DS:002B  ES:002B  FS:0053  GS:002B
Flags:00010212

Call stack:
Address   Frame     Function      SourceFile
014C51D4  00000000  0001:003F41D4 C:\Skyfire\SkyFire.548\Build\bin\Release\worldserver.exe
01457D32  00000000  0001:00386D32 C:\Skyfire\SkyFire.548\Build\bin\Release\worldserver.exe
0145ACB3  00000000  0001:00389CB3 C:\Skyfire\SkyFire.548\Build\bin\Release\worldserver.exe
01464C93  00000000  0001:00393C93 C:\Skyfire\SkyFire.548\Build\bin\Release\worldserver.exe
01466464  00000000  0001:00395464 C:\Skyfire\SkyFire.548\Build\bin\Release\worldserver.exe
014554EC  00000000  0001:003844EC C:\Skyfire\SkyFire.548\Build\bin\Release\worldserver.exe
014D1778  00000000  0001:00400778 C:\Skyfire\SkyFire.548\Build\bin\Release\worldserver.exe
012E1F26  00000000  0001:00210F26 C:\Skyfire\SkyFire.548\Build\bin\Release\worldserver.exe
0122942E  00000000  0001:0015842E C:\Skyfire\SkyFire.548\Build\bin\Release\worldserver.exe
012F613B  00000000  0001:0022513B C:\Skyfire\SkyFire.548\Build\bin\Release\worldserver.exe
013482DE  00000000  0001:002772DE C:\Skyfire\SkyFire.548\Build\bin\Release\worldserver.exe
62547AB3  00000000  ?invoke_i@ACE_Thread_Adapter@@EAEKXZ+93
625479EE  00000000  ?invoke@ACE_Thread_Adapter@@UAEKXZ+7E
5D77C01D  00000000  __get_tlsindex+6F
5D77C001  00000000  __get_tlsindex+53
772B7C04  00000000  BaseThreadInitThunk+24
7771AD1F  00000000  RtlInitializeExceptionChain+8F
7771ACEA  00000000  RtlInitializeExceptionChain+5A
========================
Local Variables And Parameters

Call stack:
Address   Frame     Function      SourceFile
014C51D4  00000000  0001:003F41D4 C:\Skyfire\SkyFire.548\Build\bin\Release\worldserver.exe

01457D32  00000000  0001:00386D32 C:\Skyfire\SkyFire.548\Build\bin\Release\worldserver.exe

0145ACB3  00000000  0001:00389CB3 C:\Skyfire\SkyFire.548\Build\bin\Release\worldserver.exe

01464C93  00000000  0001:00393C93 C:\Skyfire\SkyFire.548\Build\bin\Release\worldserver.exe

01466464  00000000  0001:00395464 C:\Skyfire\SkyFire.548\Build\bin\Release\worldserver.exe

014554EC  00000000  0001:003844EC C:\Skyfire\SkyFire.548\Build\bin\Release\worldserver.exe

014D1778  00000000  0001:00400778 C:\Skyfire\SkyFire.548\Build\bin\Release\worldserver.exe

012E1F26  00000000  0001:00210F26 C:\Skyfire\SkyFire.548\Build\bin\Release\worldserver.exe

0122942E  00000000  0001:0015842E C:\Skyfire\SkyFire.548\Build\bin\Release\worldserver.exe

012F613B  00000000  0001:0022513B C:\Skyfire\SkyFire.548\Build\bin\Release\worldserver.exe

013482DE  00000000  0001:002772DE C:\Skyfire\SkyFire.548\Build\bin\Release\worldserver.exe

62547AB3  00000000  ?invoke_i@ACE_Thread_Adapter@@EAEKXZ+93

625479EE  00000000  ?invoke@ACE_Thread_Adapter@@UAEKXZ+7E

5D77C01D  00000000  __get_tlsindex+6F

5D77C001  00000000  __get_tlsindex+53

772B7C04  00000000  BaseThreadInitThunk+24

7771AD1F  00000000  RtlInitializeExceptionChain+8F

7771ACEA  00000000  RtlInitializeExceptionChain+5A

========================
Global Variables

**Comment by thomas33** [comment]
nö

**Comment by thomas33** [comment]
compile in debug mode..

**Comment by AriDEV** [comment]
compile in debug mode pls with release crashlog we cant do much :D

**Comment by ProjectcoreDevs** [comment]
yes, compile in debug mod for post the crashlog

**Comment by oelsaid** [comment]
linux ?
