### ISSUE TITLE
Mount trouble

### ISSUE THREAD

**Issue by khasy** [ProjectSkyfire/SkyFire.548#590]
Hi, guys! I have a bug I couldn't find a fix for. When I'm mounted and I tryna' dismount by right clicking, only mount display gone, mount aura stays and i have 100% speed like im mounted. Other players are seeing the mount but I'm not. Feel free giving ideas for fixing this bug. All suggestions are welcome. I want to dismount by right clicking the mount for a second time.

Version:

SkyFireONE 2.4.3 (TBC) rev. 2013-06-28 10:28:37 -0500 (6bfebe1db1fc+) (Win32, Release)
Core version: 6
db version: ODB 0.0.4 UP1 for OregonCore rev.822
script version: ACID 2.0.4 - Full Release for Oregon Core (2.4.3 Client)

**Comment by SkyFire** [comment]
SkyFire ONE is not supported anymore.
