### ISSUE TITLE
Raid group features

### ISSUE THREAD

**Issue by azeroc** [ProjectSkyfire/SkyFire.548#591]
Raid group works only to an extent of inviting people and promoting raid-leaders, likely due to missing opcodes. Missing features:
- Move players to sub-groups.
- Promoting players to assistants.
- Giving all-assist (checkbox of top-left corner in social->raid).

Another note: if more than 5 players are invited to raid, every client in the raid will crash and continue to crash until raid group is deleted from database (probably because people don't get automatically moved to other subgroups if first one is full, but that's just my speculation).

I tried implementing handlers for those missing opcodes myself, however, I lack knowledge of reverse-engineering to find out the byte/bit pattern of the packet received from client via Ida Pro, let alone what type of server packets to send back if needed.

I was attempting to figure out pattern for moving people to sub-groups. The unknown opcode received when moving someone to subgroup is 6041 (0x1799). This is what I figured out from packet bytes:
[0] : group to move the player to (value ranges from 0 to 7)
[1] : value always is 127
[2..X] : usually expands to two bytes (if player has very low GUID) but it contains unique identifier of the subject player to move to, likely player's encrypted/jumbled GUID.

Promote to assistant (normal assist, not "Main <X>") CMSG opcode is likely 9295 (0x1897). 
Enable all assist (that checkbox I mentioned) is likely 481 (0x1E1)

There are also other unknown CMSG opcodes:
- When I switch to raid window from social: 2695 (0xA87)
- After invited to raid: 6026 (0x178A)

I hope this information is useful for fixing raid groups and my thanks.

**Comment by ProjectcoreDevs** [comment]
fixed : 
Promoting players to assistants.
Giving all-assist
