### ISSUE TITLE
CMSG_PET_RENAME packet 

### ISSUE THREAD

**Issue by Doodlezero** [ProjectSkyfire/SkyFire.548#592]
This packet CMSG_PET_RENAME doesn't work. I think that tructure is outdated.

How to reproduce that:

1. Hunter call his pet.
2. Right-Click on pet and click on option "rename"
3. Write some name there and press enter.
4. Nothing will happen.

Core revision: c4b4ea2

**Comment by GuardMoony** [comment]
WorldSession::Update ByteBufferException occured while parsing a packet (opcode: [CMSG_PET_RENAME 0xA32 (2610)]) from client xx.xx.xx.xx, accountid=9. Skipped packet. Size (12)

Error Message => [Attempted to get value with size: 12 in ByteBuffer (pos: 12 size: 1)

[0x33a408]
[0xf30d9]
[0x331e6]
[0x328bc]
[0x14c9d]
[0x42fd6e]
ACE_OS_Thread_Adapter::invoke()+0xa1 [0x0]
_get_flsindex()+0x6f [0x0]
_get_flsindex()+0x53 [0x0]
BaseThreadInitThunk()+0x12 [0x0]
RtlInitializeExceptionChain()+0x63 [0x0]
RtlInitializeExceptionChain()+0x36 [0x0]
]

**Comment by GuardMoony** [comment]
Correction seems the opcode isn't defined but the code is written in pethandler.cpp ?
