### ISSUE TITLE
MIRROR_IMAGE packet

### ISSUE THREAD

**Issue by SmythX** [ProjectSkyfire/SkyFire.548#593]
Some of MIRROR_IMAGE packets is outdated or wrong coded.

How to reproduce:

1. e.g. You are mage.
2. Try to summon mirror images.
3. You will notice that there are no images but actually they are summoned and they follow you, just they are invisible, probably because of packet structure.

Core revision: c4b4ea2

**Comment by ProjectcoreDevs** [comment]
try with 1c6627a8bf8379989e856323344a87fdb41c124c

**Comment by SmythX** [comment]
@ProjectcoreDevs, it's not fixed by 1c6627a. I tested it and it still doesn't work.

**Comment by ProjectcoreDevs** [comment]
fixed 2e945c34bf22fe05f94072fe419c84204f20c5ec

**Comment by SmythX** [comment]
@ProjectcoreDevs, not really :/ http://prntscr.com/88uon3
