### ISSUE TITLE
CHANGE RACE/FACTION packet

### ISSUE THREAD

**Issue by DoodleZero** [ProjectSkyfire/SkyFire.548#595]
Change race/faction packets doesn't work. Probably, they are not implemented yet.

Core revision: c4b4ea2

**Comment by ProjectcoreDevs** [comment]
for resolve this issue, we need the opcode smsg, if you have it, send it :) thanks

**Comment by SmythX** [comment]
I'd like to say that I have but I don't have it :(

**Comment by Ascathor** [comment]
I checked several different sources, parsers, etc.

One of the few smgs I have not found even once yet. However, trying to replicate it seems to be too much of a hassle imo...

**Comment by SkyFire** [comment]
If I have some time this weekend I will dig it out of the client.

**Comment by Rawaho** [comment]
SMSG_CHAR_FACTION_CHANGE = 0x0115

**Comment by Arcidev** [comment]
thx for opcode number, I'll try to update structure this evening (if someone else will not do it)

**Comment by SkyFire** [comment]
@Arcidev I am working all weekend. Go ahead and do it

**Comment by Arcidev** [comment]
@Rawaho are you sure about that number? Do you have a structure of that (semantics not required, syntax would be enough)?

**Comment by Rawaho** [comment]
It's a legacy packet, the structure is exactly the same.

**Comment by Arcidev** [comment]
Well, client doesn't react at all for that old structure not the success neither the error (only 1 uint8 field)

**Comment by soulfrost** [comment]
this packet contain Byte + Guid + Bit
