### ISSUE TITLE
Death Grip pull

### ISSUE THREAD

**Issue by Doodlezero** [ProjectSkyfire/SkyFire.548#596]
Death Knight's spell Death Grip pull doesn't work at all.

How to reproduce:
1. Create DK
2. Cast spell Death Grip on player or some npc
3. You will notice that your pull effect doesn't work because it won't pull your target next to you.

I think this is some packet issue, since we're using same scripts all the time (TC 3.3.5, then 4.0.6, 4.3.4, and TC 6.x.x as well) and it works there. So I guess that's packet issue. It would be nice if you can fix it.

Core revision: c4b4ea2

**Comment by Zerixx** [comment]
Do you know which packet this is?

**Comment by SmythX** [comment]
No, I don't know.
