### ISSUE TITLE
DBError at startup (lot of)

### ISSUE THREAD

**Issue by Orfeous** [ProjectSkyfire/SkyFire.548#599]
Hi!

I get a lot of error (7960 line) when start my freshly builded SkyFire emu.
here is the log: https://raw.githubusercontent.com/Orfeous/SkyFireErrors/master/DBErrors.log

I use the latest db with all updates.
Core: SkyFire 5.x.x rev. 18c4be48179b 2015-07-23 00:10:47 -0500 (master branch) (Win32, Release) (worldserver-daemon)

**Comment by alterego21** [comment]
Yeah. No shit. We are working on it.
