### ISSUE TITLE
Battlegrounds

### ISSUE THREAD

**Issue by SkyFire** [ProjectSkyfire/SkyFire.548#600]
Still need to work on battlegrounds.

**Comment by ProjectcoreDevs** [comment]
Please can you develop?

**Comment by SkyFire** [comment]
The packet structures need to be updated. Not a big deal. Just need some time.

**Comment by ProjectcoreDevs** [comment]
ok, i will work on if you want, but before i end the group opcodes

**Comment by SkyFire** [comment]
I have to leave in a few hours

**Comment by AriDEV** [comment]
No More Zerg At SkyFire !
XD

**Comment by JunkyBulgaria** [comment]
Got them fixed here, you just need to dig them out: https://github.com/JunkyBulgaria/Sky548New

**Comment by SkyFire** [comment]
BG's work. The issue was a corrupt client.
