### ISSUE TITLE
[Authentication/Login] Memory crash on login

### ISSUE THREAD

**Issue by duhow** [ProjectSkyfire/SkyFire.548#601]
Using SkyFire 5.x.x rev. 666002648680 2015-07-21 00:38:42 +0200 (master branch) (Unix, Release) (authserver)

When doing login to account (user - pass), on pressing the login button, WoW client says that I'm disconnected from server. Authserver crashes with these errors.

```
*** Error in `./authserver': free(): invalid pointer: 0x00000000013195b0 ***
Abortado
---------------------------
*** Error in `./authserver': free(): invalid pointer: 0x0000000000d665b0 ***
Abortado
```

I'm using TrinityCore 3.3.5 and SkyFire 5.4.8 on a edited DB, mixing both different columns and tables. But anyway, using Standalone SkyFire (normal Auth DB and so on...), it crashes anyway, but with other error.

```
*** Error in `./authserver': malloc(): memory corruption: 0x0000000001d113b0 ***
Abortado
```

Using a SoYouStart server with 32GB RAM. (In case it is really because of RAM).
```
             total       used       free     shared    buffers     cached
Mem:         32151      31730        420        385        389      23234
-/+ buffers/cache:       8106      24044
Swap:         6140         36       6104
```

**Comment by alterego21** [comment]
This is weird. I will try and reproduce it. It may be a day or two. I am
traveling right now.

**Comment by ProjectcoreDevs** [comment]
I think, a share any instruction executed before malloc has corrupted memory. but it's strange...

**Comment by AriDEV** [comment]
did u used a patched wow.exe for the patch 5.4.8 18414 ?

**Comment by duhow** [comment]
Nope. If I run the 3.3.5 client (as I want to use the authserver for both TrinityCore 3.3.5 and SkyFire 5.4.8) it crashes anyway.

**Comment by duhow** [comment]
Yup. Login with **3.3.5 client** crashes the authserver too.
```
*** Error in `./authserver': free(): invalid pointer: 0x00000000018ec5b0 ***
Abortado
```

**Comment by AriDEV** [comment]
the problem here is probably caused that u are trying to connect with a 5xx client to the 335 auth server or 335 client to 5xx auth server both servers are using diffrent auth packets.. thats why u cant connect. and get disconnected. make sure to use a diffrent port for each version. and also make sure to connect with the correct version to the correct auth server.

the other posibility is that skyfire is using ace and trinity is using boost.

**Comment by duhow** [comment]
**Nope**. We are talking about **SkyFire Authserver CRASH**.
Using 3.3.5 Client with SkyFire 5.4.8 Authserver: **crash**.
Using 5.4.8 Client with SkyFire 5.4.8 Authserver: **crash**.
Using 5.4.8 Client with TrinityCore 3.3.5 Authserver **with source code patched with new client list**: **works** (at least it shows realm list servers).

If I use SkyFire ONLY, **it keeps crashing**. So that about client mismatching or changing ports has nonsense.

**Comment by duhow** [comment]
Also, I'm using ACE 6.3.2 (latest build). I'm trying to compile in another machine to see if definitely it is hardware problem (RAM) or not.

**Comment by AriDEV** [comment]
no not use ace 6.3.2
skyfire is using this.
https://github.com/ProjectSkyfire/SkyFire.548/tree/master/dep/acelite
it is 6.1.4

**Comment by AriDEV** [comment]
1.) u cant run 1 authserver for both clients. the login structures are diffrent.
2.) if u modified your authserver its not a skyfire issue.
3.) skyfire supports 5.4.8 18414 .. not 335
4.) i have no crashes on connecting.

**Comment by duhow** [comment]
1.) Despite that, at least pathed TrinityCore authserver works. I haven't tested more yet.
2.) I just modified TrinityCore authserver, NOT SkyFire authserver. SkyFire is clean built. Still that, it crashes.
3.) The main idea is to use SkyFire authserver for both versions. If I need to patch it, I'll do it later. Now I'm just focusing in why is crashing. That's why I've done this report.

**Comment by AriDEV** [comment]
Post the crashlog in debug pls.

**Comment by duhow** [comment]
Where is it or how can I enable full debug mode?
