### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by deadmann** [ProjectSkyfire/SkyFire.548#603]
i know it's not a right place too ask, but the forum is dead, so, sorry :(

The wiki page says for patch 5.4.8 i should extract patch 4.0.6a... is it right? why should it even need patch 4.0.6 maps for?

Also there is no extractor, nor simple extractor, how i'm suppose to call extractor

are patch 4 and 5 playable?

**Comment by alterego21** [comment]
The forum is not dead. We are on 5.4.8 we haven't supported 406 in 2 years.
Yes it is playable.

**Comment by deadmann** [comment]
i'm reading 5XX Toturial too, but i went all step by chance and this one i the one you cant make fun of, it take days...

http://wiki.projectskyfire.org/index.php?title=Installation_Windows

**Comment by AriDEV** [comment]
skyfire is not using default accounts u need to use ".acc create" command to create your first account.

**Comment by deadmann** [comment]
what about my problem

**Comment by alterego21** [comment]
<Sarcasm> We will just put everything else on hold fix your problem for
you. </sarcasim>

**Comment by deadmann** [comment]
i didn't mean that, just this page need fix, and as long as it's like this, ... so do i really need patch 4.0.6 map for server 5.x.x? :\ and i found those things, simple extractor somewhere else on skyfire git, not within the core folder...

and this is the page i mentioned.
http://wiki.projectskyfire.org/index.php?title=Installation_Windows

**Comment by AriDEV** [comment]
for 5.4.8 u need 5.4.8 dbc and maps not 4.0.6 the extractor is in https://github.com/ProjectSkyfire/SkyFire.548/tree/master/src/tools u need to check in cmake TOOLS to compile the extractor aswell.
