### ISSUE TITLE
Crash after using french translation

### ISSUE THREAD

**Issue by firelook** [ProjectSkyfire/SkyFire.548#604]
After loading the quest local

------------------------
>> Loaded 1102 Trinity strings from table trinity_string in 3 ms
Initialize data stores...
>> Initialized 147 DBC data stores in 330 ms
Loading SpellInfo store...
>> Loaded SpellInfo store in 596 ms
Loading SpellInfo corrections...
>> Loaded SpellInfo corrections in 39 ms
Loading SkillLineAbilityMultiMap Data...
>> Loaded 8240 SkillLineAbility MultiMap Data in 2 ms
Loading SpellInfo custom attributes...
>> Loaded SpellInfo custom attributes in 206 ms
Loading GameObject models...
Loading Script Names...
>> Loaded 2390 Script Names in 116 ms
Loading Instance Template...
>> Loaded 106 instance templates in 1 ms
Loading instances...
>> Loaded instances in 3 ms
Loading Localization strings...
>> Loaded 56418 creature locale strings in 378 ms
>> Loaded 25887 gameobject locale strings in 199 ms
>> Loaded 62207 Item locale strings in 455 ms
>> Loaded 17859 Quest locale strings in 325 ms
---------------------------
=> I crash
17859 is my number of rows, I do not know what is the next table

you will find below the screenshot of the debug
![image](https://cloud.githubusercontent.com/assets/3873193/9054491/5b2f007c-3a82-11e5-9276-65fd6f100f53.png)

**Comment by ProjectcoreDevs** [comment]
After quest locale it's npc text locale

**Comment by firelook** [comment]
the problem is with locale_quest.
Do you support french accent ?

**Comment by AriDEV** [comment]
what version of mysql are u using? is your table utf8_general_ci ?

**Comment by ProjectcoreDevs** [comment]
hum... i don't have a crash ...

**Comment by AriDEV** [comment]
working on it.
