### ISSUE TITLE
MapExtractor compilation error

### ISSUE THREAD

**Issue by hypersrakser** [ProjectSkyfire/SkyFire.548#610]
Error in line 125 (loadlib.cpp):
  FileChunk* chunk = new FileChunk{ ptr, size };

  
 
 
Function:
void ChunkedFile::parseChunks()
{
    uint8* ptr = GetData();
    while (ptr < GetData() + GetDataSize())
    {
        u_map_fcc header = *(u_map_fcc*)ptr;
        uint32 size = 0;
        if (IsInterestingChunk(header))
        {
            size = *(uint32*)(ptr + 4);
            if (size <= data_size)
            {
                std::swap(header.fcc_txt[0], header.fcc_txt[3]);
                std::swap(header.fcc_txt[1], header.fcc_txt[2]);

                FileChunk* chunk = new FileChunk{ ptr, size };
                chunk->parseSubChunks();
                chunks.insert({ std::string(header.fcc_txt, 4), chunk });
            }
        }

        // move to next chunk
        ptr += size + 8;
    }
}

Output errors:
1>C:\SkyFireWow\SkyFire_5xx\src\tools\map_extractor\loadlib.cpp(125): error C2143: syntax error : missing ';' before '{'
1>C:\SkyFireWow\SkyFire_5xx\src\tools\map_extractor\loadlib.cpp(125): error C2143: syntax error : missing ';' before '}'
1>C:\SkyFireWow\SkyFire_5xx\src\tools\map_extractor\loadlib.cpp(127): error C2143: syntax error : missing ')' before '{'
1>C:\SkyFireWow\SkyFire_5xx\src\tools\map_extractor\loadlib.cpp(127): error C2661: 'std::multimap<_Kty,_Ty>::insert' : no overloaded function takes 0 arguments
1>          with
1>          [
1>              _Kty=std::string,
1>              _Ty=FileChunk *
1>          ]
1>C:\SkyFireWow\SkyFire_5xx\src\tools\map_extractor\loadlib.cpp(127): error C2143: syntax error : missing ';' before '{'
1>C:\SkyFireWow\SkyFire_5xx\src\tools\map_extractor\loadlib.cpp(127): error C2143: syntax error : missing ';' before '}'
1>C:\SkyFireWow\SkyFire_5xx\src\tools\map_extractor\loadlib.cpp(127): error C2059: syntax error : ')'
1>C:\SkyFireWow\SkyFire_5xx\src\tools\map_extractor\loadlib.cpp(168): error C2143: syntax error : missing ';' before '{'
1>C:\SkyFireWow\SkyFire_5xx\src\tools\map_extractor\loadlib.cpp(168): error C2143: syntax error : missing ';' before '}'
1>C:\SkyFireWow\SkyFire_5xx\src\tools\map_extractor\loadlib.cpp(170): error C2143: syntax error : missing ')' before '{'
1>C:\SkyFireWow\SkyFire_5xx\src\tools\map_extractor\loadlib.cpp(170): error C2661: 'std::multimap<_Kty,_Ty>::insert' : no overloaded function takes 0 arguments
1>          with
1>          [
1>              _Kty=std::string,
1>              _Ty=FileChunk *
1>          ]
1>C:\SkyFireWow\SkyFire_5xx\src\tools\map_extractor\loadlib.cpp(170): error C2143: syntax error : missing ';' before '{'
1>C:\SkyFireWow\SkyFire_5xx\src\tools\map_extractor\loadlib.cpp(170): error C2143: syntax error : missing ';' before '}'
1>C:\SkyFireWow\SkyFire_5xx\src\tools\map_extractor\loadlib.cpp(170): error C2059: syntax error : '

how can i fix it?

**Comment by alterego21** [comment]
What version of visual studio you using. Compiled fine for me.

**Comment by hypersrakser** [comment]
VisualStudio 2012

**Comment by alterego21** [comment]
The lowest supported compiler is visual studio 2013. 2012 doesn't support
all of the c++11 standard.

**Comment by hypersrakser** [comment]
cmake generate Visual C++ solutions for visual studio version that installed in your system, isn't it? Besides there is a note about VC++ 2013 on wiki page: "If you are using Visual Studio 2013, your compiler would be "Visual Studio 12" 
http://wiki.projectskyfire.org/index.php?title=Installation_(Windows_5xx)

In addition another 20 projects in solution compiled correctly. Something wrong with mapextractor.

**Comment by Natsui31** [comment]
In Requirement section :
MS Visual Studio = 12 (2013) (Windows only)

I'll also add SkyFire support only Visual Studio 2013 (12 2013 from Cmake) With Update 4.

**Comment by alterego21** [comment]
Just use the compiled version in the here.
https://github.com/ProjectSkyfire/SkyFire-Community-Tools

**Comment by rafaelrodrigosilveira** [comment]
I tried the compiled version of extrators from windows above, but don't work too. It's not work right.

**Comment by AriDEV** [comment]
https://github.com/ProjectSkyfire/SkyFire.548/commit/6685dbaca2384e08a102fe949ab40183f1ed4d4b
