### ISSUE TITLE
Divine Star

### ISSUE THREAD

**Issue by kikote300** [ProjectSkyfire/SkyFire.548#617]
Priest level 90 talent Divine Star - http://www.wowhead.com/spell=110744

This spell should shoot a star to where i'm facing, and go 24yd damaging (enemies) and healing(allies) everyone it hits, we the star reaches 24yd it should come back and do the same.
Instead it heals and damage everyone in a 24yd radius every 0.5 seconds during 15 seconds.

**Comment by SmythX** [comment]
Confirmed!
