### ISSUE TITLE
Mage Spell: Blink

### ISSUE THREAD

**Issue by Pigpriest** [ProjectSkyfire/SkyFire.548#627]
If I use this Spell the Mage don´t teleport 20 yards forward only on the same place.

Spell: http://www.wowhead.com/spell=1953/blink

**Comment by thelextor** [comment]
for me it works ...

**Comment by Arcidev** [comment]
@thelextor structure you've posted is for SMSG_MOVE_TELEPORT (0x0B39), not SMSG_MOVE_UPDATE_TELEPORT (0x15A9)

**Comment by thelextor** [comment]
ahh yeah .. :D
