### ISSUE TITLE
Crab fishin (5.4.8)

### ISSUE THREAD

**Issue by Pigpriest** [ProjectSkyfire/SkyFire.548#629]
No QuestItem loot

Quets: http://www.wowhead.com/quest=25037/crab-fishin
Item: http://www.wowhead.com/item=52080/fresh-crawler-meat

Fix:
update creature_template set lootid = 39004 WHERE entry = 39004
insert into `creature_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) values('39004','52080','-89','1','0','1','1');

**Comment by ProjectcoreDevs** [comment]
plz pull this fix in pull request not in issue ! tks

**Comment by Pigpriest** [comment]
Allright, 
I do this never, I hope I do this OK. (Sorry for Reopen)
