### ISSUE TITLE
Consort of the sea witch (5.4.8)

### ISSUE THREAD

**Issue by Pigpriest** [ProjectSkyfire/SkyFire.548#630]
No QuestItem loot

Quest: http://www.wowhead.com/quest=24625/consort-of-the-sea-witch
Item: http://www.wowhead.com/item=50018/najtess-orb-of-corruption

Fix:
update creature_template set lootid = 39072 WHERE entry = 39072
insert into `creature_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) values('39072','50018','-100','1','0','1','1');

**Comment by ProjectcoreDevs** [comment]
pull your fix in pull request plz

**Comment by Pigpriest** [comment]
Allright, 
I do this never, I hope I do this OK. (Sorry for Reopen)
