### ISSUE TITLE
Realm show offline

### ISSUE THREAD

**Issue by Ziex0** [ProjectSkyfire/SkyFire.548#633]
Anyone know bout this?
all config good.. latest DB and updated also that is localhost/127.0.0.1
but still realm show offline
http://prntscr.com/89ang8
Thanks

**Comment by Orfeous** [comment]
Same here
Rev. 2e945c34bf22fe05f94072fe419c84204f20c5ec

**Comment by ProjectcoreDevs** [comment]
it's not a bug, it's your local configuration the problem. in realmlist : 
adress : 127.0.0.1, localadress : 127.0.0.1, port 8085, gamebuild 18414 !
if you have this verify your configuration file your port, adress and realmID = 1 !

**Comment by Orfeous** [comment]
@ProjectcoreDevs  thank you for the reply.
I use the correct configuration in database and config files also.
It worked before, nothing really changed but the core.

I dont really know what is the problem.

**Comment by Ziex0** [comment]
Here are detail i posted
http://www.projectskyfire.org/index.php?/topic/10352-realm-show-offline/

**Comment by SkyFire** [comment]
I can't reproduce your issue. I could be your client version. It needs to be a raw client only patched with the skyfire patcher. It can not be from some random private server. Also we will not link one to you is is against the rules.

**Comment by Ziex0** [comment]
Nvm then... like i said i use all SF thing.. i will test again..Ty

**Comment by cooler-SAI** [comment]
all good for me
