### ISSUE TITLE
Table 'characters.arena_team' doesn't exist

### ISSUE THREAD

**Issue by beleavschi-ladela** [ProjectSkyfire/SkyFire.548#634]
How to fix error?
Help please

**Comment by ProjectcoreDevs** [comment]
update or re-apply the character database it's on this database

**Comment by beleavschi-ladela** [comment]
no table 'arena_team' in latest characters.sql

**Comment by ProjectcoreDevs** [comment]
CREATE TABLE IF NOT EXISTS `arena_team` (
  `arenaTeamId` int(10) unsigned NOT NULL DEFAULT '0',
  `name` varchar(24) NOT NULL,
  `captainGuid` int(10) unsigned NOT NULL DEFAULT '0',
  `type` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `rating` smallint(5) unsigned NOT NULL DEFAULT '0',
  `seasonGames` smallint(5) unsigned NOT NULL DEFAULT '0',
  `seasonWins` smallint(5) unsigned NOT NULL DEFAULT '0',
  `weekGames` smallint(5) unsigned NOT NULL DEFAULT '0',
  `weekWins` smallint(5) unsigned NOT NULL DEFAULT '0',
  `rank` int(10) unsigned NOT NULL DEFAULT '0',
  `backgroundColor` int(10) unsigned NOT NULL DEFAULT '0',
  `emblemStyle` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `emblemColor` int(10) unsigned NOT NULL DEFAULT '0',
  `borderStyle` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `borderColor` int(10) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`arenaTeamId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

**Comment by ProjectcoreDevs** [comment]
apply this

**Comment by beleavschi-ladela** [comment]
thanks
but still error
Table 'characters.arena_team_member' doesn't exist

**Comment by ProjectcoreDevs** [comment]
rewrite your characters database with : 
https://github.com/ProjectSkyfire/SkyFire.548/blob/master/sql/base/characters_database.sql

**Comment by beleavschi-ladela** [comment]
thanks
