### ISSUE TITLE
or portal does not quest 5.4.8

### ISSUE THREAD

**Issue by oelsaid** [ProjectSkyfire/SkyFire.548#641]
Bug: or portal does not quest
Emulador: Skyfire 5.4.8
System: Ubuntu 14.04
Print: http://i.imgur.com/HVMnwrF.jpg

**Comment by ProjectcoreDevs** [comment]
pandaren zone is on dev ... patient... :p

**Comment by AriDEV** [comment]
what should i understand under this, 1.) portal not working, 2.) portal working and it should give a quest, 3.) portal is working but quest dosnt work, 4.) portal not working quest so quest dont update, 5.) portal not working quest works, 6.) portal not working thats why the quest is not working.
