### ISSUE TITLE
Resurrect spells

### ISSUE THREAD

**Issue by shocky4** [ProjectSkyfire/SkyFire.548#642]
Resurrection spells not working. Due to missing packet SMSG_RESURRECTION_REQUEST.

**Comment by ProjectcoreDevs** [comment]
035e7ef4c61b4fafa6d63315dc8cbcfe40b5740a

**Comment by shocky4** [comment]
Tested it, even though both CMSG and SMSG resurrection opcodes are there, the dead player doesn't receive the 'accept/decline' notification, it just stays at 'resurrect spirit'

**Comment by ProjectcoreDevs** [comment]
ok i will work on
