### ISSUE TITLE
SQL Update - creature_loot_template

### ISSUE THREAD

**Issue by Atis6** [ProjectSkyfire/SkyFire.548#643]
Hi!
When i'm updating the last 2 fix to creature_loot_template, i got this message: 
[Err] 1136 - Column count doesn't match value count at row 1

DB - Release 12
rev. :https://github.com/ProjectSkyfire/SkyFire.548/commit/035e7ef4c61b4fafa6d63315dc8cbcfe40b5740a

**Comment by ProjectcoreDevs** [comment]
7d633c162691afdeacb851e514cf8150ff914391
