### ISSUE TITLE
Worldserver crash

### ISSUE THREAD

**Issue by Atis6** [ProjectSkyfire/SkyFire.548#646]
Hi!
When the worldserver is loading, and this row when it wrotes this : "Race 1 Class 1 Level 1 does not have stats data!" and it stops working. (It's the row line in DBErrors.log)
Server.log's last row: "Loading Player Create Level Stats Data..."

But i've datas in that table! There is the picture.
OS: Win10
MYSQL: 5.6
DB: release 12 + all updates
Rev: https://github.com/ProjectSkyfire/SkyFire.548/commit/7d633c162691afdeacb851e514cf8150ff914391

After that I've rebuilded the core as Release (not Debug), and It's worked :)

![db](https://cloud.githubusercontent.com/assets/7590936/9693760/2942c46a-5353-11e5-9c53-ebeb31e58a1d.PNG)

**Comment by ProjectcoreDevs** [comment]
hum... you have one ligne in this table?

**Comment by Atis6** [comment]
nope, a lot of.

**Comment by ProjectcoreDevs** [comment]
it's only in debug mod?

**Comment by Atis6** [comment]
Yes, in Release mode works good.

**Comment by ProjectcoreDevs** [comment]
i don't have any error with debug mod loading... try with the last database and last core, all clean

**Comment by AriDEV** [comment]
can u share the crashlog in debug ?

**Comment by Myst** [comment]
Please, check your config, I'm not able to reproduce this error.
