### ISSUE TITLE
Auth opcode

### ISSUE THREAD

**Issue by Atis6** [ProjectSkyfire/SkyFire.548#647]
Hi!
After auth with the account i got this message in worldserver:

![opcode](https://cloud.githubusercontent.com/assets/7590936/9699466/94324a2a-53e4-11e5-994b-b08b3a4503b8.PNG)

**Comment by ProjectcoreDevs** [comment]
it's cmsg_realm_split

**Comment by WoWShards** [comment]
just one question this issue is since 5 Sep open, Is it now bugged or not?

**Comment by SkyFire** [comment]
We don't use the term bugged around here it's not politically correct. Try F.U.B.A.R instead.

**Comment by AriDEV** [comment]
fucked up beyond all recognition
