### ISSUE TITLE
second realm login error

### ISSUE THREAD

**Issue by cavaclub** [ProjectSkyfire/SkyFire.548#651]
WHen i create a second realm and try to login on it stops on connected and the SF console i receive this message but it dont seems to crash...

SF>SkyFire 5.x.x rev. 4daf674c6a49 2015-09-16 23:44:50 +0200 (master branch) (Unix, Release) (worldserver-daemon) ready...
SF>Unable to retrieve class or race data.

**Comment by alterego21** [comment]
I'm not by my laptop. Look in the account table. The realm needs to be
added to 2 tables.  Realm_classes and realm_races.

**Comment by cavaclub** [comment]
i got it thank you! when you reply i was changing that for test, and works greate.
