### ISSUE TITLE
Goldshire <gryphon master>

### ISSUE THREAD

**Issue by cavaclub** [ProjectSkyfire/SkyFire.548#652]
SkyFire 5.x.x rev. 07ebba257b75 2015-09-17 12:05:47 +0200 (master branch) (Unix, Release)

![wowscrnshot_091815_162542](https://cloud.githubusercontent.com/assets/2026665/9963686/607d630a-5e24-11e5-9966-d77d2e96045a.jpg)

I have all flypaths active, but i can get any fly window...
the same happens in Kharanos, Gol'Bolar Quarry...

**Comment by Cronicman** [comment]
They don't have the flightpaths implemented yet since they came from Cataclysm.

**Comment by cavaclub** [comment]
@Cronicman but i can fly to there
