### ISSUE TITLE
no breath bar

### ISSUE THREAD

**Issue by cavaclub** [ProjectSkyfire/SkyFire.548#654]
SkyFire 5.x.x rev. 07ebba257b75 2015-09-17 12:05:47 +0200 (master branch) (Unix, Release)

When underwater i can't see breath bar, but still can die normally...

**Comment by AriDEV** [comment]
in configs look line 806 and try to set it correctly as u need, it is disabled by default.
if the issue no longer persist feel free to close the comment.

´´´DisableWaterBreath = ´´´

**Comment by cavaclub** [comment]
#
#    DisableWaterBreath
#        Description: Required security level for water breathing.
#        Default:     4  - (Disabled)
#                     0  - (Enabled, Everyone)
#                     1  - (Enabled, Mods/GMs/Admins)
#                     2  - (Enabled, GMs/Admins)
#                     3  - (Enabled, Admins)

DisableWaterBreath = 4

mine is like above... and i said that i can die, so i supose that is working the timer but don't appear on screen.
