### ISSUE TITLE
Mapextractor Issue

### ISSUE THREAD

**Issue by Shoxxo** [ProjectSkyfire/SkyFire.548#656]
Today i was come back to test the mainfixxes but the extractors are same as last year...

Extract TheBattleforGilneas (163/288)
No such file World\Maps\TheBattleforGilneas\TheBattleforGilneas.wdt

Possible maps will not be founded in the latest client !

**Comment by SkyFire** [comment]
I don't have this issue. You may not have all the data.

**Comment by Xunil1337** [comment]
Can you Upload a complete client for one time on mega or else uploaders ?

**Comment by Reck1501** [comment]
You can find clients on the website of most private servers

**Comment by Xunil1337** [comment]
Only will accepting full game client like 30Gigs ... no 65mb client and no torrent sdhit they all missing datas

**Comment by SkyFire** [comment]
No one will upload or link a client for you here without getting banned!

**Comment by rafaelrodrigosilveira** [comment]
Please, upload only the torrent from the complete client 5.4.8, that not fail in the extraction. Put this in the how to Wiki. Thanks.

**Comment by SkyFire** [comment]
We can't link to downloads of any kind. Google it.
