### ISSUE TITLE
Worldserver crash when speak with this npc

### ISSUE THREAD

**Issue by UnAfraid** [ProjectSkyfire/SkyFire.548#658]
When i attempt to speak with this npc and server crashes
![wowscrnshot_100315_181420](https://cloud.githubusercontent.com/assets/2185291/10268518/292012fc-6ac4-11e5-950e-171750b6a38e.jpg)

Error message:
```
*** stack smashing detected ***: ./worldserver terminated
Aborted (core dumped)
```

I am running the last revision of master branch on ubuntu 14.04

**Comment by AriDEV** [comment]
can u send a crashlog in debug mode ?

**Comment by UnAfraid** [comment]
How do i start server in debug mode?

**Comment by alterego21** [comment]
Compile the server in debug. If you're on windows it's easy.

**Comment by UnAfraid** [comment]
As i said i am on linux, Ubuntu 14.04

**Comment by alterego21** [comment]
Ubuntu isn't a true os. :) look in our wiki. There is debug information on
that. I can't tell you where because I am not at a computer right now.

**Comment by UnAfraid** [comment]
I am recompiling with "-DWITH_COREDEBUG" flags i hope that's what i need.
If Ubuntu server isn't true OS then what is?

**Comment by UnAfraid** [comment]
When i compiled it with this flag server didn't even finished loading it simply stopped like there was some exit function called, no error nothing.
Last thing console printed was:
Loading Player Create Level Stats Data...

**Comment by Atis6** [comment]
That was the problem at me too.
https://github.com/ProjectSkyfire/SkyFire.548/issues/646

**Comment by WoWShards** [comment]
and they said they couldnt reproduce :dancer:

**Comment by SkyFire** [comment]
Think I found the issue. Will dig into it after I finish grilling my steak.

**Comment by WoWShards** [comment]
14 days later.. I think you should look after your steak ^^

**Comment by Arcidev** [comment]
@Atis6 can I close 646 too? To me it doesnt look like as the same problem

**Comment by Atis6** [comment]
I think yes.
