### ISSUE TITLE
Cannot connect to world database

### ISSUE THREAD

**Issue by Reck1501** [ProjectSkyfire/SkyFire.548#659]
My worldserver.exe keeps returning the error "Cannot connect to world database localhost;3306;root;;world"

Yet my authserver connects just fine to the database

**Comment by alterego21** [comment]
You need to setup your confidence for the world server. Look at the error
message.

**Comment by Reck1501** [comment]
I don't follow. The error message is there, sure, but the host, port, username, whatever.. is correct

**Comment by SkyFire** [comment]
Your missing the password for your world server or else the world table is non extant.

**Comment by Reck1501** [comment]
I've added a password to the user, and changed it in the world config, yet the error is still there.
The world database is also there http://i.imgur.com/I0ge7fi.png

**Comment by AriDEV** [comment]
worldserver.conf -> LINE 96-98, u need a database for auth for world and for characters to set make sure to use 127.0.0.1 instead of localhost

**Comment by SkyFire** [comment]
PEBKAC
