### ISSUE TITLE
CMake Warning

### ISSUE THREAD

**Issue by Xunil1337** [ProjectSkyfire/SkyFire.548#660]
Detected 32-bit platform
Using supplied MySQL sources
MSVC: Enabled large address awareness
MSVC: Enabled SSE2 support
MSVC: Overloaded standard names
MSVC: Disabled NON-SECURE warnings
MSVC: Disabled POSIX warnings
MSVC: Disabled generic compiletime warnings
Found OpenSSL library: optimized;C:/OpenSSL-Win32/lib/VC/ssleay32MD.lib;C:/OpenSSL-Win32/lib/VC/libeay32MD.lib;debug;C:/OpenSSL-Win32/lib/VC/ssleay32MDd.lib;C:/OpenSSL-Win32/lib/VC/libeay32MDd.lib
Found OpenSSL headers: C:/OpenSSL-Win32/include
Found git binary : C:/Program Files (x86)/Git/cmd/git.exe

* SkyFire revision   : 43ae73892f6f 2015-10-03 18:04:23 -0500 (master branch)

* Install core to        : C:/Program Files (x86)/Project_Skyfire

* Build world/auth       : Yes (default)
* Build with scripts     : Yes (default)
* Build map/vmap tools   : Yes
* Build core w/PCH       : Yes (default)
* Build scripts w/PCH    : Yes (default)
* Show compile-warnings  : No  (default)
* Use coreside debug     : No  (default)
* Use MySQL sourcetree   : Yes (default)
* Use GIT revision hash  : Yes

-- MySQL 5.5.9
SCRIPT PREPARATIONS
  -> Prepared: Spells
  -> Prepared: Commands
  -> Prepared: Examples
  -> Prepared: Custom
  -> Prepared: World
  -> Prepared: Outdoor PVP Zones
  -> Prepared: Eastern Kingdoms
  -> Prepared: Kalimdor
  -> Prepared: Outland
  -> Prepared: Northrend
  -> Prepared: The Maelstrom
  -> Prepared: Events
  -> Prepared: Pandaria
  -> Prepared: Pet
SCRIPT PREPARATION COMPLETE

Configuring done
CMake Warning (dev) in dep/mysqllite/CMakeLists.txt:
  Policy CMP0043 is not set: Ignore COMPILE_DEFINITIONS_<Config> properties.
  Run "cmake --help-policy CMP0043" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in dep/mysqllite/CMakeLists.txt:
  Policy CMP0043 is not set: Ignore COMPILE_DEFINITIONS_<Config> properties.
  Run "cmake --help-policy CMP0043" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in dep/mysqllite/CMakeLists.txt:
  Policy CMP0043 is not set: Ignore COMPILE_DEFINITIONS_<Config> properties.
  Run "cmake --help-policy CMP0043" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in dep/mysqllite/CMakeLists.txt:
  Policy CMP0043 is not set: Ignore COMPILE_DEFINITIONS_<Config> properties.
  Run "cmake --help-policy CMP0043" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

Generating done

**Comment by SkyFire** [comment]
It's just a warning. Because not everything is c++11 compliant yet. Just ignore it for now.
