### ISSUE TITLE
[CORE] TicketMgr error compile

### ISSUE THREAD

**Issue by WoWShards** [ProjectSkyfire/SkyFire.548#663]
Hi, since the last Rev 8b503c1d1abc411b75e0fddf8585164809a5e4f4

I get errors on compile:

---

/src/server/game/Tickets/TicketMgr.h:79:14: error: explicit specialization in non-namespace scope 'class TicketMgr'
     template<> uint32 GetOpenTicketCount<GmTicket>() const { return _openGmTicketCount; }
              ^
compilation terminated due to -Wfatal-errors.

**Comment by SkyFire** [comment]
Did you do a clean build?

**Comment by WoWShards** [comment]
yes

**Comment by SkyFire** [comment]
I'm building right now. Checking it out

**Comment by WoWShards** [comment]
I tried it again with a clean build, still same issue :(

**Comment by WoWShards** [comment]
would be nice if you could fix this, I want to start off fix some DB related stuff but I need to get Ingame for that :)

**Comment by DrEhsan** [comment]
https://github.com/ProjectSkyfire/SkyFire.548/commit/e0504c894244862dc2c3c953a788b8aef2110589
