### ISSUE TITLE
[CORE] Realm show up as offline

### ISSUE THREAD

**Issue by WoWShards** [ProjectSkyfire/SkyFire.548#664]
Rev: e0504c894244862dc2c3c953a788b8aef2110589

Thanks again for the compile error fix, apparently next issue show up.
He is telling me now that the realm is offline, I already tried use realmlist "+:8085" both versions dont work, I already tried Skyfire Connection Patcher but he kick instant out everytime. I saw already 2 tickets where some people had this problem too. Any Suggestions?

**Comment by SkyFire** [comment]
Seems only a select few have this issue. It's not a client patch issue.
Try adding this to your config.wtf
SET realmlist "localhost"
SET patchlist "localhost"
It needs to match your server exactly.

If the wow client has already been patched it will error out.

**Comment by WoWShards** [comment]
Sorry Sire, Im not a newbie, Im using already in realmlsit the exactly IP like my rootserver.
So the problem must be somewhere else.

**Comment by DrEhsan** [comment]
@WoWShards we dont have that problem check if your gamebuild matches with your launcher in realmlist table. both should be same , for example boths should be 18414 or 18291

**Comment by WoWShards** [comment]
Please I really dont know what is wrong I took some pictures, and uploaded my config files, please check. I guess there is really nothing wrong there.

game version: http://prntscr.com/8yzrpn
realmstatus: http://prntscr.com/8yzs3t
authserver.conf: http://pastebin.com/rsJb7yUH
worldserver.conf: http://pastebin.com/PHJkU8Zw

**Comment by alterego21** [comment]
Try and change your worldserver port to 8086 once. Check your firewall too.

**Comment by WoWShards** [comment]
@alterego21 sorry but i try nothing more, 8085 is default. So If it would be a problem with firewall, I should had this problem with other cores too. But I dont.

**Comment by Myst** [comment]
Hello, this usually happen because ports are not open or you are not using a correct patched wow.exe
