### ISSUE TITLE
Help with SMSG_LOOT_LIST

### ISSUE THREAD

**Issue by Undergarun** [ProjectSkyfire/SkyFire.548#665]
In void Group::SendLooter(...)

uknown guid of SMSG_LOOT_LIST is masterLooterGuid, Can anybody help me with the WriteBitSeq of masterLooterGuid ? The code is the following:

    WorldPacket data(SMSG_LOOT_LIST);

    data.WriteBitSeq<4, 5, 2, 3, 7>(creatureGuid);
    data.WriteBit(groupLooterGuid != 0);

    if (groupLooterGuid)
        data.WriteBitSeq<5, 1, 3, 0, 7, 6, 2, 4>(groupLooterGuid);

    data.WriteBit(masterLooterGuid != 0);
    data.WriteBitSeq<1, 6, 0>(creatureGuid);

    if (masterLooterGuid)
    {
        // Unknown WriteBitSeq HELP ME HERE PLEASE!!
    }

    if (groupLooterGuid)
        data.WriteByteSeq<3, 2, 7, 0, 5, 1, 6, 4>(groupLooterGuid);

    data.WriteByteSeq<0, 2, 5, 4, 3, 1, 6, 7>(creatureGuid);

    BroadcastPacket(&data, false);

**Comment by Arcidev** [comment]
This should be SMSG_LOOT_LIST (I have it from my parser)... If you know what is what of those unk values you could post it back, one of them is groupLooter, second one masterGroupLooter :)

var guid48 = new byte[8];
var guid16 = new byte[8];
guid48[5] = packet.ReadBit();
var unk24 = packet.ReadBit("unk24"); // 24
if (unk24)
    guid16 = packet.StartBitStream(4, 6, 0, 7, 5, 2, 3, 1);
guid48[1] = packet.ReadBit();
var unk40 = packet.ReadBit("unk40"); // 40
guid48[4] = packet.ReadBit();
guid48[3] = packet.ReadBit();
guid48[2] = packet.ReadBit();
var guid32 = new byte[8];
if (unk40)
    guid32 = packet.StartBitStream(2, 3, 4, 5, 6, 0, 1, 7);
guid48[7] = packet.ReadBit();
guid48[0] = packet.ReadBit();
guid48[6] = packet.ReadBit();
if (unk40)
{
    packet.ParseBitStream(guid32, 7, 1, 0, 6, 5, 3, 4, 2);
    packet.WriteGuid("guid32", guid32);
}
if (unk24)
{
    packet.ParseBitStream(guid16, 4, 5, 6, 3, 2, 7, 0, 1);
    packet.WriteGuid("guid16", guid16);
}
packet.ParseBitStream(guid48, 5, 1, 6, 2, 3, 0, 7, 4);
