### ISSUE TITLE
Working dungeons and raids

### ISSUE THREAD

**Issue by sanek20142** [ProjectSkyfire/SkyFire.548#670]
Can you give a rough list of workers ' instow and raids,Thanks for the reply

**Comment by sanek20142** [comment]
Install*

**Comment by sanek20142** [comment]
Dungeons***

**Comment by alterego21** [comment]
Test it yourself.

**Comment by sanek20142** [comment]
And where should I write unemployed mobs and bosses,here?

**Comment by SkyFire** [comment]
No send them to the welfare line. There is no free lunch at SkyFire. Missing bosses and scripts are not bugs. They are just not added features. We don't need a list we already have one. However if you wish to be useful start scripting and make some pull requests.

**Comment by sanek20142** [comment]
So all the bosses are scripted already ?And in the siege of Orgrimmar ? There the teleport does not work after like 4 boss to Scorpion
