### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by sanek20142** [ProjectSkyfire/SkyFire.548#671]
Where can I get the extractors which you have that would make dbc vmaps,maps?
And how much you work ability ?

**Comment by rafaelrodrigosilveira** [comment]
The extrators in this project do not work. I have say about this, but the project management peoples do not help. Them say that is could`t be linked here. I'll exit this emu from this.

**Comment by Ascathor** [comment]
Potentially every 5.4.8 extractor should work here.
Also, I had no issues with the extractors from this core. I can not find your problem with it.

What exactly is the problem ?

**Comment by sanek20142** [comment]
The efficiency of the talents and the spells what ?

**Comment by soulfrost** [comment]
@sanek20142 
![default](https://cloud.githubusercontent.com/assets/2207154/11860874/bc47ad24-a48a-11e5-985d-3314ffcc522d.jpg)

**Comment by sanek20142** [comment]
The efficiency of the talents and the spells what ?
Pls Answer the question!

**Comment by sanek20142** [comment]
The efficiency of the talents and the spells *
Pls Answer the question

**Comment by soulfrost** [comment]
100%

**Comment by sanek20142** [comment]
Thx

**Comment by AriDEV** [comment]
Not an Issue for Questions and Help support use the forum.

**Comment by Ascathor** [comment]
Not an actual extractor issue...
