### ISSUE TITLE
Transport DBC files

### ISSUE THREAD

**Issue by Pnemonic** [ProjectSkyfire/SkyFire.548#677]
Hi all, I just compiled a fresh core and downloaded version 12 DB from projectskyfire website. Problem I am having is that none of the transports work. The GM commands make you teleport, but instances transport, portals and flightmasters don't work. I noticed when compiling the DBC files that there were errors involving transport. Any ideas? Otherwise the server works perfectly.

**Comment by SkyFire** [comment]
It's on our list.

**Comment by Pnemonic** [comment]
Ok upon further testing, I found the following flightpaths faulty: 
Orgrimmer to Crossroads: Message "you are moving"
Orgrimmer to Nozzlepot's outpost: Message "you are moving"

Instances still unavailable.
I will list faulty and working portals and see if you can come up with a fix for the faulty ones. I think it might be missing "spell_target_position" values.

Faulty Portals are:
Dalaran Portal to Stormwind (190960)


The only portals that I find working is: 
Portal to Blasted Lands
Portal to Shattrath Portal to Isle of Quel'Danas
Portal to the Purple Parlor
Portal to the Violet Citadel
Dalaran Portal To Caverns of time


Will update as I go along.

**Comment by SkyFire** [comment]
Some of the non working portals are DB issues. Not that hard to fix. Just need to find the sniff data for them.

**Comment by SkyFire** [comment]
Transports are working. Need separate issue for any non working portals.
