### ISSUE TITLE
(.reload quest_template) make the all of quests bug

### ISSUE THREAD

**Issue by AlirezaAbsolut** [ProjectSkyfire/SkyFire.548#684]
when you edit a some details in database>>world>>quest_template  and back to game and use the .reload quest_template command all of quests change and become autocomplete!!!!!

**Comment by SkyFire** [comment]
I will check it out

**Comment by SkyFire** [comment]
Confirmed.

**Comment by AriDEV** [comment]
after using .reload quest_template the server pops quests as errors cause of bad/missing special flag. the other issue is after u use .reload quest_template u are unable to get credits to objectives

**Comment by AriDEV** [comment]
https://github.com/ProjectSkyfire/SkyFire.548/commit/1f9d783eeb1fec6aaf64c690b667bc228adbe5d7
