### ISSUE TITLE
Segmentation Fault on Command Input.

### ISSUE THREAD

**Issue by Anddrw** [ProjectSkyfire/SkyFire.548#705]
Hi, whenever I try to input a command into the worldserver's console, the core exits with the "Segmentation Fault" error!

Im currently experiencing this problem on a fresh build, from the latest source.

> Platform: Ubuntu 15.10 (GNU/Linux 4.2.0-16-generic x86_64)
> Server Ram: 3 GB
> Server Cores: 4

**Scenario:** After the worldserver loads, when i try to execute an account command for example, the core receives Segmentation Fault!
Example: .account add test test

gdb output:

(http://pastebin.com/eHL4ruQH)

Kind regards,

Andrew!

**Comment by Arcidev** [comment]
I've just made a clean install (after OS reinstallation) and I get no error... Only "There is no such subcommand". Do you have all db updates and have you built the latest version of master branch?

Btw the command is ".account create test test"

**Comment by Anddrw** [comment]
Yes, i've compiled the latest branch and i've applied all database updates. Still getting this error.

**Comment by SkyFire** [comment]
Your backtrace is not of any use. Need to compile in debug so I can get the full output.
