### ISSUE TITLE
Monk SpellScript issue

### ISSUE THREAD

**Issue by Anddrw** [ProjectSkyfire/SkyFire.548#707]
I've managed to fix and compile the monk spells script, i've added all the spells in the spell_script_name table, i've also loaded the spells in ScriptLoader, yet there is no different ingame skill  behaviour. I've never worked with TC source before but i have a good C++ knowledge, so i raise this question to you: **How do you exactly manage to link the SpellScript to the game?**

I've followed these steps:

- Uncommented the spell_monk.cpp from CMakeLists.txt
- Fixed and compiled spell_monk.cpp
- Added void AddSC_monk_spell_scripts() in ScriptLoader.cpp
- Added script name definitions in the spell_script_name

**Comment by Arcidev** [comment]
Have you also added AddSC_monk_spell_scripts into AddSpellScripts method in ScriptLoader?

**Comment by Anddrw** [comment]
@Arcidev , yes.

**Comment by SkyFire** [comment]
Closing this. It's not a bug. General questions should be asked in the forum.
