### ISSUE TITLE
vmap4extractor CMake error:unrecognized command -std=c++11 

### ISSUE THREAD

**Issue by angelsss** [ProjectSkyfire/SkyFire.548#709]
--Cmake Error Info: ---------
Scanning dependencies of target vmap4extractor
[ 24%] Building CXX object src/tools/vmap4_extractor/CMakeFiles/vmap4extractor.dir/vmapexport.cpp.o
[ 24%] cc1plus: error: unrecognized command line option "-std=c++11"
make[2]: **\* [src/tools/vmap4_extractor/CMakeFiles/vmap4extractor.dir/vmapexport.cpp.o] Error 1
make[1]: **\* [src/tools/vmap4_extractor/CMakeFiles/vmap4extractor.dir/all] Error 2
make[1]: **\* Waiting for unfinished jobs....
[ 24%] Building CXX object src/tools/map_extractor/CMakeFiles/mapextractor.dir/System.cpp.o
Building CXX object src/tools/map_extractor/CMakeFiles/mapextractor.dir/dbcfile.cpp.o
cc1plus: error: unrecognized command line option "-std=c++11"
make[2]: **\* [src/tools/map_extractor/CMakeFiles/mapextractor.dir/dbcfile.cpp.o] Error 1
make[2]: **\* Waiting for unfinished jobs....
cc1plus: error: unrecognized command line option "-std=c++11"
make[2]: **\* [src/tools/map_extractor/CMakeFiles/mapextractor.dir/System.cpp.o] Error 1
make[1]: **\* [src/tools/map_extractor/CMakeFiles/mapextractor.dir/all] Error 2
[ 24%] Built target generate_ScriptPCH.cpp
make: **\* [all] Error 2

=====remark
1: gcc and gcc+ : 4.4.7 --Red Hat 4.4.7-16  ; ProjectSkyfire --now master 
2: I had use gcc/gcc+ 4.8 --issues still

**Comment by angelsss** [comment]
resolve by myself： upgrade gcc version to 4.7+  with src make at https://gcc.gnu.org 
but appear another issue: not find Map.dbc  (set PATH not resolve) 
use strace to find follow detail error:
--------strace error------
Loading common MPQ files
Extracting maps...
Read Map.dbc file... Done! (288 maps loaded)
Read AreaTable.dbc file...Done! (3991 areas loaded)
Read LiquidType.dbc file...Done! (61 LiqTypes loaded)
Convert map files
Extract Azeroth (1/288)
-default not use strace error----------------------------------
[root@localhost wow]# ./mapextracto
Using locale: zhCN
Loading common MPQ files
Extracting maps...
Read Map.dbc file... Fatal error: Cannot find Map.dbc in archive!
[root@localhost wow]# find . -name Map.dbc    
./dbc/enCN/Map.dbc
./dbc/Map.dbc
./WOW-MAPS/dbc/enCN/Map.dbc
./WOW-MAPS/dbc/Map.dbc
------------------------------

**Comment by angelsss** [comment]
add: strace error: 
--------strace error------
Loading common MPQ files
Extracting maps...
Read Map.dbc file... Done! (288 maps loaded)
Read AreaTable.dbc file...Done! (3991 areas loaded)
Read LiquidType.dbc file...Done! (61 LiqTypes loaded)
Convert map files
Extract Azeroth (1/288)
**No such file World\Maps\Azeroth\Azeroth.wdt**

**Comment by SkyFire** [comment]
It can't find the map data in the DBC.Make sure your data is complete. The base data you get when you first install the client is not good.

**Comment by AriDEV** [comment]
Using locale: zhCN
./dbc/enCN/Map.dbc

is dat an english chinese version or wut ? the first time i hear about enCN

**Comment by Shoxxo** [comment]
Make sure your wow folder is like : C:/WoW_Client/ and not C:/WoW Client Freespaces/

Most of them will result in an error :/
