### ISSUE TITLE
Spells/Raids/Item

### ISSUE THREAD

**Issue by dutywar** [ProjectSkyfire/SkyFire.548#711]
i have few questions
1. How i can enable no raid group MUST to go into Raid
2. How i fix items that his procs is to much?
3. How i start to script a spell from start?

**Comment by SkyFire** [comment]
Questions are reserved for the forum. http:www.projectskyfire.org Not the bug tracker

**Comment by dutywar** [comment]
true i tried there no one answer..

**Comment by SkyFire** [comment]
Could it be that no one has an answer?

**Comment by dutywar** [comment]
everything there is answer , forum just empty
