### ISSUE TITLE
VmapExport build error

### ISSUE THREAD

**Issue by gonzo1247** [ProjectSkyfire/SkyFire.548#714]
when i will compile with tools, i become this error:

/home/mop/SkyFireEMU/src/tools/vmap3_extractor/vmapexport.cpp: In function â€˜int main(int, char**)â€™:
/home/mop/SkyFireEMU/src/tools/vmap3_extractor/vmapexport.cpp:502:21: error: too few arguments to function â€˜int mkdir(const char*, __mode_t)â€™

**Comment by SkyFire** [comment]
What version of Linux?

**Comment by gonzo1247** [comment]
Ubuntu 14.04.2 is the version of linux

**Comment by SkyFire** [comment]
Every push is tested and built with Ubuntu. I will try and reproduce this on my local.

**Comment by Shoxxo** [comment]
vmap3_extractor = Outdated, will check it.

**Comment by Shoxxo** [comment]
Tested with Windows 10 Build x64

ScottTest
Transport
Old Systems not used can be ignored these errors.

But it worked!
