### ISSUE TITLE
DBC Enums Dungeons / Raid Wrong

### ISSUE THREAD

**Issue by Shoxxo** [ProjectSkyfire/SkyFire.548#716]
https://github.com/ProjectSkyfire/SkyFire.548/blob/master/src/server/game/DataStores/DBCEnums.h#L326

It is wrong. Here a example:

![Diff Example From DBC File](http://image.prntscr.com/image/58b40f510b264253a83bb6f94b8d4a1b.png)

Should be fixxed....

Fixxed?

- [x] No
- [ ] Yes

**Comment by Ulduar** [comment]
Flex start from 10 people initially like 10-Normal, but may to scale up to 25 people.
But if flex raid enter group having for example 8 people, for them and will be of 10.

**Comment by Shoxxo** [comment]
Let me please do my job mate :) I write on the source longer as 1 year and i played from vanilla on live server :D

**Comment by AriDEV** [comment]
in Mist of Pandaria Flex is 14 in dbc and 10 dosnt exist. 13 is scenario heroic 5man there is no scenario 25 .)

**Comment by AriDEV** [comment]
1 NORMAL
2 HEROIC
3 10 NORMAL
4 25 NORMAL
5 10 HEROIC
6 25 HEROIC
7 25 LFR
8 5 CHALLENGE
9 40 MAN (ALTERAC)
10 Dosn't exist 
11 3 Scenario NORMAL
12 5 Scenario HEROIC
13 Dosn't exist
14 10-25 FLEX
