### ISSUE TITLE
Fix for raging blow proc and charges

### ISSUE THREAD

**Issue by cybrann** [ProjectSkyfire/SkyFire.548#718]
Fix for charges from raging blow:

class spell_warr_raging_blow : public SpellScriptLoader
{
	public:
		spell_warr_raging_blow() : SpellScriptLoader("spell_warr_raging_blow") { }

		class spell_warr_raging_blow_SpellScript : public SpellScript
		{
			PrepareSpellScript(spell_warr_raging_blow_SpellScript);

			bool Validate(SpellInfo const* /*spellEntry*/)
			{
				if (!sSpellMgr->GetSpellInfo(WARRIOR_SPELL_RAGING_BLOW))
					return false;
				return true;
			}

			void HandleOnHit()
			{
				if (Player* _player = GetCaster()->ToPlayer())
				{
					if (_player->HasAura(WARRIOR_SPELL_ALLOW_RAGING_BLOW))
					{
						if (_player->GetAura(WARRIOR_SPELL_ALLOW_RAGING_BLOW))
						{
							int32 stacks = _player->GetAura(WARRIOR_SPELL_ALLOW_RAGING_BLOW)->GetStackAmount();

							if (stacks <= 1)
							{
								_player->RemoveAura(WARRIOR_SPELL_ALLOW_RAGING_BLOW);
							}
							else
							{
								_player->GetAura(WARRIOR_SPELL_ALLOW_RAGING_BLOW)->SetStackAmount(stacks - 1);
							}
						}
					}
				}
			}

			void Register()
			{
				OnHit += SpellHitFn(spell_warr_raging_blow_SpellScript::HandleOnHit);
			}
		};

		SpellScript* GetSpellScript() const
		{
			return new spell_warr_raging_blow_SpellScript();
		}
};

Fix for activating raging blow:

class spell_warr_raging_blow_proc : public SpellScriptLoader
{
    public:
		spell_warr_raging_blow_proc() : SpellScriptLoader("spell_warr_raging_blow_proc") { }

		class spell_warr_raging_blow_proc_SpellScript : public SpellScript
        {
			PrepareSpellScript(spell_warr_raging_blow_proc_SpellScript);

            void HandleOnHit()
            {
                if (Player* _player = GetCaster()->ToPlayer())
                    if (_player->GetSpecializationId(_player->GetActiveSpec()) == CHAR_SPECIALIZATION_WARRIOR_FURY && _player->getLevel() >= 30)
                        _player->CastSpell(_player, WARRIOR_SPELL_ALLOW_RAGING_BLOW, true);
            }

            void Register()
            {
				OnHit += SpellHitFn(spell_warr_raging_blow_proc_SpellScript::HandleOnHit);
            }
        };

        SpellScript* GetSpellScript() const
        {
			return new spell_warr_raging_blow_proc_SpellScript();
        }
};

**Comment by DrEhsan** [comment]
why are you opening an issue instead of PR?

**Comment by cybrann** [comment]
I'm just too lazy to do that. If someone wants he/she can add it.

**Comment by SkyFire** [comment]
It's hard to open a pull request on a copy/paste submission.

**Comment by DrEhsan** [comment]
@cybrann you should create pull request so devs can test your code and if everything is fine they can merge it in to core.

it is useless like this...

i see no sql stuff for the spell :|

**Comment by cybrann** [comment]
Here sql core

INSERT INTO `spell_script_names` VALUES (85288, 'spell_warr_raging_blow')
INSERT INTO `spell_script_names` VALUES (12880, 'spell_warr_raging_blow_proc')

**Comment by Shoxxo** [comment]
https://github.com/ProjectSkyfire/SkyFire.548/pull/742/commits/7103854ca2567bd4b91a45637d736e9723ec818c
