### ISSUE TITLE
Enchanting not working

### ISSUE THREAD

**Issue by cybrann** [ProjectSkyfire/SkyFire.548#734]
Whenever we try to enchant an item we get error: Tried to enchant an item that didn't exist.

**Comment by AriDEV** [comment]
can u give more details about what item u tryed to disenchant/enchant ?
is it only enchanting of new enchantments, or are the old enchantments also not working properly,
did u tryed to enchant/disenchant new items or are the old also not enchant/disenchant properly ?

**Comment by cybrann** [comment]
Whenever I try to use any enchant to enchant any item it gives error: Tried to enchant an item that didn't exist.

Just try enchanting any item

**Comment by Shoxxo** [comment]
Submit a debug log please.

**Comment by cybrann** [comment]
There is no debug log for this. Try enchanting any item in game, and it will show you message Tried to enchant an item that didn't exist.

**Comment by Shoxxo** [comment]
Compile it please in debug with rel info, and debug the server, i have atm not the full client here with any files, so i am not able to check, but i will do it today!

**Comment by cybrann** [comment]
I don't have time bro

**Comment by Shoxxo** [comment]
Okay, you tell us an error, but you don't have time do make a debug log. Hmm. okay.

**Comment by Shoxxo** [comment]
Some updates, or i can close this?

**Comment by Myst** [comment]
Try to check the spell related.

**Comment by Shoxxo** [comment]
i'll check some code later if skyfire and me had completed a new framework that we need .. still i let it open.

**Comment by AriDEV** [comment]
Fixed: https://github.com/ProjectSkyfire/SkyFire.548/commit/bdea2a0d237abaa0e502d7071094d24dba0d9c51
