### ISSUE TITLE
Unknown opcodes I have received

### ISSUE THREAD

**Issue by RAlexis** [ProjectSkyfire/SkyFire.548#738]
http://pastebin.com/fYkG684D

Probably some requests, because their length is 0. Only one of the opcodes has the length 4. Also take a look at the last opcode, it's SMSG_MISSILE_CANCEL on SkyFire, but it's a CMSG actually, so it's wrong on SkyFire I guess?
In case anyone has any info regarding these, that would be nice :)

**Comment by SkyFire** [comment]
It is possible to have the same opcode value for both CMSG and SMSG. The last opcode is correct.

**Comment by RAlexis** [comment]
Oh, okay then. Thanks for the clarification.
