### ISSUE TITLE
Macro Saving

### ISSUE THREAD

**Issue by smoldar** [ProjectSkyfire/SkyFire.548#741]
Client not saving macros.
Tested 5 versions of Wow, added full permissions on all files in folder wow, tried start wow as admin and nothing. Macros saved but when relog, macros not loaded back on action bars, i think that this is problem of save macros into database.

**Comment by SkyFire** [comment]
Confirmed. Will look at it. Thanks

**Comment by smoldar** [comment]
At first i thinked aboud problem of Ru version, but i tested enGB versions too and still same problem, macros are saved on client side, but not in DB
Same problem is when create new character, char dont see his chat in chat window until he use /resetchat after it is ok.

**Comment by Rawaho** [comment]
The chat and macro problem are account data related

**Comment by Shoxxo** [comment]
Marcos not saved in player database, only in clientfiles.

Close?!

**Comment by smoldar** [comment]
Macros are saved on client side, but not saved on action bars. And this is based on server-side.

**Comment by Shoxxo** [comment]
```quote
Prevented sending disabled opcode [UNKNOWN OPCODE 0x279 (633)] to [Player: Developement (Guid: 1, Account: 1)]
No defined handler for opcode [UNKNOWN OPCODE 0x1124 (4388)] sent by [Player: Developement (Guid: 1, Account: 1)]
No defined handler for opcode [UNKNOWN OPCODE 0x1F34 (7988)] sent by [Player: Developement (Guid: 1, Account: 1)]
Spell action 1 not added into button 11 for player Developement (GUID: 1): player don't known this spell
```

Seems an missing Opcode Packet Handler! It comes after creating a Macro and place it to the Button bar!
