### ISSUE TITLE
CMake Problem

### ISSUE THREAD

**Issue by Anvirion** [ProjectSkyfire/SkyFire.548#749]
I got a lot of Problems here, while configurate the source with CMake

I have installed following programs on my Ubuntu 16.04:
`apt-cache search libreadline
libreadline-dev - GNU readline and history libraries, development files
libreadline-gplv2-dev - GNU readline and history libraries, development files
libreadline5 - GNU readline and history libraries, run-time libraries
libreadline5-dbg - GNU readline and history libraries, debugging libraries
libreadline6 - GNU readline and history libraries, run-time libraries
libreadline6-dbg - GNU readline and history libraries, debugging libraries
libreadline6-dev - GNU readline and history libraries, development files
cupt - flexible package manager -- console interface
libreadline-java - GNU readline and BSD editline wrappers for Java
libreadline-java-doc - API docs for readline/editline wrappers for Java
`

All needed other Programs are installed, so as described in the Wiki.
http://wiki.projectskyfire.org/index.php?title=Installation_(Linux_5xx)

Programs from TC compiling are installed too:

[CMakeError.txt](https://github.com/ProjectSkyfire/SkyFire.548/files/625970/CMakeError.txt)

**Comment by SkyFire** [comment]
Every push is tested on Ubuntu
https://travis-ci.org/ProjectSkyfire/SkyFire.548/jobs/175538910

**Comment by Anvirion** [comment]
I have all done so its descriped there but that Errors are allready there

**Comment by AriDEV** [comment]
https://github.com/ProjectSkyfire/SkyFire.548/commit/aafb59dad22359138a980eece8a13aeb48680572

**Comment by Anvirion** [comment]
Thank you AriDEV
