### ISSUE TITLE
CMAKE Readline library not found! UBUNTU 16.04

### ISSUE THREAD

**Issue by Cubansephiroth** [ProjectSkyfire/SkyFire.548#751]
After following wiki step by step i got an error when run cmake

The CXX compiler identification is unknown
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detected 64-bit platform
-- UNIX: Using jemalloc
-- UNIX: Using default configuration directory
-- UNIX: Using default library directory
-- UNIX: Configuring uninstall target
-- UNIX: Created uninstall target
-- UNIX: Detected compiler: /usr/bin/cc
-- Found ACE library: /usr/local/lib/libACE.so
-- Found ACE headers: /usr/local/include
-- Found OpenSSL library: /usr/local/lib/libssl.so;/usr/local/lib/libcrypto.so
-- Found OpenSSL headers: /usr/local/include
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Using mysql-config: /usr/bin/mysql_config
-- Found MySQL library: /usr/lib/x86_64-linux-gnu/libmysqlclient.so
-- Found MySQL headers: /usr/include/mysql
**CMake Error at cmake/macros/FindReadline.cmake:27 (MESSAGE):
  **** Readline library not found!****

after that some help message
Your distro may provide a binary for Readline e.g.  for ubuntu try
  apt-get install libreadline5-dev

So i tried..

 apt-get install libreadline5-dev

Reading state information... Done
Package libreadline5-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libreadline-gplv2-dev:i386 libreadline-gplv2-dev

And then i tried
 apt-get install libreadline-gplv2-dev (Installed fine)

but when i run cmake again still no readline library found...

Any help here?

Thanks..

**Comment by SkyFire** [comment]
Restart your server and run cmake again. It may be a cache issue

**Comment by Cubansephiroth** [comment]
Same errors after restart :(

**Comment by Cubansephiroth** [comment]
Compiled fine in Ubuntu 14.04.5.. Close...
