### ISSUE TITLE
Error while CMake configures

### ISSUE THREAD

**Issue by Anvirion** [ProjectSkyfire/SkyFire.548#755]
I got a error while CMake configures.

1. OpenSSL is installed but detected anymore
2. Readline libary installed in Version "libreadline6-dev"

Errorlog:
`-- Detected 64-bit platform
-- UNIX: Using jemalloc
-- UNIX: Using default configuration directory
-- UNIX: Using default library directory
-- UNIX: Configuring uninstall target
-- UNIX: Created uninstall target
-- UNIX: Detected compiler: /usr/bin/cc
-- Found OpenSSL library: OPENSSL_SSL_LIBRARIES-NOTFOUND;OPENSSL_CRYPTO_LIBRARIES-NOTFOUND
-- Found OpenSSL headers: /usr/include
-- Using mysql-config: /usr/bin/mysql_config
-- Found MySQL library: /usr/lib/x86_64-linux-gnu/libmysqlclient.so
-- Found MySQL headers: /usr/include/mysql
CMake Error at cmake/macros/FindReadline.cmake:28 (MESSAGE):
  ** Readline library not found!

  ** Your distro may provide a binary for Readline e.g.  for ubuntu try
  apt-get install libreadline5-dev
Call Stack (most recent call first):
  CMakeLists.txt:68 (find_package)

-- Configuring incomplete, errors occurred!
See also "/root/SkyFire.548/build/CMakeFiles/CMakeOutput.log".
See also "/root/SkyFire.548/build/CMakeFiles/CMakeError.log".
`
Operating System: Ubuntu 16.04

My Question: How do i fix this errors?

Note: "libreadline5-dev" not longer available for Ubuntu 12.04 or higher , please update to libreadline6-dev

`sudo apt-get install libreadline5-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package libreadline5-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  lib64readline-gplv2-dev:i386 libreadline-gplv2-dev:i386 libreadline-gplv2-dev

E: Package 'libreadline5-dev' has no installation candidate
`

**Comment by AriDEV** [comment]
sudo apt-get install libreadline6-dev

**Comment by Anvirion** [comment]
libreadline6-dev ist allready installed but i got the same error

**Comment by AriDEV** [comment]
Did u tryed to reinstall cmake ?

**Comment by Anvirion** [comment]
Ubuntu fresh install but doesnt work!

**Comment by SkyFire** [comment]
Eww. Ubuntu. Debian ftw. I will try it on my VM. Give me a bit.

**Comment by AriDEV** [comment]
use the comand: 
`which gcc`
it should output your path where gcc is installed.
Example: /usr/bin/gcc
after u know where you have your gcc. u will need to set the CC and CXX to the path.
It is basic linux knowledge maybe u should consider of changing to windows.

**Comment by AriDEV** [comment]
Can u provide a fresh CmakeOutput.log ?

**Comment by SkyFire** [comment]
I was able to reproduce the issue on my virtual machine. Looks like they changed the file path for readline libraries. I will make a work around for this. I need to get a few hours of sleep first.

**Comment by Anvirion** [comment]
SkyFire what is the current standing?

**Comment by alterego21** [comment]
For now compile
https://github.com/ProjectSkyfire/SkyFire.548/commit/93c637c93128b9d2c631274568aa6d469f042553
or below. Until I can have some time to troubleshoot it.
Just checkout 93c637c93128b9d2c631274568aa6d469f042553

**Comment by Anvirion** [comment]
is this dead now??

I have allready the problem with the libreadline libaries

**Comment by SkyFire** [comment]
Why does everyone assume we are dead? Some of us have a real life family or a demanding job. Oh wait let me drop my life and fix your problem. We are volunteers and are under obligation fix things on demand. It gets fixed when it gets fixed!

**Comment by AriDEV** [comment]
@Anvirion 7 days back i asked u to provide your CmakeOutput.log.
Translation to German: Vor 7 Tagen habe ich dich gebeten deinen CmakeOutput.log zur Verfügung zu stellen.

**Comment by SkyFire** [comment]
Scheiße und furz

**Comment by Anvirion** [comment]
@AriDEV 

`apt-get install libreadline6-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libreadline6-dev : Depends: libreadline6 (= 6.3-8ubuntu2) but 6.3-8ubuntu8 is to be installed
E: Unable to correct problems, you have held broken packages.
`
[CMakeOutput.txt](https://github.com/ProjectSkyfire/SkyFire.548/files/853147/CMakeOutput.txt)

**Comment by AriDEV** [comment]
OK first things first ^^

The following packages have unmet dependencies:
libreadline6-dev : Depends: libreadline6 (= 6.3-8ubuntu2) but 6.3-8ubuntu8 is to be installed
E: Unable to correct problems, you have held broken packages.

Tells us that u have installed 6.3-8ubuntu8 instead 6.3-8ubuntu2.

6.3-8ubuntu8  (active development) Zesty
6.3-8ubuntu8  (current stable release) Yakkety (16.10)
6.3-8ubuntu2  (supported) Xenial (16.04)

You wrote in this issue your Operating System is: Ubuntu 16.04
Ubuntu 16.04LTS is Xenial Dist.

To find out your Dist. use
`$ lsb_release -a`

If your Dist is Xenial u will need to uninstall libreadlines and reinstall the correct ones that are for your dist.

NOTE: Im sure your Dist is Yakkety and not Xenial ^^

**Comment by Anvirion** [comment]
`lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial
`

`apt-get remove libreadline6
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages will be REMOVED:
  apparmor apt apt-utils dh-python gnupg libboost-all-dev
  libboost-mpi-python-dev libboost-mpi-python1.58-dev
  libboost-mpi-python1.58.0 libboost-python-dev libboost-python1.58-dev
  libpython-dev libpython-stdlib libpython2.7 libpython2.7-dev
  libpython2.7-stdlib libpython3-stdlib libpython3.5-stdlib libreadline6
  lsb-release mysql-server mysql-server-5.7 python python-apt
  python-apt-common python-dev python-pycurl python-software-properties
  python2.7 python2.7-dev python3 python3-apt python3-dbus python3-gi
  python3-pycurl python3-software-properties python3.5
  software-properties-common unattended-upgrades
WARNING: The following essential packages will be removed.
This should NOT be done unless you know exactly what you are doing!
  apt gnupg (due to apt)
0 upgraded, 0 newly installed, 39 to remove and 0 not upgraded.
After this operation, 130 MB disk space will be freed.
You are about to do something potentially harmful.
To continue type in the phrase 'Yes, do as I say!'
 ?]
`

uninstall is no good idea

Btw: OS is freshly installed

**Comment by AriDEV** [comment]
rizon.net
#project_skyfire

**Comment by alterego21** [comment]
Switch operating systems. Ubuntu is temperamental. Try Debian. It's 10 X
better than Ubuntu.

**Comment by AriDEV** [comment]
@alterego21 it have nothing to do with the system more with the one behind it. travis compile without issues on 16.04

**Comment by Anvirion** [comment]
Fix is here:  https://github.com/ProjectSkyfire/SkyFire.548/issues/756

Thanks to @knuxyl
