### ISSUE TITLE
Incompatible with Ubuntu (fix here)

### ISSUE THREAD

**Issue by knuxyl** [ProjectSkyfire/SkyFire.548#756]
This project seems to have been developed on a Debian platform because it does not work with Ubuntu without some tweaks to your system. I don't know anything about how to edit the project library directories but it seems it is looking for libraries in the wrong place. I have fixed this with some simple commands (needs to be 64-bit Ubuntu (any flavor))

sudo ln -s /lib/x86_64-linux-gnu/libreadline.so.5 /usr/lib/libreadline.so
sudo ln -s /lib/x86_64-linux-gnu/libz.so.1.2.8 /usr/lib/libz.so
sudo ln -s /lib/x86_64-linux-gnu/libbz2.so.1.0 /usr/lib/libbz2.so
sudo ln -s /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 /usr/lib/libcrypto.so
sudo ln -s /lib/x86_64-linux-gnu/libssl.so.1.0.0 /usr/lib/libssl.so

This will create the symlinks nessacery for
libreadline
zlib
bzip
openssl crypto

I managed to get Cmake to run without errors on Xubuntu 16.04.2 LTS x86_64

Make fails with this though...
[ 23%] Linking CXX static library libstorm.a
[ 23%] Built target storm
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by knuxyl** [comment]
Seems this libreadline5 error can be fixed with this command. I looked through the libreadline5-dev debian package and found a symlink and searched my pc for libreadline

sudo ln -s /lib/x86_64-linux-gnu/libreadline.so.5 /usr/lib/libreadline.so

I don't know where libreadline.so.5 came from, all the libreadline-dev packages are not installed.

**Comment by AriDEV** [comment]
https://launchpad.net/~george-edison55/+archive/ubuntu/cmake-3.x

**Comment by AriDEV** [comment]
what is your cmake version ?

**Comment by knuxyl** [comment]
cmake --version
cmake version 3.5.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).

**Comment by AriDEV** [comment]
URL: rizon.net/chat
CHANNEL: #project_skyfire

**Comment by Anvirion** [comment]
Thank you!

**Comment by knuxyl** [comment]
All incompatibility was fixed recently. A standard cmake ../, make runs just fine, even cmake ../ -DtOOLS=1

**Comment by Shoxxo** [comment]
http://wiki.projectskyfire.org/index.php?title=Installation_(Linux)
