### ISSUE TITLE
[mapextractor]

### ISSUE THREAD

**Issue by knuxyl** [ProjectSkyfire/SkyFire.548#758]
The Windows version and the Linux (built on my machine) does not extract map files. I don't know what is causing this.

knuxyl@lapras:~/Games/Mists of Pandaria$ ./mapextractor 
Map & DBC Extractor
===================

Loading enUS locale MPQs
Loaded ./Data/wow-update-base-16016.MPQ
Loaded ./Data/wow-update-base-16048.MPQ
Loaded ./Data/wow-update-base-16057.MPQ
Loaded ./Data/wow-update-base-16309.MPQ
Loaded ./Data/wow-update-base-16357.MPQ
Loaded ./Data/wow-update-base-16516.MPQ
Loaded ./Data/wow-update-base-16650.MPQ
Loaded ./Data/wow-update-base-16844.MPQ
Loaded ./Data/wow-update-base-16965.MPQ
Loaded ./Data/wow-update-base-17116.MPQ
Loaded ./Data/wow-update-base-17266.MPQ
Loaded ./Data/wow-update-base-17325.MPQ
Loaded ./Data/wow-update-base-17345.MPQ
Loaded ./Data/wow-update-base-17538.MPQ
Loaded ./Data/wow-update-base-17645.MPQ
Loaded ./Data/wow-update-base-17688.MPQ
Loaded ./Data/wow-update-base-17898.MPQ
Loaded ./Data/wow-update-base-18273.MPQ
Loaded ./Data/enUS/wow-update-enUS-16016.MPQ
Loaded ./Data/enUS/wow-update-enUS-16048.MPQ
Loaded ./Data/enUS/wow-update-enUS-16057.MPQ
Loaded ./Data/enUS/wow-update-enUS-16309.MPQ
Loaded ./Data/enUS/wow-update-enUS-16357.MPQ
Loaded ./Data/enUS/wow-update-enUS-16516.MPQ
Loaded ./Data/enUS/wow-update-enUS-16650.MPQ
Loaded ./Data/enUS/wow-update-enUS-16844.MPQ
Loaded ./Data/enUS/wow-update-enUS-16965.MPQ
Loaded ./Data/enUS/wow-update-enUS-17116.MPQ
Loaded ./Data/enUS/wow-update-enUS-17266.MPQ
Loaded ./Data/enUS/wow-update-enUS-17325.MPQ
Loaded ./Data/enUS/wow-update-enUS-17345.MPQ
Loaded ./Data/enUS/wow-update-enUS-17538.MPQ
Loaded ./Data/enUS/wow-update-enUS-17645.MPQ
Loaded ./Data/enUS/wow-update-enUS-17688.MPQ
Loaded ./Data/enUS/wow-update-enUS-17898.MPQ
Loaded ./Data/enUS/wow-update-enUS-18273.MPQ
Loaded ./Data/Cache/patch-base-16016.MPQ
Loaded ./Data/Cache/patch-base-16048.MPQ
Loaded ./Data/Cache/patch-base-16057.MPQ
Loaded ./Data/Cache/patch-base-16309.MPQ
Loaded ./Data/Cache/patch-base-16357.MPQ
Loaded ./Data/Cache/patch-base-16516.MPQ
Loaded ./Data/Cache/patch-base-16650.MPQ
Loaded ./Data/Cache/patch-base-16844.MPQ
Loaded ./Data/Cache/patch-base-16965.MPQ
Loaded ./Data/Cache/patch-base-17116.MPQ
Loaded ./Data/Cache/patch-base-17266.MPQ
Loaded ./Data/Cache/patch-base-17325.MPQ
Loaded ./Data/Cache/patch-base-17345.MPQ
Loaded ./Data/Cache/patch-base-17538.MPQ
Loaded ./Data/Cache/patch-base-17645.MPQ
Loaded ./Data/Cache/patch-base-17688.MPQ
Loaded ./Data/Cache/patch-base-17898.MPQ
Loaded ./Data/Cache/patch-base-18273.MPQ
Loaded ./Data/Cache/enUS/patch-enUS-16016.MPQ
Loaded ./Data/Cache/enUS/patch-enUS-16048.MPQ
Loaded ./Data/Cache/enUS/patch-enUS-16057.MPQ
Loaded ./Data/Cache/enUS/patch-enUS-16309.MPQ
Loaded ./Data/Cache/enUS/patch-enUS-16357.MPQ
Loaded ./Data/Cache/enUS/patch-enUS-16516.MPQ
Loaded ./Data/Cache/enUS/patch-enUS-16650.MPQ
Loaded ./Data/Cache/enUS/patch-enUS-16844.MPQ
Loaded ./Data/Cache/enUS/patch-enUS-16965.MPQ
Loaded ./Data/Cache/enUS/patch-enUS-17116.MPQ
Loaded ./Data/Cache/enUS/patch-enUS-17266.MPQ
Loaded ./Data/Cache/enUS/patch-enUS-17325.MPQ
Loaded ./Data/Cache/enUS/patch-enUS-17345.MPQ
Loaded ./Data/Cache/enUS/patch-enUS-17538.MPQ
Loaded ./Data/Cache/enUS/patch-enUS-17645.MPQ
Loaded ./Data/Cache/enUS/patch-enUS-17688.MPQ
Loaded ./Data/Cache/enUS/patch-enUS-17898.MPQ
Loaded ./Data/Cache/enUS/patch-enUS-18273.MPQ

Detected locale: enUS
Detected client build 18273 for locale enUS

Extracting dbc files...
Extracted 393 DBC files

Extracting db2 files...
Extracted 58 DB2 files

Using locale: enUS

Loading enUS locale MPQs
Loaded ./Data/wow-update-base-16016.MPQ
Loaded ./Data/wow-update-base-16048.MPQ
Loaded ./Data/wow-update-base-16057.MPQ
Loaded ./Data/wow-update-base-16309.MPQ
Loaded ./Data/wow-update-base-16357.MPQ
Loaded ./Data/wow-update-base-16516.MPQ
Loaded ./Data/wow-update-base-16650.MPQ
Loaded ./Data/wow-update-base-16844.MPQ
Loaded ./Data/wow-update-base-16965.MPQ
Loaded ./Data/wow-update-base-17116.MPQ
Loaded ./Data/wow-update-base-17266.MPQ
Loaded ./Data/wow-update-base-17325.MPQ
Loaded ./Data/wow-update-base-17345.MPQ
Loaded ./Data/wow-update-base-17538.MPQ
Loaded ./Data/wow-update-base-17645.MPQ
Loaded ./Data/wow-update-base-17688.MPQ
Loaded ./Data/wow-update-base-17898.MPQ
Loaded ./Data/wow-update-base-18273.MPQ
Loaded ./Data/enUS/wow-update-enUS-16016.MPQ
Loaded ./Data/enUS/wow-update-enUS-16048.MPQ
Loaded ./Data/enUS/wow-update-enUS-16057.MPQ
Loaded ./Data/enUS/wow-update-enUS-16309.MPQ
Loaded ./Data/enUS/wow-update-enUS-16357.MPQ
Loaded ./Data/enUS/wow-update-enUS-16516.MPQ
Loaded ./Data/enUS/wow-update-enUS-16650.MPQ
Loaded ./Data/enUS/wow-update-enUS-16844.MPQ
Loaded ./Data/enUS/wow-update-enUS-16965.MPQ
Loaded ./Data/enUS/wow-update-enUS-17116.MPQ
Loaded ./Data/enUS/wow-update-enUS-17266.MPQ
Loaded ./Data/enUS/wow-update-enUS-17325.MPQ
Loaded ./Data/enUS/wow-update-enUS-17345.MPQ
Loaded ./Data/enUS/wow-update-enUS-17538.MPQ
Loaded ./Data/enUS/wow-update-enUS-17645.MPQ
Loaded ./Data/enUS/wow-update-enUS-17688.MPQ
Loaded ./Data/enUS/wow-update-enUS-17898.MPQ
Loaded ./Data/enUS/wow-update-enUS-18273.MPQ
Loaded ./Data/Cache/patch-base-16016.MPQ
Loaded ./Data/Cache/patch-base-16048.MPQ
Loaded ./Data/Cache/patch-base-16057.MPQ
Loaded ./Data/Cache/patch-base-16309.MPQ
Loaded ./Data/Cache/patch-base-16357.MPQ
Loaded ./Data/Cache/patch-base-16516.MPQ
Loaded ./Data/Cache/patch-base-16650.MPQ
Loaded ./Data/Cache/patch-base-16844.MPQ
Loaded ./Data/Cache/patch-base-16965.MPQ
Loaded ./Data/Cache/patch-base-17116.MPQ
Loaded ./Data/Cache/patch-base-17266.MPQ
Loaded ./Data/Cache/patch-base-17325.MPQ
Loaded ./Data/Cache/patch-base-17345.MPQ
Loaded ./Data/Cache/patch-base-17538.MPQ
Loaded ./Data/Cache/patch-base-17645.MPQ
Loaded ./Data/Cache/patch-base-17688.MPQ
Loaded ./Data/Cache/patch-base-17898.MPQ
Loaded ./Data/Cache/patch-base-18273.MPQ
Loaded ./Data/Cache/enUS/patch-enUS-16016.MPQ
Loaded ./Data/Cache/enUS/patch-enUS-16048.MPQ
Loaded ./Data/Cache/enUS/patch-enUS-16057.MPQ
Loaded ./Data/Cache/enUS/patch-enUS-16309.MPQ
Loaded ./Data/Cache/enUS/patch-enUS-16357.MPQ
Loaded ./Data/Cache/enUS/patch-enUS-16516.MPQ
Loaded ./Data/Cache/enUS/patch-enUS-16650.MPQ
Loaded ./Data/Cache/enUS/patch-enUS-16844.MPQ
Loaded ./Data/Cache/enUS/patch-enUS-16965.MPQ
Loaded ./Data/Cache/enUS/patch-enUS-17116.MPQ
Loaded ./Data/Cache/enUS/patch-enUS-17266.MPQ
Loaded ./Data/Cache/enUS/patch-enUS-17325.MPQ
Loaded ./Data/Cache/enUS/patch-enUS-17345.MPQ
Loaded ./Data/Cache/enUS/patch-enUS-17538.MPQ
Loaded ./Data/Cache/enUS/patch-enUS-17645.MPQ
Loaded ./Data/Cache/enUS/patch-enUS-17688.MPQ
Loaded ./Data/Cache/enUS/patch-enUS-17898.MPQ
Loaded ./Data/Cache/enUS/patch-enUS-18273.MPQ

Loading common MPQ files
Loaded ./Data/world.MPQ
Loaded ./Data/misc.MPQ
Loaded ./Data/expansion1.MPQ
Loaded ./Data/expansion2.MPQ
Loaded ./Data/expansion3.MPQ
Loaded ./Data/expansion4.MPQ
Loaded ./Data/wow-update-base-16016.MPQ
Loaded ./Data/wow-update-base-16048.MPQ
Loaded ./Data/wow-update-base-16057.MPQ
Loaded ./Data/wow-update-base-16309.MPQ
Loaded ./Data/wow-update-base-16357.MPQ
Loaded ./Data/wow-update-base-16516.MPQ
Loaded ./Data/wow-update-base-16650.MPQ
Loaded ./Data/wow-update-base-16844.MPQ
Loaded ./Data/wow-update-base-16965.MPQ
Loaded ./Data/wow-update-base-17116.MPQ
Loaded ./Data/wow-update-base-17266.MPQ
Loaded ./Data/wow-update-base-17325.MPQ
Loaded ./Data/wow-update-base-17345.MPQ
Loaded ./Data/wow-update-base-17538.MPQ
Loaded ./Data/wow-update-base-17645.MPQ
Loaded ./Data/wow-update-base-17688.MPQ
Loaded ./Data/wow-update-base-17898.MPQ
Loaded ./Data/wow-update-base-18273.MPQ
Loaded ./Data/Cache/patch-base-16016.MPQ
Loaded ./Data/Cache/patch-base-16048.MPQ
Loaded ./Data/Cache/patch-base-16057.MPQ
Loaded ./Data/Cache/patch-base-16309.MPQ
Loaded ./Data/Cache/patch-base-16357.MPQ
Loaded ./Data/Cache/patch-base-16516.MPQ
Loaded ./Data/Cache/patch-base-16650.MPQ
Loaded ./Data/Cache/patch-base-16844.MPQ
Loaded ./Data/Cache/patch-base-16965.MPQ
Loaded ./Data/Cache/patch-base-17116.MPQ
Loaded ./Data/Cache/patch-base-17266.MPQ
Loaded ./Data/Cache/patch-base-17325.MPQ
Loaded ./Data/Cache/patch-base-17345.MPQ
Loaded ./Data/Cache/patch-base-17538.MPQ
Loaded ./Data/Cache/patch-base-17645.MPQ
Loaded ./Data/Cache/patch-base-17688.MPQ
Loaded ./Data/Cache/patch-base-17898.MPQ
Loaded ./Data/Cache/patch-base-18273.MPQ

Extracting maps...
Read Map.dbc file... Done! (288 maps loaded)
Read AreaTable.dbc file...Done! (3991 areas loaded)
Read LiquidType.dbc file...Done! (61 LiqTypes loaded)
Convert map files
Extract Azeroth (1/288)                  
Error loading World\Maps\Azeroth\Azeroth_28_28.adt
Error loading World\Maps\Azeroth\Azeroth_31_47.adt
Error loading World\Maps\Azeroth\Azeroth_30_48.adt
Error loading World\Maps\Azeroth\Azeroth_32_55.adt
Extract Kalimdor (2/288)                  
Error loading World\Maps\Kalimdor\Kalimdor_29_12.adt
Segmentation fault (core dumped)
knuxyl@lapras:~/Games/Mists of Pandaria$

**Comment by SkyFire** [comment]
You need to compile the tools in debug. I need a copy of the stack trace put in a pastebin. Segmentation faults need a stack tracke

**Comment by Shoxxo** [comment]
I know this issue, it is the wrong client

**Comment by knuxyl** [comment]
The client is 5.4.8 but what I'm thinking is that it might not be the full client. Do you know where to get the full client?

**Comment by Shoxxo** [comment]
No sry.
