### ISSUE TITLE
Unknown Opcodes reached by Pandaren Monk

### ISSUE THREAD

**Issue by Shoxxo** [ProjectSkyfire/SkyFire.548#763]
**Description:**

More unknown opcodes found!

```quote
No defined handler for opcode [CMSG_REALM_SPLIT 0x18B2 (6322)] sent by [Player: <none> (Guid: 0, Account: 1)]
Race (24) has wrong teamid (42) in DBC: wrong DBC files?
Race (24) has wrong teamid (42) in DBC: wrong DBC files?
No defined handler for opcode [CMSG_REALM_SPLIT 0x18B2 (6322)] sent by [Player: <none> (Guid: 0, Account: 1)]
No defined handler for opcode [UNKNOWN OPCODE 0x1A87 (6791)] sent by [Player: <none> (Guid: 0, Account: 1)]
No defined handler for opcode [CMSG_DB_QUERY_BULK 0x158D (5517)] sent by [Player: <none> (Guid: 0, Account: 1)]
Race (24) has wrong teamid (42) in DBC: wrong DBC files?
Race (24) has wrong teamid (42) in DBC: wrong DBC files?
WaypointMovementGenerator::LoadPath: creature Instructor Mossthorn (Entry: 57754 GUID: 604148 DB GUID: 604148) doesn't have waypoint path id: 0
No defined handler for opcode [UNKNOWN OPCODE 0x6F5 (1781)] sent by [Player: Brewmaster (Guid: 1, Account: 1)]
No defined handler for opcode [CMSG_LEARN_PREVIEW_TALENTS_PET 0x77B (1915)] sent by [Player: Brewmaster (Guid: 1, Account: 1)]
No defined handler for opcode [UNKNOWN OPCODE 0x1F9E (8094)] sent by [Player: Brewmaster (Guid: 1, Account: 1)]
No defined handler for opcode [UNKNOWN OPCODE 0x44E (1102)] sent by [Player: Brewmaster (Guid: 1, Account: 1)]
No defined handler for opcode [UNKNOWN OPCODE 0x365 (869)] sent by [Player: Brewmaster (Guid: 1, Account: 1)]
No defined handler for opcode [UNKNOWN OPCODE 0x32D (813)] sent by [Player: Brewmaster (Guid: 1, Account: 1)]
No defined handler for opcode [CMSG_LFG_LOCK_INFO_REQUEST 0x6B (107)] sent by [Player: Brewmaster (Guid: 1, Account: 1)]
No defined handler for opcode [UNKNOWN OPCODE 0x813 (2067)] sent by [Player: Brewmaster (Guid: 1, Account: 1)]
No defined handler for opcode [UNKNOWN OPCODE 0xA23 (2595)] sent by [Player: Brewmaster (Guid: 1, Account: 1)]
No defined handler for opcode [UNKNOWN OPCODE 0xA87 (2695)] sent by [Player: Brewmaster (Guid: 1, Account: 1)]
No defined handler for opcode [CMSG_VOICE_SESSION_ENABLE 0x15A9 (5545)] sent by [Player: Brewmaster (Guid: 1, Account: 1)]
No defined handler for opcode [CMSG_GUILD_SET_ACHIEVEMENT_TRACKING 0xCF0 (3312)] sent by [Player: Brewmaster (Guid: 1, Account: 1)]
No defined handler for opcode [UNKNOWN OPCODE 0x1203 (4611)] sent by [Player: Brewmaster (Guid: 1, Account: 1)]
No defined handler for opcode [CMSG_SAVE_CUF_PROFILES 0x6E6 (1766)] sent by [Player: Brewmaster (Guid: 1, Account: 1)]
No defined handler for opcode [CMSG_DB_QUERY_BULK 0x158D (5517)] sent by [Player: Brewmaster (Guid: 1, Account: 1)]
No defined handler for opcode [CMSG_DB_QUERY_BULK 0x158D (5517)] sent by [Player: Brewmaster (Guid: 1, Account: 1)]
No defined handler for opcode [UNKNOWN OPCODE 0x1124 (4388)] sent by [Player: Brewmaster (Guid: 1, Account: 1)]
No defined handler for opcode [CMSG_QUEST_NPC_QUERY 0x1DAE (7598)] sent by [Player: Brewmaster (Guid: 1, Account: 1)]
No defined handler for opcode [UNKNOWN OPCODE 0x1F34 (7988)] sent by [Player: Brewmaster (Guid: 1, Account: 1)]
No defined handler for opcode [CMSG_DB_QUERY_BULK 0x158D (5517)] sent by [Player: Brewmaster (Guid: 1, Account: 1)]
No defined handler for opcode [CMSG_MOVE_FORCE_RUN_SPEED_CHANGE_ACK 0x10F3 (4339)] sent by [Player: Brewmaster (Guid: 1, Account: 1)]
``` 
**Current behaviour:**

If you create a pandaren, you can do nothing. Cuz the opcode handlers are missing.

**Expected behaviour:**

The Handlers should be avaible to play that class

**Steps to reproduce the problem:**

1) Create a Panda Monk
2) Login to the game and test to cmomplete the quest!

**SF rev. hash/commit:** 

9be9bff0ad5dc9444a061bebd4e24b4bb0e16777

**SFDB version:** 

5.4.8

**Operating system:**

Windows 10 x64

**Comment by knuxyl** [comment]
I got the same for Tauren. I can't talk to any NPC's. I think it might be all races this happens to. 

`World initialized in 1 minutes 5 seconds
SF>SF>SkyFire 5.x.x rev. 9be9bff0ad5d 2017-05-23 11:24:32 +0200 (master branch) (Unix, Release) (worldserver-daemon) ready...
No defined handler for opcode [CMSG_REALM_SPLIT 0x18B2 (6322)] sent by [Player: <none> (Guid: 0, Account: 1)]
Disabled opcode [SMSG_UPDATE_ACCOUNT_DATA_COMPLETE 0x0 (0)] have opcode value, but is disabled missing structure update?
No defined handler for opcode [CMSG_DB_QUERY_BULK 0x158D (5517)] sent by [Player: <none> (Guid: 0, Account: 1)]
Race (24) has wrong teamid (42) in DBC: wrong DBC files?
Race (24) has wrong teamid (42) in DBC: wrong DBC files?
WaypointMovementGenerator::LoadPath: creature Instructor Mossthorn (Entry: 57754 GUID: 604148 DB GUID: 604148) doesn't have waypoint path id: 0
Disabled opcode [SMSG_UPDATE_ACCOUNT_DATA_COMPLETE 0x0 (0)] have opcode value, but is disabled missing structure update?
Disabled opcode [SMSG_UPDATE_ACCOUNT_DATA_COMPLETE 0x0 (0)] have opcode value, but is disabled missing structure update?
No defined handler for opcode [UNKNOWN OPCODE 0x6F5 (1781)] sent by [Player: Knuxyl (Guid: 1, Account: 1)]
No defined handler for opcode [CMSG_LEARN_PREVIEW_TALENTS_PET 0x77B (1915)] sent by [Player: Knuxyl (Guid: 1, Account: 1)]
No defined handler for opcode [UNKNOWN OPCODE 0x1F9E (8094)] sent by [Player: Knuxyl (Guid: 1, Account: 1)]
No defined handler for opcode [UNKNOWN OPCODE 0x44E (1102)] sent by [Player: Knuxyl (Guid: 1, Account: 1)]
No defined handler for opcode [UNKNOWN OPCODE 0x365 (869)] sent by [Player: Knuxyl (Guid: 1, Account: 1)]
No defined handler for opcode [UNKNOWN OPCODE 0x32D (813)] sent by [Player: Knuxyl (Guid: 1, Account: 1)]
No defined handler for opcode [CMSG_LFG_LOCK_INFO_REQUEST 0x6B (107)] sent by [Player: Knuxyl (Guid: 1, Account: 1)]
No defined handler for opcode [UNKNOWN OPCODE 0x813 (2067)] sent by [Player: Knuxyl (Guid: 1, Account: 1)]
No defined handler for opcode [UNKNOWN OPCODE 0xA23 (2595)] sent by [Player: Knuxyl (Guid: 1, Account: 1)]
No defined handler for opcode [UNKNOWN OPCODE 0xA87 (2695)] sent by [Player: Knuxyl (Guid: 1, Account: 1)]
No defined handler for opcode [CMSG_VOICE_SESSION_ENABLE 0x15A9 (5545)] sent by [Player: Knuxyl (Guid: 1, Account: 1)]
No defined handler for opcode [CMSG_GUILD_SET_ACHIEVEMENT_TRACKING 0xCF0 (3312)] sent by [Player: Knuxyl (Guid: 1, Account: 1)]
No defined handler for opcode [UNKNOWN OPCODE 0x1203 (4611)] sent by [Player: Knuxyl (Guid: 1, Account: 1)]
No defined handler for opcode [CMSG_SAVE_CUF_PROFILES 0x6E6 (1766)] sent by [Player: Knuxyl (Guid: 1, Account: 1)]
No defined handler for opcode [CMSG_DB_QUERY_BULK 0x158D (5517)] sent by [Player: Knuxyl (Guid: 1, Account: 1)]
No defined handler for opcode [CMSG_DB_QUERY_BULK 0x158D (5517)] sent by [Player: Knuxyl (Guid: 1, Account: 1)]
No defined handler for opcode [CMSG_QUEST_NPC_QUERY 0x1DAE (7598)] sent by [Player: Knuxyl (Guid: 1, Account: 1)]
No defined handler for opcode [UNKNOWN OPCODE 0x1124 (4388)] sent by [Player: Knuxyl (Guid: 1, Account: 1)]
No defined handler for opcode [UNKNOWN OPCODE 0x1F34 (7988)] sent by [Player: Knuxyl (Guid: 1, Account: 1)]
No defined handler for opcode [CMSG_DB_QUERY_BULK 0x158D (5517)] sent by [Player: Knuxyl (Guid: 1, Account: 1)]
Disabled opcode [SMSG_LFG_UPDATE_SEARCH 0x1161 (4449)] have opcode value, but is disabled missing structure update?
No defined handler for opcode [UNKNOWN OPCODE 0x115B (4443)] sent by [Player: <none> (Guid: 0, Account: 1)]
Disabled opcode [SMSG_UPDATE_ACCOUNT_DATA_COMPLETE 0x0 (0)] have opcode value, but is disabled missing structure update?
Disabled opcode [SMSG_UPDATE_ACCOUNT_DATA_COMPLETE 0x0 (0)] have opcode value, but is disabled missing structure update?
No defined handler for opcode [CMSG_REALM_SPLIT 0x18B2 (6322)] sent by [Player: <none> (Guid: 0, Account: 1)]
Spell action 20549 not added into button 9 for player Asdfww (GUID: 2): player don't known this spell
Spell action 20549 not added into button 75 for player Asdfww (GUID: 2): player don't known this spell
No defined handler for opcode [CMSG_REALM_SPLIT 0x18B2 (6322)] sent by [Player: <none> (Guid: 0, Account: 1)]
No defined handler for opcode [CMSG_DB_QUERY_BULK 0x158D (5517)] sent by [Player: <none> (Guid: 0, Account: 1)]
No defined handler for opcode [CMSG_DB_QUERY_BULK 0x158D (5517)] sent by [Player: <none> (Guid: 0, Account: 1)]
No defined handler for opcode [UNKNOWN OPCODE 0x6F5 (1781)] sent by [Player: Asdfww (Guid: 2, Account: 1)]
No defined handler for opcode [CMSG_LEARN_PREVIEW_TALENTS_PET 0x77B (1915)] sent by [Player: Asdfww (Guid: 2, Account: 1)]
No defined handler for opcode [UNKNOWN OPCODE 0x1F9E (8094)] sent by [Player: Asdfww (Guid: 2, Account: 1)]
No defined handler for opcode [UNKNOWN OPCODE 0x44E (1102)] sent by [Player: Asdfww (Guid: 2, Account: 1)]
No defined handler for opcode [UNKNOWN OPCODE 0x365 (869)] sent by [Player: Asdfww (Guid: 2, Account: 1)]
No defined handler for opcode [UNKNOWN OPCODE 0x32D (813)] sent by [Player: Asdfww (Guid: 2, Account: 1)]
No defined handler for opcode [CMSG_LFG_LOCK_INFO_REQUEST 0x6B (107)] sent by [Player: Asdfww (Guid: 2, Account: 1)]
No defined handler for opcode [UNKNOWN OPCODE 0x813 (2067)] sent by [Player: Asdfww (Guid: 2, Account: 1)]
No defined handler for opcode [UNKNOWN OPCODE 0xA23 (2595)] sent by [Player: Asdfww (Guid: 2, Account: 1)]
No defined handler for opcode [UNKNOWN OPCODE 0xA87 (2695)] sent by [Player: Asdfww (Guid: 2, Account: 1)]
No defined handler for opcode [CMSG_VOICE_SESSION_ENABLE 0x15A9 (5545)] sent by [Player: Asdfww (Guid: 2, Account: 1)]
No defined handler for opcode [CMSG_GUILD_SET_ACHIEVEMENT_TRACKING 0xCF0 (3312)] sent by [Player: Asdfww (Guid: 2, Account: 1)]
No defined handler for opcode [UNKNOWN OPCODE 0x1203 (4611)] sent by [Player: Asdfww (Guid: 2, Account: 1)]
No defined handler for opcode [CMSG_SAVE_CUF_PROFILES 0x6E6 (1766)] sent by [Player: Asdfww (Guid: 2, Account: 1)]
No defined handler for opcode [CMSG_DB_QUERY_BULK 0x158D (5517)] sent by [Player: Asdfww (Guid: 2, Account: 1)]
No defined handler for opcode [CMSG_DB_QUERY_BULK 0x158D (5517)] sent by [Player: Asdfww (Guid: 2, Account: 1)]
No defined handler for opcode [UNKNOWN OPCODE 0x1124 (4388)] sent by [Player: Asdfww (Guid: 2, Account: 1)]
No defined handler for opcode [UNKNOWN OPCODE 0x1F34 (7988)] sent by [Player: Asdfww (Guid: 2, Account: 1)]
No defined handler for opcode [CMSG_DB_QUERY_BULK 0x158D (5517)] sent by [Player: Asdfww (Guid: 2, Account: 1)]
No defined handler for opcode [CMSG_REALM_SPLIT 0x18B2 (6322)] sent by [Player: Asdfww (Guid: 2, Account: 1)]
No defined handler for opcode [UNKNOWN OPCODE 0xDE0 (3552)] sent by [Player: Asdfww (Guid: 2, Account: 1)]`

**Comment by Shoxxo** [comment]
I edited your post a bit.!

**Comment by knuxyl** [comment]
thanks, I couldn't figure out how to do that

**Comment by 2h2k** [comment]
I have the same problem !  no quests work due to missing opcodes.

**Comment by alterego21** [comment]
Questing works. It's missing some data.

**Comment by 2h2k** [comment]
Hmm i have the same problems as Shoxxo and knuxyl I can't talk to any NPC's.
`World initialized in 0 minutes 52 seconds
SkyFire 5.x.x rev. 9be9bff0ad5d 2017-05-23 11:24:32 +0200 (master branch) (Win64, Release) (worldserver-daemon) ready...
No defined handler for opcode [CMSG_REALM_SPLIT 0x18B2 (6322)] sent by [Player: <none> (Guid: 0, Account: 1)]
No defined handler for opcode [CMSG_DB_QUERY_BULK 0x158D (5517)] sent by [Player: <none> (Guid: 0, Account: 1)]
No defined handler for opcode [CMSG_DB_QUERY_BULK 0x158D (5517)] sent by [Player: <none> (Guid: 0, Account: 1)]
Player::addSpell: Non-existed in SpellStore spell #13358 request.
Player::addSpell: Non-existed in SpellStore spell #24949 request.
Player::addSpell: Non-existed in SpellStore spell #87816 request.
Disabled opcode [SMSG_UPDATE_ACCOUNT_DATA_COMPLETE 0x0 (0)] have opcode value, but is disabled missing structure update?
No defined handler for opcode [CMSG_QUEST_NPC_QUERY 0x1DAE (7598)] sent by [Player: Arrow (Guid: 4, Account: 1)]
No defined handler for opcode [UNKNOWN OPCODE 0x6F5 (1781)] sent by [Player: Arrow (Guid: 4, Account: 1)]
No defined handler for opcode [CMSG_LEARN_PREVIEW_TALENTS_PET 0x77B (1915)] sent by [Player: Arrow (Guid: 4, Account: 1)]
No defined handler for opcode [UNKNOWN OPCODE 0x1F9E (8094)] sent by [Player: Arrow (Guid: 4, Account: 1)]
No defined handler for opcode [UNKNOWN OPCODE 0x44E (1102)] sent by [Player: Arrow (Guid: 4, Account: 1)]
No defined handler for opcode [UNKNOWN OPCODE 0x365 (869)] sent by [Player: Arrow (Guid: 4, Account: 1)]
No defined handler for opcode [UNKNOWN OPCODE 0x32D (813)] sent by [Player: Arrow (Guid: 4, Account: 1)]
No defined handler for opcode [CMSG_LFG_LOCK_INFO_REQUEST 0x6B (107)] sent by [Player: Arrow (Guid: 4, Account: 1)]
No defined handler for opcode [UNKNOWN OPCODE 0x813 (2067)] sent by [Player: Arrow (Guid: 4, Account: 1)]
No defined handler for opcode [UNKNOWN OPCODE 0xA23 (2595)] sent by [Player: Arrow (Guid: 4, Account: 1)]
No defined handler for opcode [UNKNOWN OPCODE 0xA87 (2695)] sent by [Player: Arrow (Guid: 4, Account: 1)]
No defined handler for opcode [CMSG_VOICE_SESSION_ENABLE 0x15A9 (5545)] sent by [Player: Arrow (Guid: 4, Account: 1)]
No defined handler for opcode [CMSG_GUILD_SET_ACHIEVEMENT_TRACKING 0xCF0 (3312)] sent by [Player: Arrow (Guid: 4, Account: 1)]
No defined handler for opcode [UNKNOWN OPCODE 0x1203 (4611)] sent by [Player: Arrow (Guid: 4, Account: 1)]
No defined handler for opcode [CMSG_DB_QUERY_BULK 0x158D (5517)] sent by [Player: Arrow (Guid: 4, Account: 1)]
No defined handler for opcode [CMSG_DB_QUERY_BULK 0x158D (5517)] sent by [Player: Arrow (Guid: 4, Account: 1)]
No defined handler for opcode [CMSG_SAVE_CUF_PROFILES 0x6E6 (1766)] sent by [Player: Arrow (Guid: 4, Account: 1)]
No defined handler for opcode [CMSG_DB_QUERY_BULK 0x158D (5517)] sent by [Player: Arrow (Guid: 4, Account: 1)]`

this is the error i get when trying to speak to NPC's with all races.

**Comment by Shoxxo** [comment]
Guys... Use quotes!

**Comment by SkyFire** [comment]
for the last time. Those are not errors. They are for debugging. All it means is the opcode handlers are not finished.
