### ISSUE TITLE
Extracting maps,vmaps,mmaps on Linux

### ISSUE THREAD

**Issue by knuxyl** [ProjectSkyfire/SkyFire.548#764]
I believe I posted a while back on a bunch of errors for extracting the data from MoP and I found the fix.
If you get a bunch of errors like 

No such file World\Maps\Stratholme Raid\Stratholme Raid_29_49.adt

and then the program crashes with like a segmentation fault, the problem is the libstorm not being installed.

This isn't included in any documentation I have found, but the extractors use libstorm for MPQ archive reading.

On Ubuntu 16.04 (LTS), libstorm is not available. I went and download libstorm-dev.deb and libstorm.deb for Yakkety Yak and installed those (had to run sudo apt-get install -f to fix dependencies) and now the extractor works.

**Comment by Shoxxo** [comment]
Hey,

Please use the Issue Template for your issue.

Closed!
