### ISSUE TITLE
Hi,guys,Do you have commercial  code for sale?

### ISSUE THREAD

**Issue by huajiang1989** [ProjectSkyfire/SkyFire.548#765]
I have a closer look at your code and submit record, I‘m very much appreciate your high level, I would like to ask you if there is a commercial version of the code to sell, if you can, I think I can use a more appropriate price to buy you to repair a better level Higher source code.
Thanks all

**Comment by SkyFire** [comment]
NO!

**Comment by Shoxxo** [comment]
Really ... wtf is wrong with peoples xD
