### ISSUE TITLE
Repack or full Database

### ISSUE THREAD

**Issue by gasabi** [ProjectSkyfire/SkyFire.548#769]
Do you have a repack or can give Full Database (*.rar) file ? 

Thanks

**Comment by alterego21** [comment]
The database is in the forum. You need to make a forum account to download
it. WE DON'T DO REPACKS!

**Comment by gasabi** [comment]
Can give me Forum URL to download? 

Thanks.

**Comment by SkyFire** [comment]
Seek and you shall find. If your not intelligent enough to find the forum this may be above your skill level.

**Comment by Shoxxo** [comment]
Closed & Locked.
