### ISSUE TITLE
NPC interaction broken

### ISSUE THREAD

**Issue by Smerdokryl** [ProjectSkyfire/SkyFire.548#771]
**Description:**

Whatever NPCs I click on (quest/guard/just talking) turn to me and say their "hi" phrase, but no text/guard window shows up.

I also cannot cast spells on enemy NPCs. For example, I tried casting a shadow bolt on a training dummy and, for a second, my character went into the casting animation, and the spell sound started, but nothing happened after that.

**SF rev. hash/commit:** 

SkyFire 5.x.x rev. 1873afc9205e 2018-01-01 16:24:54 -0600 (master branch) (Win64, Release) (worldserver-daemon)

**SFDB version:**  I'm not sure, I downloaded it yesterday, so should be that one

**Operating system:** Windows 10

**Comment by MobileDev** [comment]
**_have you applied the client patch?_**

**Comment by Smerdokryl** [comment]
Firstly, I had a wow client with two exe's (32 and 64 bit). Neither of them would connect to the server. I tried patching both, which was successful, but they still wouldn't connect. Then I found another torrent and got the wow.exe from there, which connected anyway (perhaps it was already patched), but I still created a patched version of it. I tried on both of these, and both have those problems.

**Comment by Smerdokryl** [comment]
Update: AOE spells, such as the priest talent Halo, do not work either (the character goes into casting animation, but no effect appears).

Also, I have encountered some npcs which have working dialogues, and a couple of spells (for example, incinerate, which, for some reason, is channelled when I click on shadow bolt...)

**Comment by Smerdokryl** [comment]
Well, changing exe's does not seem to help, whether they are patched or not. This problem also doesn't look like something that could be caused by the rest of my client files, so I am at a loss. Any suggestions what I should do?

**Comment by Smerdokryl** [comment]
Here's an example of the messages I get in worldserver, just in case they are related:

`No defined handler for opcode [CMSG_DB_QUERY_BULK 0x158D (5517)] sent by [Player: <none> (Guid: 0, Account: 1)]  
Player::addSpell: Non-existed in SpellStore spell #58284 request.  
Player::addSpell: Non-existed in SpellStore spell #75445 request.  
No defined handler for opcode [UNKNOWN OPCODE 0x6F5 (1781)] sent by [Player: Theron (Guid: 7, Account: 1)]  
No defined handler for opcode [CMSG_LEARN_PREVIEW_TALENTS_PET 0x77B (1915)] sent by [Player: Theron (Guid: 7, Account: 1)]  
No defined handler for opcode [UNKNOWN OPCODE 0x1F9E (8094)] sent by [Player: Theron (Guid: 7, Account: 1)]  
No defined handler for opcode [UNKNOWN OPCODE 0x44E (1102)] sent by [Player: Theron (Guid: 7, Account: 1)]  
No defined handler for opcode [UNKNOWN OPCODE 0x365 (869)] sent by [Player: Theron (Guid: 7, Account: 1)]  
No defined handler for opcode [UNKNOWN OPCODE 0x32D (813)] sent by [Player: Theron (Guid: 7, Account: 1)]  
No defined handler for opcode [CMSG_LFG_LOCK_INFO_REQUEST 0x6B (107)] sent by [Player: Theron (Guid: 7, Account: 1)]  
No defined handler for opcode [UNKNOWN OPCODE 0x813 (2067)] sent by [Player: Theron (Guid: 7, Account: 1)]  
No defined handler for opcode [UNKNOWN OPCODE 0xA23 (2595)] sent by [Player: Theron (Guid: 7, Account: 1)]  
No defined handler for opcode [UNKNOWN OPCODE 0xA87 (2695)] sent by [Player: Theron (Guid: 7, Account: 1)]  
No defined handler for opcode [CMSG_VOICE_SESSION_ENABLE 0x15A9 (5545)] sent by [Player: Theron (Guid: 7, Account: 1)]  
No defined handler for opcode [CMSG_GUILD_SET_ACHIEVEMENT_TRACKING 0xCF0 (3312)] sent by [Player: Theron (Guid: 7, Account: 1)]  
No defined handler for opcode [UNKNOWN OPCODE 0x1203 (4611)] sent by [Player: Theron (Guid: 7, Account: 1)]  
No defined handler for opcode [CMSG_DB_QUERY_BULK 0x158D (5517)] sent by [Player: Theron (Guid: 7, Account: 1)]  
No defined handler for opcode [CMSG_DB_QUERY_BULK 0x158D (5517)] sent by [Player: Theron (Guid: 7, Account: 1)]  
No defined handler for opcode [CMSG_LFG_LOCK_INFO_REQUEST 0x6B (107)] sent by [Player: Theron (Guid: 7, Account: 1)]  
No defined handler for opcode [CMSG_LFG_LOCK_INFO_REQUEST 0x6B (107)] sent by [Player: Theron (Guid: 7, Account: 1)]  
No defined handler for opcode [UNKNOWN OPCODE 0x1D8D (7565)] sent by [Player: Theron (Guid: 7, Account: 1)]  
No defined handler for opcode [CMSG_DB_QUERY_BULK 0x158D (5517)] sent by [Player: Theron (Guid: 7, Account: 1)]  
No defined handler for opcode [CMSG_DB_QUERY_BULK 0x158D (5517)] sent by [Player: Theron (Guid: 7, Account: 1)]`

**Comment by Smerdokryl** [comment]
From what I've seem with all the .exe's I've tried so far, the patcher doesn't help at all. Some of the clients I've downloaded work anyway, even if not patched, the others don't work at all, even if patched.

**Comment by Smerdokryl** [comment]
I have now, just in case, redownloaded and recompiled everything all over again, including importing DB and stuff, strictly according to the Installation instruction. It didn't help

**Comment by alterego21** [comment]
I will load a clean install when I get home tonight.

**Comment by SkyFire** [comment]
Figured it out. It is a DB issue for most of the NPC's. I will look at issuing a fix sometime this weekend If my weekend is slow at my office.

**Comment by Smerdokryl** [comment]
Great, thank you!

I don't know if there is a connection, but I have also noticed multiple spell-related issues, such as:

- Monk roll doesn't do anything
- Abilities which are supposed to release a projectile do not do that (e.g. monk fire blossom, mage frozen orb, priest lvl 90 talents)
- Warlock shadowbolt casts Incinerate even if you aren't destro. Destro spells themselves (including Incinerate) seem to require a crazy amount of mana (around 5m for incinerate when my char has only 300k)
- Demonic circle teleport does not work, and demonic gates, instead of standing where they are supposed to, run off to attack nearby mobs.

Should I create a separate issue thread for that?

I've also noticed that there are opcode warnings for literally anything I do in-game, like switching run/walk. Is that ok?

**Comment by Ulduar2** [comment]
``` CPP
Update: AOE spells, such as the priest talent Halo, do not work either (the character goes into casting animation, but no effect appears).
```
https://github.com/ProjectSkyfire/SkyFire.548/pull/775
Check this please. Maybe help.

**Comment by Ulduar** [comment]
ENG:
So spell after the patch is still not visually displayed?

RU:
Значит, спелл после патча по прежнему не отображается визуально? Досадно.

**Comment by Smerdokryl** [comment]
https://streamable.com/iz5h2

As you can see, the sort of wave effect (also used by spell 137381, but in a weird way) is not there

**Comment by Ulduar** [comment]
EN
There must be another solution.
Somehow convert spell visual into 3.3.5.
Including halo.
I want to understand what is responsible for this. Even if you need a patch in the client.

RU
Должен же быть другой путь.
Как-то же конвертируют spell visual в 3.3.5.
В том числе и сияние.
Я хочу понять, что за это отвечает. Даже если необходим патч в клиент.

**Comment by Ulduar** [comment]
Sorry, i don't know, how your help.

**Comment by Smerdokryl** [comment]
Do you need any logs or anything? Can I help somehow?

**Comment by Smerdokryl** [comment]
Had any luck fixing the issue?

**Comment by Smerdokryl** [comment]
@SkyFire ?

**Comment by tagban** [comment]
This NPC conversation seems to be the same issue I'm having to. Any chance this was fixed? I grabbed the latest database from https://www.projectskyfire.org/index.php?/files/file/29-skyfire-548-database-release-15/  Which appears to be much newer than the date on this issue.

**Comment by SkyFire** [comment]
The issues seems to be with the gossip flag. If you change that value to 2 it will show the quests but that's not right. Something got changed in our gossip system and right now my time is too short to troubleshoot. @tagban The database releases are just all the updates merged up to that date. Contains nothing special.

**Comment by tagban** [comment]
I also realized that nobody can attack. But I figured that might be due to the initial question not complete. Will give this a shot. Thanks! Also I appreciate your work and respect your time. Just love MoP and really didn't want 'yet another WotLK or Legion based server lol

**Comment by tagban** [comment]
@LegionCaos There is a Discord Channel, link is on the IRC Channel.

**Comment by LegionCaos** [comment]
@tagban please can you give me the link of the disk or the link where the candela de dicord is located please

**Comment by SkyFire** [comment]
https://discord.gg/pZF2S2H

**Comment by Shoxxo** [comment]
#793

**Comment by GMKyle** [comment]
hello guys
I check Opcodes.cpp, CMSG_DB_QUERY_BULK and CMSG_REQUEST_HOTFIX have the same value 0x158D, so I comment the line  503 DEFINE_OPCODE_HANDLER(CMSG_DB_QUERY_BULK ... and all gossip are magically working xD.

**Comment by SkyFire** [comment]
@GMKyle  I will look this. Thx.

**Comment by SkyFire** [comment]
Fixed in. https://github.com/ProjectSkyfire/SkyFire.548/commit/8a3cd2f1264327eb2ba8cde19421f5235c0a7666
