### ISSUE TITLE
Item_template update failed

### ISSUE THREAD

**Issue by Smerdokryl** [ProjectSkyfire/SkyFire.548#773]
**Description:**

Applying [the Item_template update](https://github.com/ProjectSkyfire/SkyFire.548/blob/master/sql/updates/world/2017_10_21_00_item_template.sql) fails

**Current behaviour:**

```
Preparing...
Importing 2017_10_21_00_item_template.sql...
Finished executing script
ERROR 1064 (42000) at line 2: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '0, 0, NULL, -1, 0, -1, 0, 0, NULL, -1, 0, -1, 0, 0, NULL, -1, 0, -1, 0, 'The soc' at line 1
Operation failed with exitcode 1
```

**Expected behaviour:**

Should apply normally

**Steps to reproduce the problem:**

1. Install [the latest DB](https://www.projectskyfire.org/index.php?/files/file/27-skyfire-548-database-release-14/)
2. Apply all other updates (shouldn't be related, but I did apply them)
3. Try to apply the Item_template update

I was using MySQL Workbench

**SFDB version:**  14 1.0.0 (is that the right thing?)

**Operating system:** Windows 10

**Comment by SkyFire** [comment]
Fixed here. https://github.com/ProjectSkyfire/SkyFire.548/commit/f1ac5073ad75cfd4063d8eeb91427ffd6a4311aa
