### ISSUE TITLE
NPC spawn SQL error

### ISSUE THREAD

**Issue by Smerdokryl** [ProjectSkyfire/SkyFire.548#776]
**Description:**

Spawning a creature causes an error in worldserver. The creature is not actually saved and disappears if you restart the server.

(something similar happens with gameobjects)

**Current behaviour:**

```
Command: .npc add 20707 [Player: Vladimir (Guid: 10) (Account: 1) X: 3816.817627 Y: -2715.334961 Z: 132.083588 Map: 0 (Восточные королевства) Area: 2037 (Кель'Талас) Zone: Unknown Selected none:  (GUID: 0)]
SQL(p): INSERT INTO creature (guid, id , map, spawnMask, phaseMask, modelid, equipment_id, position_x, position_y, position_z, orientation, spawntimesecs, spawndist, currentwaypoint, curhealth, curmana, MovementType, npcflag, unit_flags, dynamicflags) VALUES (8189913, 20707, 0, 1, 4294967295, 0, 0, 3816.82, -2715.33, 132.084, 0.103813, 300, 0, 0, 42, 0, 0, 0, 0, 0)
 [ERROR]: [1264] Out of range value for column 'phaseMask' at row 1
Unhandled MySQL errno 1264. Unexpected behaviour possible.
```

**Expected behaviour:**

Should spawn normally

**Steps to reproduce the problem:**

1. Spawn some npc as I did above
2. Restart worldserver.exe
3. Log in to see the creature absent

**SF rev. hash/commit:** 

SkyFire 5.x.x rev. 1873afc9205e 2018-01-01 16:24:54 -0600 (master branch) (Win64, Release) (authserver)

**SFDB version:**  Latest

**Operating system:** Windows 10

**Comment by AriDEV** [comment]
Phasemask: 4294967295, this number is the maximum of an unsigned int, in the database the phasemask is a small int.

**Comment by Smerdokryl** [comment]
I tried doing .mod phase 0 on myself before spawning the npc/object - it didn't help

**Comment by SkyFire** [comment]
This was fixed.
