### ISSUE TITLE
Instance worldserver crash

### ISSUE THREAD

**Issue by Smerdokryl** [ProjectSkyfire/SkyFire.548#778]
**Description:**

When teleporting to Firelands (same might happen with other instances/raids), worldserver crashes.

**Current behaviour:**

`InstanceSaveManager::AddInstanceSave: mapid = 720, instanceid = 1, wrong dificalty 254!`

**Steps to reproduce the problem:**

1. Do .teleport firelands

**SF rev. hash/commit:** 

SkyFire 5.x.x rev. 1873afc9205e 2018-01-01 16:24:54 -0600 (master branch) (Win64, Release) (worldserver-daemon)

**SFDB version:** Current

**Operating system:** Windows 10

**Comment by Shoxxo** [comment]
Do a release with debug information build and sent us the crashlog here please.

**Comment by Smerdokryl** [comment]
Sorry it took me rather long.

This appears in worldserver.exe:
```
InstanceSaveManager::AddInstanceSave: mapid = 720, instanceid = 1, wrong dificalty 254!

C:\SkyFireEMU\Core\src\server\game\Maps\Map.cpp:2740 in InstanceMap::AddPlayerToMap ASSERTION FAILED:
  mapSave
[0x3fe77c]
[0x4c7753]
[0x4c6ffa]
[0x17e911]
[0x4061c]
[0x3faec]
[0x1ac3e]
[0x69a37f]
ACE_OS_Thread_Adapter::invoke()+0x7a [0x6391a]
iswascii()+0xa5 [0x1d885]
BaseThreadInitThunk()+0x14 [0x11fe4]
RtlUserThreadStart()+0x21 [0x6ef91]
```
Crashlog:
[c198a54c2fca+_MoP_Piratecraft_worldserver.exe_[4-2_19-21-45].txt](https://github.com/ProjectSkyfire/SkyFire.548/files/1693218/c198a54c2fca._MoP_Piratecraft_worldserver.exe_.4-2_19-21-45.txt)

Crash dump:
[c198a54c2fca+_MoP_Piratecraft_worldserver.exe_[4-2_19-21-45].zip](https://github.com/ProjectSkyfire/SkyFire.548/files/1693220/c198a54c2fca._MoP_Piratecraft_worldserver.exe_.4-2_19-21-45.zip)

**Comment by AriDEV** [comment]
Should be fixed in ef5bfbf

**Comment by Smerdokryl** [comment]
I can confirm that it's fixed in ef5bfbf

Thank you!

**Comment by Smerdokryl** [comment]
Just got a crash when teleporting to Unga Ingoo with gm mode on.

Worldserver:
`CreateInstance: no instance template for map 1048`

Crash log:
[bb178db49562+_worldserver.exe_[18-2_21-25-25].txt](https://github.com/ProjectSkyfire/SkyFire.548/files/1735130/bb178db49562._worldserver.exe_.18-2_21-25-25.txt)

**Comment by SkyFire** [comment]
Your crash dump is not good. Need to compile in relwithdebug or in debug. I will reopen for now.

**Comment by AriDEV** [comment]
unga ingoo is a scenario not dungeon or raid. the scenario system isnt implemented yet only dungeons and raids are working right now
