### ISSUE TITLE
Error on compile 

### ISSUE THREAD

**Issue by Tortschi** [ProjectSkyfire/SkyFire.548#782]
**Description:**

When i compile the last Version i get this Errors:

Scanning dependencies of target shared
[  9%] Building CXX object src/server/shared/CMakeFiles/shared.dir/Configuration/Config.cpp.o
[  9%] Building CXX object src/server/shared/CMakeFiles/shared.dir/Cryptography/Authentication/AuthCrypt.cpp.o
In file included from /root/SkyFire.548/src/server/shared/Cryptography/Authentication/AuthCrypt.h:23:0,
                 from /root/SkyFire.548/src/server/shared/Cryptography/Authentication/AuthCrypt.cpp:20:
/root/SkyFire.548/src/server/shared/Cryptography/ARC4.h:35:24: error: field 'm_ctx' has incomplete type 'EVP_CIPHER_CTX {aka evp_cipher_ctx_st}'
         EVP_CIPHER_CTX m_ctx;
                        ^~~~~
compilation terminated due to -Wfatal-errors.
make[2]: *** [src/server/shared/CMakeFiles/shared.dir/Cryptography/Authentication/AuthCrypt.cpp.o] Error 1
make[1]: *** [src/server/shared/CMakeFiles/shared.dir/all] Error 2
make: *** [all] Error 2

**SF rev. hash/commit:** 

**SFDB version:** 

**Operating system:** Ubuntu 14.04

**Comment by Bootz** [comment]
wut version of OpenSSL are you using?

**Comment by Tortschi** [comment]
Thanks for your help. Now i have this Error:


/usr/bin/ld: cannot find -lncurses
collect2: error: ld returned 1 exit status
src/server/worldserver/CMakeFiles/worldserver.dir/build.make:292: recipe for target 'src/server/worldserver/worldserver' failed
make[2]: *** [src/server/worldserver/worldserver] Error 1
CMakeFiles/Makefile2:1259: recipe for target 'src/server/worldserver/CMakeFiles/worldserver.dir/all' failed
make[1]: *** [src/server/worldserver/CMakeFiles/worldserver.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Tortschi** [comment]
Thanks. Missing Boost Lib.
