### ISSUE TITLE
Readline library not found!

### ISSUE THREAD

**Issue by Stabatha** [ProjectSkyfire/SkyFire.548#784]
**Description:**

Receiving Readline library not found!

**Current behaviour:**

When trying to compile I receive an error

-- Found OpenSSL headers: /usr/include
-- Using mysql-config: /usr/bin/mysql_config
-- Found MySQL library: /usr/lib/x86_64-linux-gnu/libmysqlclient.so
-- Found MySQL headers: /usr/include/mysql
CMake Error at cmake/macros/FindReadline.cmake:26 (MESSAGE):
  ** Readline library not found!

  **
Call Stack (most recent call first):
  CMakeLists.txt:66 (find_package)

-- Configuring incomplete, errors occurred!
See also "/SkyFire.548/build/CMakeFiles/CMakeOutput.log".
See also "/SkyFire.548/build/CMakeFiles/CMakeError.log".

**Expected behaviour:**

Should complete compile

**Steps to reproduce the problem:**

Running cmake ../ -DPREFIX=/home/`echo $USER`/skyfire -DTOOLS=1

https://github.com/ProjectSkyfire/SkyFire.548/commit/65e7ce6e66fa99cd73e8740581fc7bcb4fe209ac

**Operating system:** Ubuntu 16.04

![capture](https://user-images.githubusercontent.com/112463/37063039-c99d6890-215d-11e8-926c-3c212a4fad0f.PNG)

**Comment by AriDEV** [comment]
hello make sure you not missing libreadline-dev package, libreadline6-dev is a dependancy package for libreadline thouse are 2 diffrent libraries.

**Comment by Stabatha** [comment]
Thanks!  I'll give that a try

**Comment by Stabatha** [comment]
Ok ran that and it installed libreadline-dev and libreadline6-dev but I still get Readline library not found.  I rebooted, deleted SkyFire and re-cloned, everything I can think of but still get the error.

**Comment by Shoxxo** [comment]
Upgrade to Ubuntu 17.04 or Debian 9.

Ubuntu 16.04 no longer supported!

**Comment by Stabatha** [comment]
What about Ubuntu 17.10 or CentOS 7.4 @Shoxxo   My datacenter doesn't have 17.04 or  Debian 9

Here is my choices of OS I can reload to my dedicated server.

![os](https://user-images.githubusercontent.com/112463/37180810-079ed140-22f0-11e8-8eb1-11ca54cac52c.png)

**Comment by SkyFire** [comment]
Debian 9 is a good choice.

**Comment by Stabatha** [comment]
Debian 9 isn't on that list though  :(  Debian "Jessie" is 8, or so I thought.

**Comment by Stabatha** [comment]
How have you been Alter?  been many years,  nice to see SkyFireEMU is still up and running  :)

**Comment by Stabatha** [comment]
Ok trying on Debian 9 on a VPS elsewhere.  Still getting readline not found when running cmake

libreadline-dev exists though

# apt-get install libreadline-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
libreadline-dev is already the newest version (7.0-3).

# gcc --version
gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516


I'm not sure what I'm doing wrong  :(

**Comment by AriDEV** [comment]
@Shoxxo Ubuntu xenial is supported.
@Stabatha cmake version ?

**Comment by Stabatha** [comment]
@AriDEV is it ok my libreadline-dev is 7.0-3 but my gcc is 6.3?

**Comment by AriDEV** [comment]
gcc is fine 
for libreadline you might want to symlink

**Comment by AriDEV** [comment]
`sudo ln -s /var/lib/libreadline.so.7 /var/lib/libreadline.so.6`

**Comment by Stabatha** [comment]
@AriDEV it's cmake version 3.7.2

**Comment by AriDEV** [comment]
navigate to your Skyfire folder then write:
`mkdir build`
`cd build`

then choose one of this cmake commands:
if you want to cmake with scripts and tools:
`cmake ../ -DScripts=1 -DTOOLS=1`
if you want to cmake with scripts and without tools:
`cmake ../ -DScripts=1 -DTOOLS=0`
if you want to cmake without scripts and with tools:
`cmake ../ -DScripts=0 -DTOOLS=1`
if you want to cmake without scripts and without tools:
`cmake ../ -DScripts=0 -DTOOLS=0`

link me the output what you get from this.

**Comment by Stabatha** [comment]
@AriDEV Got it to work on Deb 9,  but prob is my dedicated server doesn't offer it.  Would really like to get it running on CentOS7.  Here is the error still from CentOS7

]# cmake ../ -DSCRIPTS=0 -DTOOLS=0
-- Detected 64-bit platform
-- UNIX: Using jemalloc
-- UNIX: Using default configuration directory
-- UNIX: Using default library directory
-- UNIX: Configuring uninstall target
-- UNIX: Created uninstall target
-- UNIX: Detected compiler: /usr/local/bin/ccache
/usr/local/bin/ccache: invalid option -- 'd'
Usage:
    ccache [options]
    ccache compiler [compiler options]
    compiler [compiler options]          (via symbolic link)

Options:
    -c, --cleanup         delete old files and recalculate size counters
                          (normally not needed as this is done automatically)
    -C, --clear           clear the cache completely (except configuration)
    -F, --max-files=N     set maximum number of files in cache to N (use 0 for
                          no limit)
    -M, --max-size=SIZE   set maximum size of cache to SIZE (use 0 for no
                          limit); available suffixes: k, M, G, T (decimal) and
                          Ki, Mi, Gi, Ti (binary); default suffix: G
    -o, --set-config=K=V  set configuration key K to value V
    -p, --print-config    print current configuration options
    -s, --show-stats      show statistics summary
    -z, --zero-stats      zero statistics counters

    -h, --help            print this help text
    -V, --version         print version and copyright information

See also <https://ccache.samba.org>.
CMake Error at cmake/platform/unix/settings.cmake:50 (message):
  GCC: Compiler doesnt support c++14, requires g++ 6.0 or greater.
Call Stack (most recent call first):
  cmake/macros/CheckPlatform.cmake:26 (include)
  CMakeLists.txt:52 (include)


-- Configuring incomplete, errors occurred!
See also "/SkyFire.548/build/CMakeFiles/CMakeOutput.log".
[01:14][root@slapshot.pucksters.com build]# ^C
[01:14][root@slapshot.pucksters.com build]# nano /SkyFire.548/build/CMakeFiles/CMakeOutput.log
You have new mail in /var/spool/mail/root
[01:15][root@slapshot.pucksters.com build]# rm -rf /SkyFire.548/build/CMakeFiles/CMakeOutput.log
[01:15][root@slapshot.pucksters.com build]# cmake ../ -DSCRIPTS=0 -DTOOLS=0
-- Detected 64-bit platform
-- UNIX: Using jemalloc
-- UNIX: Using default configuration directory
-- UNIX: Using default library directory
-- UNIX: Configuring uninstall target
-- UNIX: Created uninstall target
-- UNIX: Detected compiler: /usr/local/bin/ccache
/usr/local/bin/ccache: invalid option -- 'd'
Usage:
    ccache [options]
    ccache compiler [compiler options]
    compiler [compiler options]          (via symbolic link)
Options:
    -c, --cleanup         delete old files and recalculate size counters
                          (normally not needed as this is done automatically)
    -C, --clear           clear the cache completely (except configuration)
    -F, --max-files=N     set maximum number of files in cache to N (use 0 for
                          no limit)
    -M, --max-size=SIZE   set maximum size of cache to SIZE (use 0 for no
                          limit); available suffixes: k, M, G, T (decimal) and
                          Ki, Mi, Gi, Ti (binary); default suffix: G
    -o, --set-config=K=V  set configuration key K to value V
    -p, --print-config    print current configuration options
    -s, --show-stats      show statistics summary
    -z, --zero-stats      zero statistics counters

    -h, --help            print this help text
    -V, --version         print version and copyright information

See also <https://ccache.samba.org>.
CMake Error at cmake/platform/unix/settings.cmake:50 (message):
  GCC: Compiler doesnt support c++14, requires g++ 6.0 or greater.
Call Stack (most recent call first):
  cmake/macros/CheckPlatform.cmake:26 (include)
  CMakeLists.txt:52 (include)


-- Configuring incomplete, errors occurred!

but I have using g++ 6.0 or greater

# g++ --version
g++ (GCC) 6.1.0

**Comment by Stabatha** [comment]
and thank you for all your help @AriDEV   It's much appreciated

**Comment by AriDEV** [comment]
i have not much experience with centos but im using ubuntu xenial 16.04LTS.
the error message is simple, it indicates that you GCC is using your older default version of gcc
thats why you get the message that your gcc dosnt support c++14
`GCC: Compiler doesnt support c++14, requires g++ 6.0 or greater.`

in ubuntu however you would like to update alternatives like this:
`sudo apt-get install g++-6`
`sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 100`
`sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 100`
`sudo update-alternatives --install /usr/bin/cpp cpp-bin /usr/bin/cpp-6 100`
`sudo update-alternatives --config gcc`

in ubuntu you could also try export with:
`export CXX=/usr/bin/g++-6 CC=/usr/bin/gcc-6`

**Comment by Stabatha** [comment]
@AriDEV  Trying on Ubuntu 16.04

# sudo apt-get install g++-6
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package g++-6
E: Couldn't find any package by regex 'g++-6'

**Comment by AriDEV** [comment]
You should use the ubuntu toolchain ppa to download gcc
`sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y`
`sudo apt-get update`
`sudo apt-get install gcc-6 g++-6`

**Comment by Stabatha** [comment]
woot!  Getting closer @AriDEV    getting this error during make.

[ 44%] Building CXX object src/server/shared/CMakeFiles/shared.dir/Cryptography/ARC4.cpp.o
In file included from /SkyFire.548/src/server/shared/Cryptography/ARC4.cpp:20:0:
/SkyFire.548/src/server/shared/Cryptography/ARC4.h:35:24: error: field 'm_ctx' has incomplete type 'EVP                              _CIPHER_CTX {aka evp_cipher_ctx_st}'
         EVP_CIPHER_CTX m_ctx;
                        ^~~~~
In file included from /usr/include/openssl/evp.h:14:0,
                 from /SkyFire.548/src/server/shared/Cryptography/ARC4.h:24,
                 from /SkyFire.548/src/server/shared/Cryptography/ARC4.cpp:20:
/usr/include/openssl/ossl_typ.h:90:16: note: forward declaration of 'EVP_CIPHER_CTX {aka struct evp_cip                              her_ctx_st}'
 typedef struct evp_cipher_ctx_st EVP_CIPHER_CTX;
                ^~~~~~~~~~~~~~~~~
src/server/shared/CMakeFiles/shared.dir/build.make:86: recipe for target 'src/server/shared/CMakeFiles/                              shared.dir/Cryptography/ARC4.cpp.o' failed
make[2]: *** [src/server/shared/CMakeFiles/shared.dir/Cryptography/ARC4.cpp.o] Error 1
CMakeFiles/Makefile2:634: recipe for target 'src/server/shared/CMakeFiles/shared.dir/all' failed
make[1]: *** [src/server/shared/CMakeFiles/shared.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by AriDEV** [comment]
this is an error if you using openssl 1.1 make sure you are using openssl 1.0.2

**Comment by Stabatha** [comment]
@AriDEV  so apt remove openssl and then compile 1.0.2  with ./configure --disable-ssl ?

**Comment by AriDEV** [comment]
you dont need to compile openssl you can get it from ubuntu with apt-get

**Comment by AriDEV** [comment]
ubuntu xenial allready have a package for 1.0.2
https://packages.ubuntu.com/xenial/openssl

**Comment by Stabatha** [comment]
oh I found in the wiki
wget http://ftp.debian.org/debian/pool/main/o/openssl/libssl-dev_1.0.2l-1~bpo8+1_amd64.deb
wget http://ftp.debian.org/debian/pool/main/o/openssl/libssl1.0.0_1.0.2l-1~bpo8+1_amd64.deb
wget http://ftp.debian.org/debian/pool/main/o/openssl/openssl_1.0.2l-1~bpo8+1_amd64.deb
sudo dpkg -i libssl-dev_1.0.2l-1~bpo8+1_amd64.deb
sudo dpkg -i libssl1.0.0_1.0.2l-1~bpo8+1_amd64.deb
sudo dpkg -i openssl_1.0.2l-1~bpo8+1_amd64.deb

going well so far!  make at 68%

**Comment by Stabatha** [comment]
yay!
Install the project...
-- Install configuration: "Release"
-- Installing: /home/stormstout/bin/authserver
-- Set runtime path of "/home/stormstout/bin/authserver" to "/home/authserver/lib"
-- Installing: /home/stormstout/etc/authserver.conf.dist
-- Installing: /home/stormstout/bin/worldserver
-- Set runtime path of "/home/stormstout/bin/worldserver" to "/home/authserver/lib"
-- Installing: /home/stormstout/etc/worldserver.conf.dist

THANK YOU again so much @AriDEV very very much appreciated all the help you gave me

**Comment by AriDEV** [comment]
So the issue is solved and can be Closed?

**Comment by Stabatha** [comment]
Yes  :)
