### ISSUE TITLE
map extraction errors

### ISSUE THREAD

**Issue by Stabatha** [ProjectSkyfire/SkyFire.548#786]
**Description:**

errors extracting maps

**Current behaviour:**

DBC and DB2 extract fine but maps error and map folder remains empty. Tried both extractors created from building source with tools on my Linux 16.04 server  and using the SkyFire-Community-Tools-master on my Win10 desktop

**Expected behaviour:**

to extract the map files

**Steps to reproduce the problem:**

run the extractor.  

Extracting maps...
Read Map.dbc file... Done! (288 maps loaded)
Read AreaTable.dbc file...Done! (3991 areas loaded)
Read LiquidType.dbc file...Done! (61 LiqTypes loaded)
Convert map files
Extract Azeroth (1/288)
Error loading World\Maps\Azeroth\Azeroth.wdt
Extract Kalimdor (2/288)
Error loading World\Maps\Kalimdor\Kalimdor.wdt
Extract test (3/288)
No such file World\Maps\test\test.wdt
Extract ScottTest (4/288)
No such file World\Maps\ScottTest\ScottTest.wdt
Extract PVPZone01 (5/288)
Error loading World\Maps\PVPZone01\PVPZone01.wdt
Extract Shadowfang (6/288)
Error loading World\Maps\Shadowfang\Shadowfang.wdt
Extract StormwindJail (7/288)
Error loading World\Maps\StormwindJail\StormwindJail.wdt
Extract StormwindPrison (8/288)

**SF rev. hash/commit:** 

master 5feae33c273714f847d548917716f903b43a3429

**Operating system:** CHANGEME OS

Ubuntu 16.04

**Comment by Stabatha** [comment]
Just tried on Deb9 with libstorm-dev  and still same issue

**Comment by SkyFire** [comment]
It's not the extractors. You have incomplete data. Meaning your client is missing data.

**Comment by Stabatha** [comment]
oh, I see that now.  Going on someone else's server there is background downloading still

**Comment by Shoxxo** [comment]
:) Better first check client, than report issue ;) But nice that we can help you.

**Comment by Stabatha** [comment]
It's been 10 years since I set up a emu  :P   Yeah after I clicked the WoW icon  when that popup ran for like 10 minutes I thought it was fully installed since there was .MPQ files populated.

**Comment by SkyFire** [comment]
Closed. Assumed Resolved
