### ISSUE TITLE
Lots of errors  & GM commands cause crash

### ISSUE THREAD

**Issue by Stabatha** [ProjectSkyfire/SkyFire.548#787]
**Description:**

Lot's of errors as you can see in the screenshot and using any gm command cause Segmentation fault. crashing the world server

**SF rev. hash/commit:** 

latest - https://github.com/ProjectSkyfire/SkyFire.548/commit/5feae33c273714f847d548917716f903b43a3429
![lots of errors](https://user-images.githubusercontent.com/112463/37397964-ffbcf3c6-274a-11e8-9c2b-5c970e7a54d0.PNG)

**SFDB version:** latest -   release 15 1.0.0

Database is installed and populated  

![db](https://user-images.githubusercontent.com/112463/37398178-a211ae8c-274b-11e8-9a54-30d26ee407d1.PNG)

**Operating system:** Ubuntu 16.04

**Comment by SkyFire** [comment]
If you look at your screenshot. they are no errors :) These are just messages about stuff that is missing data.
Far as the crash you would need to compile in debug and submit a stacktrace.

**Comment by Artamedes** [comment]
https://github.com/TrinityCore/TrinityCore/commit/2d942ddcc528cc9fe718ebbd5903318fcbdab817#diff-3765624a2b35376a91cf4d1930d65f6d will fix crash

**Comment by AriDEV** [comment]
@Stabatha can you tell me what command you used? so i can try to reproduce the crash?

**Comment by Stabatha** [comment]
@AriDEV    Just any word starting with  a period  .gm on  or .gfddsedd.  Even just member with no gm powers can crash it

**Comment by AriDEV** [comment]
https://gist.github.com/AriDEV/f874b99bac9103e76a1215060d9e6d8a

**Comment by AriDEV** [comment]
https://github.com/ProjectSkyfire/SkyFire.548/commit/e83cf0f6ca0f32b046956b3fc32872455d7af657
