### ISSUE TITLE
Tiger Power not granting armor penetration

### ISSUE THREAD

**Issue by iamreyne** [ProjectSkyfire/SkyFire.548#803]
**Description:**

Tiger Power does not grant armor penetration.

**Current behaviour:**

Gain Tiger Power from Tiger Palm. Tiger Power does not increase any damage.

**Expected behaviour:**

Gain Tiger Power from Tiger Palm. Attacks penetrate 30% of targets armor for 20 seconds.

**Steps to reproduce the problem:**

1. Cast Tiger Palm
2. Gain Tiger Power Buff
3. Current/Expected behavior above.

**SF rev. hash/commit:**  

5.x.x rev 6c707a4d746d 2018-06-01 13:20:44 +0200 (master branch) (Unix, Release)

**SFDB version:**  [SFDB 15](https://www.projectskyfire.org/index.php?/files/file/29-skyfire-548-database-release-15/)

**Operating system:** Ubuntu 14.06

**Comment by AriDEV** [comment]
https://github.com/ProjectSkyfire/SkyFire.548/commit/d26da16e8ac901e2c3edeacfe8ffe6b3b4707d75
