### ISSUE TITLE
Searing Totem not working as intended

### ISSUE THREAD

**Issue by iamreyne** [ProjectSkyfire/SkyFire.548#806]
**Description:**

Searing Totem doesn't work.

**Current behaviour:**

Searing Totem spawns, but never attacks.

**Expected behaviour:**

Expected to spawn and attack in a 40 yard radius.

**Steps to reproduce the problem:**

1. Cast Searing Totem
2. Does not attack

**SF rev. hash/commit:**  

5.x.x rev 6c707a4d746d 2018-06-01 13:20:44 +0200 (master branch) (Unix, Release)

**SFDB version:**  [SFDB 15](https://www.projectskyfire.org/index.php?/files/file/29-skyfire-548-database-release-15/)

**Operating system:** Ubuntu 14.06

**Comment by GMKyle** [comment]
UPDATE creature_template` SET `spell1` = 3606 WHERE `entry` = 2523
Test this please!!
