### ISSUE TITLE
Error on world start up - Rank

### ISSUE THREAD

**Issue by madmax765** [ProjectSkyfire/SkyFire.548#810]
Unable to start world server

Steps to reproduce the problem:
Hello my server ran ok at Commits on May 30, 2018 4805af1 I update core... to Commits on Jun 5, 2018 6b71dcc﻿ updated MYSQL to 8.0 got the core to compile ok. But I get an error unknown column in 'rank' in 'field list" when I try to run the worldserver

Loading guilds definitions...

        Loaded 1﻿ guild definitions in 4 ms
        Loading guild ranks...
        Loaded 5 guild ranks in 3 ﻿ms
        Loading guild members... ﻿

I installed fresh DB SFDB_full_548.15_2018_03_06 and applied the 3 SQL update in the world folder

and ran the 2018_06_01_00_characters in the character update folder too

SF rev. hash/commit:
6b71dcc

SFDB version:
SFDB_full_548.15_2018_03_06

Operating system:
OS windows 10 pro

**Comment by AriDEV** [comment]
for me it looks like 2018_06_01_00_characters.sql wasnt applied.

**Comment by madmax765** [comment]
I tryed again with Commits on Jun 8, 2018  9b445cec6d985b053bbb26e6db01d06850d4a085
![rank](https://user-images.githubusercontent.com/29853/41163293-48928422-6b06-11e8-8f32-076e5b91e070.png)
and with new SFDB_full_548.16_2018_06_07

`Using configuration file worldserver.conf.
Using SSL version: OpenSSL 1.0.2l  25 May 2017 (library: OpenSSL 1.0.0d 8 Feb 2011)
Using ACE version: 6.4.5
SkyFire 5.x.x rev. 9b445cec6d98 2018-06-08 12:29:24 +0200 (master branch) (Win64, Release) (worldserver-daemon)
<Ctrl-C> to stop.

   ______  __  __  __  __  ______ __  ______  ______ 
  /\  ___\/\ \/ / /\ \_\ \/\  ___/\ \/\  == \/\  ___\ 
  \ \___  \ \  _'-\ \____ \ \  __\ \ \ \  __<\ \  __\ 
   \/\_____\ \_\ \_\/\_____\ \_\  \ \_\ \_\ \_\ \_____\ 
    \/_____/\/_/\/_/\/_____/\/_/   \/_/\/_/ /_/\/_____/ 
  Project SkyFireEmu 2011 - 2017(c) Open-sourced Game Emulation 
           <http://www.projectskyfire.org/> 

Realm running as realm ID 1
Using World DB: SFDB 548.Release.15
Using enUS DBC Locale
Will clear `logs` table of entries older than 1209600 seconds every 10 minutes.
Using DataDir ../5-4-8/
WORLD: MMap data directory is: ../5-4-8/mmaps
VMap support included. LineOfSight: 1, getHeight: 1, indoorCheck: 1
VMap data directory is: ../5-4-8/vmaps
Loading Skyfire strings...
>> Loaded 1117 Skyfire strings from table skyfire_string in 7 ms
Initialize data stores...
>> Initialized 151 DBC data stores in 2080 ms
Loading SpellInfo store...
>> Loaded SpellInfo store in 2848 ms
Loading SpellInfo corrections...
>> Loaded SpellInfo corrections in 60 ms
Loading SkillLineAbilityMultiMap Data...
>> Loaded 8240 SkillLineAbility MultiMap Data in 4 ms
Loading SpellInfo custom attributes...
>> Loaded SpellInfo custom attributes in 207 ms
Loading GameObject models...
>> Loaded 5526 GameObject models in 8 ms
Loading Script Names...
>> Loaded 2355 Script Names in 230 ms
Loading Instance Template...
>> Loaded 110 instance templates in 2 ms
Loading instances...
>> Loaded instances in 47 ms
Loading Localization strings...
>> Localization strings loaded in 17 ms
Loading Account Roles and Permissions...
>> Loaded 633 permission definitions, 616 linked permissions and 4 default permissions in 13 ms
Loading Page Texts...
>> Loaded 1876 page texts in 20 ms
Loading Game Object Templates...
>> Loaded 35997 game object templates in 1013 ms
Loading Transport templates...
>> Loaded 44 transport templates in 69 ms
Loading Spell Rank Data...
>> Loaded 132 spell rank records in 3 ms
Loading Spell Required Data...
>> Loaded 22 spell required records in 2 ms
Loading Spell Group types...
>> Loaded 346 spell group definitions in 3 ms
Loading Spell Learn Skills...
>> Loaded 145 Spell Learn Skills from DBC in 55 ms
Loading Spell Learn Spells...
>> Loaded 6 spell learn spells, 359 found in Spell.dbc and 0 from TalentTab.dbc in 50 ms
Loading Spell Proc Event conditions...
>> Loaded 316 extra spell proc event conditions in 4 ms
Loading Spell Proc conditions and data...
>> Loaded 0 spell proc conditions and data. DB table `spell_proc` is empty.
Loading Spell Bonus Data...
>> Loaded 218 extra spell bonus data in 3 ms
Loading Aggro Spells Definitions...
>> Loaded 31 SpellThreatEntries in 2 ms
Loading Spell Group Stack Rules...
>> Loaded 41 spell group stack rules in 1 ms
Loading Spell Phase Dbc Info...
>> Loaded 0 spell dbc infos. DB table `spell_phase` is empty.
Loading NPC Texts...
>> Loaded 7867 npc texts in 321 ms
Loading Enchant Spells Proc datas...
>> Loaded 0 spell enchant proc event conditions. DB table `spell_enchant_proc_data` is empty.
Loading Item Random Enchantments Table...
>> Loaded 28607 Item Enchantment definitions in 71 ms
Loading Disables
>> Loaded 74 disables in 2 ms
Loading Items...
>> Loaded 10023 item templates from Item-sparse.db2 and 62240 from database in 4541 ms
Loading Item set names...
>> Loaded 661 item addon templates in 4 ms
>> Loaded 18 item script names in 2 ms
Loading Creature Model Based Info Data...
>> Loaded 37591 creature model based info in 163 ms
Loading Creature templates...
>> Loaded 56886 creature definitions in 3075 ms
Loading Equipment templates...
>> Loaded 10542 equipment templates in 55 ms
Loading Creature template addons...
>> Loaded 16844 creature template addons in 123 ms
Loading Reputation Reward Rates...
>> Loaded 14 reputation_reward_rate in 2 ms
Loading Creature Reputation OnKill Data...
>> Loaded 2023 creature award reputation definitions in 15 ms
Loading Reputation Spillover Data...
>> Loaded 28 reputation_spillover_template in 3 ms
Loading Points Of Interest Data...
>> Loaded 490 Points of Interest definitions in 5 ms
Loading Creature Base Stats...
>> Loaded 380 creature base stats in 612 ms
Loading Creature Data...
>> Loaded 207728 creatures in 5308 ms
Loading Temporary Summon Data...
>> Loaded 132 temp summons in 4 ms
Loading pet levelup spells...
>> Loaded 472 pet levelup and default spells for 65 families in 20 ms
Loading pet default spells additional to levelup spells...
>> Loaded addition spells for 0 pet spell data entries in 6 ms
Loading summonable creature templates...
>> Loaded 601 summonable creature templates in 53 ms
Loading Creature Addon Data...
>> Loaded 16197 creature addons in 106 ms
Loading Gameobject Data...
>> Loaded 67384 gameobjects in 1686 ms
Loading Creature Linked Respawn...
>> Loaded 3791 linked respawns in 1202 ms
Loading Weather Data...
>> Loaded 35 weather definitions in 2 ms
Loading Quests...
>> Loaded 17930 quests definitions in 2179 ms
Checking Quest Disables
>> Checked 69 quest disables in 0 ms
Loading Quest Objectives...
>> Loaded 15970 Quest Objectives in 336 ms.
Loading Quest Objective Locales...
>> Loaded 0 Quest Objective locale descriptions. DB table `locales_quest_objective` is empty.
Loading Quest Objective Visual Effects...
>> Loaded 1443 Quest Objective visual effects in 30 ms.
Loading Quest POI
>> Loaded 22149 quest POI definitions in 369 ms
Loading Quests Starters and Enders...
Loading GO Start Quest Data...
>> Loaded 642 quest relations from gameobject_queststarter in 7 ms
Loading GO End Quest Data...
>> Loaded 513 quest relations from gameobject_questender in 5 ms
Loading Creature Start Quest Data...
>> Loaded 10453 quest relations from creature_queststarter in 80 ms
Loading Creature End Quest Data...
>> Loaded 10806 quest relations from creature_questender in 84 ms
Loading Objects Pooling Data...
>> Loaded 3052 objects pools in 6 ms
Loading Creatures Pooling Data...
>> Loaded 325 creatures in pools in 2 ms
Loading Gameobject Pooling Data...
>> Loaded 5776 gameobject in pools in 23 ms
Loading Mother Pooling Data...
>> Loaded 2259 pools in mother pools in 45 ms
Loading Quest Pooling Data...
>> Loaded 267 quests in pools in 5 ms
Starting objects pooling system...
Loading Game Event Data...
>> Loaded 49 game events in 3 ms
Loading Game Event Saves Data...
>> Loaded 0 game event saves in game events. DB table `game_event_save` is empty.
Loading Game Event Prerequisite Data...
>> Loaded 0 game event prerequisites in game events. DB table `game_event_prerequisite` is empty.
Loading Game Event Creature Data...
>> Loaded 1257 creatures in game events in 4 ms
Loading Game Event GO Data...
>> Loaded 8250 gameobjects in game events in 33 ms
Loading Game Event Model/Equipment Change Data...
>> Loaded 0 model/equipment changes in game events. DB table `game_event_model_equip` is empty.
Loading Game Event Quest Data...
>> Loaded 327 quests additions in game events in 2 ms
Loading Game Event GO Quest Data...
>> Loaded 189 quests additions in game events in 2 ms
Loading Game Event Quest Condition Data...
>> Loaded 0 quest event conditions in game events. DB table `game_event_quest_condition` is empty.
Loading Game Event Condition Data...
>> Loaded 0 conditions in game events. DB table `game_event_condition` is empty.
Loading Game Event Condition Save Data...
>> Loaded 0 condition saves in game events. DB table `game_event_condition_save` is empty.
Loading Game Event NPCflag Data...
>> Loaded 0 npcflags in game events. DB table `game_event_npcflag` is empty.
Loading Game Event Seasonal Quest Relations...
>> Loaded 620 quests additions in game events in 3 ms
Loading Game Event Vendor Additions Data...
>> Loaded 2 vendor additions in game events in 1 ms
Loading Game Event Battleground Data...
>> Loaded 6 battleground holidays in game events in 2 ms
Loading Game Event Pool Data...
>> Loaded 8 pools for game events in 2 ms
Loading UNIT_NPC_FLAG_SPELLCLICK Data...
>> Loaded 406 spellclick definitions in 22 ms
Loading Vehicle Template Accessories...
>> Loaded 120 Vehicle Template Accessories in 2 ms
Loading Vehicle Accessories...
>> Loaded 0 Vehicle Accessories in 1 ms
Loading SpellArea Data...
>> Loaded 431 spell area requirements in 6 ms
Loading AreaTrigger definitions...
>> Loaded 337 area trigger teleport definitions in 4 ms
Loading Access Requirements...
>> Loaded 179 access requirement definitions in 2 ms
Loading Quest Area Triggers...
>> Loaded 54 quest trigger points in 2 ms
Loading Tavern Area Triggers...
>> Loaded 176 tavern triggers in 3 ms
Loading AreaTrigger script names...
>> Loaded 95 areatrigger scripts in 2 ms
Loading LFG entrance positions...
>> Loaded 14 lfg entrance positions in 4 ms
LFGMgr::LoadLFGDungeons: Failed to load dungeon Random Cataclysm Dungeon (Id: 300), cant find areatrigger for map 65535
LFGMgr::LoadLFGDungeons: Failed to load dungeon Prince Sarsarun (Id: 310), cant find areatrigger for map 734
LFGMgr::LoadLFGDungeons: Failed to load dungeon Random Burning Crusade Heroic (Id: 260), cant find areatrigger for map 65535
LFGMgr::LoadLFGDungeons: Failed to load dungeon Random Lich King Dungeon (Id: 261), cant find areatrigger for map 65535
LFGMgr::LoadLFGDungeons: Failed to load dungeon Random Lich King Heroic (Id: 262), cant find areatrigger for map 65535
LFGMgr::LoadLFGDungeons: Failed to load dungeon Proving Grounds: White Tiger Temple (Id: 640), cant find areatrigger for map 1148
LFGMgr::LoadLFGDungeons: Failed to load dungeon Prince Sarsarun (Id: 299), cant find areatrigger for map 734
LFGMgr::LoadLFGDungeons: Failed to load dungeon Random Mists of Pandaria Heroic (Id: 462), cant find areatrigger for map 65535
LFGMgr::LoadLFGDungeons: Failed to load dungeon Random Mists of Pandaria Dungeon (Id: 463), cant find areatrigger for map 65535
Loading Dungeon boss data...
>> Loaded 385 instance encounters in 117 ms
Loading LFG rewards...
>> Loaded 15 lfg dungeon rewards in 2 ms
Loading Graveyard-zone links...
>> Loaded 957 graveyard-zone links in 18 ms
Loading Graveyard Orientations...
>> Loaded 1016 graveyard orientations in 4 ms
Loading spell pet auras...
Spell 56315 listed in `spell_pet_auras` does not have dummy aura or dummy effect
Spell 56315 listed in `spell_pet_auras` does not have dummy aura or dummy effect
>> Loaded 2 spell pet auras in 20 ms
Loading Spell target coordinates...
>> Loaded 478 spell teleport coordinates in 31 ms
Loading enchant custom attributes...
>> Loaded 3 custom enchant attributes in 4 ms
Loading linked spells...
>> Loaded 253 linked spells in 21 ms
Loading Player Create Data...
>> Loaded 122 player create definitions in 3 ms
Loading Player Create Items Data...
>> Loaded 1 custom player create items in 2 ms
Loading Player Create Spell Data...
>> Loaded 6470 player create spells in 3 ms
Loading Player Create Action Data...
>> Loaded 353 player create actions in 3 ms
Loading Player Create Level Stats Data...
>> Loaded 12725 level stats definitions in 173 ms
Loading Player Create XP Data...
>> Loaded 89 xp for level definitions in 2 ms
Loading Exploration BaseXP Data...
>> Loaded 80 BaseXP definitions in 1 ms
Loading Pet Name Parts...
>> Loaded 313 pet name parts in 3 ms
Loading the max pet number...
>> Loaded the max pet number: 20 in 2 ms
Loading pet level stats...
>> Loaded 2480 level pet stats definitions in 164 ms
Loading Player Corpses...
>> Loaded 0 corpses. DB table `corpse` is empty.
Loading Player level dependent mail rewards...
>> Loaded 24 level dependent mail rewards in 2 ms
Loading creature loot templates...
>> Loaded 367207 creature loot templates in 1940 ms
Loading fishing loot templates...
>> Loaded 245 fishing loot templates in 3 ms
Loading gameobject loot templates...
>> Loaded 19414 gameobject loot templates in 381 ms
Loading item loot templates...
>> Loaded 4963 item loot templates in 40 ms
Loading mail loot templates...
>> Loaded 81 mail loot templates in 2 ms
Loading milling loot templates...
>> Loaded 51 milling loot templates in 12 ms
Loading pickpocketing loot templates...
>> Loaded 11351 pickpocketing loot templates in 76 ms
Loading skinning loot templates...
>> Loaded 3772 skinning loot templates in 40 ms
Loading disenchanting loot templates...
>> Loaded 180 disenchanting loot templates in 19 ms
Loading prospecting loot templates...
>> Loaded 57 prospecting loot templates in 12 ms
Loading spell loot templates...
>> Loaded 227 spell loot templates in 276 ms
Loading reference loot templates...
>> Loaded refence loot templates in 118 ms
Loading Skill Discovery Table...
>> Loaded 256 skill discovery definitions in 33 ms
Loading Skill Extra Item Table...
>> Loaded 219 spell specialization definitions in 8 ms
Loading Skill Fishing base level requirements...
>> Loaded 89 areas for fishing base skill level in 2 ms
Loading Achievements...
>> Loaded 48 achievement references in 1 ms
Loading Achievement Criteria Lists...
>> Loaded 1 achievement criteria in 31 ms
Loading Achievement Criteria Data...
>> Loaded 1132 additional achievement criteria data in 121 ms
Loading Achievement Rewards...
>> Loaded 110 achievement rewards in 17 ms
Loading Achievement Reward Locales...
>> Loaded 0 achievement reward locale strings.  DB table `locales_achievement_reward` is empty
Loading Completed Achievements...
>> Loaded 14 realm first completed achievements in 6 ms
Deleting expired auctions...
>> No expired auctions to delete
Loading Item Auctions...
>> Loaded 0 auction items. DB table `auctionhouse` or `item_instance` is empty!
Loading Auctions...
>> Loaded 0 auctions. DB table `auctionhouse` is empty.
Loading Guild XP for level...
>> Loaded 24 xp for guild level definitions in 2 ms
Loading Guild rewards...
>> Loaded 60 guild reward definitions in 2 ms
Loading Guilds...
Loading guilds definitions...
>> Loaded 1 guild definitions in 5 ms
Loading guild ranks...
>> Loaded 5 guild ranks in 3 ms
Loading guild members...
`

**Comment by madmax765** [comment]
Sweet i got it working.. i just rolled backed  my character DB. I must applied a SQL update to it from something else
