### ISSUE TITLE
Compilation error on ubuntu

### ISSUE THREAD

**Issue by Shkipper** [ProjectSkyfire/SkyFire.548#812]
Compilation error on ubuntu 14.04

In file included from /dev/Honore/trinity/.sys/include/ace/TSS_T.h:261:0,
                 from /dev/Honore/source/SkyFire.548/src/server/shared/Threading/Threading.h:24,
                 from /dev/Honore/source/SkyFire.548/src/server/shared/Common.h:90,
                 from /dev/Honore/source/SkyFire.548/src/server/shared/PrecompiledHeaders/sharedPCH.h:22,
                 from /dev/Honore/source/SkyFire.548/src/server/shared/PrecompiledHeaders/sharedPCH.cpp:20:
/dev/Honore/trinity/.sys/include/ace/TSS_T.cpp: In member function ‘void ACE_TSS_Guard<ACE_LOCK>::init_key()’:
/dev/Honore/trinity/.sys/include/ace/TSS_T.cpp:357:39: error: no matching function for call to ‘ACE_Thread::keycreate(ACE_thread_key_t*, void (*)(void*), void* ’
                          (void *) this);
                                       ^
In file included from /dev/Honore/trinity/.sys/include/ace/Thread.h:277:0,
                 from /dev/Honore/source/SkyFire.548/src/server/shared/Threading/Threading.h:23,
                 from /dev/Honore/source/SkyFire.548/src/server/shared/Common.h:90,
                 from /dev/Honore/source/SkyFire.548/src/server/shared/PrecompiledHeaders/sharedPCH.h:22,
                 from /dev/Honore/source/SkyFire.548/src/server/shared/PrecompiledHeaders/sharedPCH.cpp:20:
/dev/Honore/trinity/.sys/include/ace/Thread.inl:14:1: note: candidate: static int ACE_Thread::keycreate(ACE_thread_key_t*, ACE_THR_DEST)
 ACE_Thread::keycreate (ACE_thread_key_t *keyp,
 ^~~~~~~~~~
/dev/Honore/trinity/.sys/include/ace/Thread.inl:14:1: note:   candidate expects 2 arguments, 3 provided
In file included from /dev/Honore/source/SkyFire.548/src/server/shared/AutoPtr.h:23:0,
                 from /dev/Honore/source/SkyFire.548/src/server/shared/Database/QueryResult.h:23,
                 from /dev/Honore/source/SkyFire.548/src/server/shared/Database/SQLOperation.h:26,
                 from /dev/Honore/source/SkyFire.548/src/server/shared/PrecompiledHeaders/sharedPCH.h:25,
                 from /dev/Honore/source/SkyFire.548/src/server/shared/PrecompiledHeaders/sharedPCH.cpp:20:
/dev/Honore/trinity/.sys/include/ace/Bound_Ptr.h: At global scope:
/dev/Honore/trinity/.sys/include/ace/Bound_Ptr.h:121:34: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
   explicit ACE_Strong_Bound_Ptr (auto_ptr<X> p);
                                  ^~~~~~~~
In file included from /usr/include/c++/7/memory:80:0,
                 from /dev/Honore/trinity/.sys/include/ace/Auto_Ptr.h:78,
                 from /dev/Honore/trinity/.sys/include/ace/Service_Gestalt.h:25,
                 from /dev/Honore/trinity/.sys/include/ace/Service_Object.h:27,
                 from /dev/Honore/trinity/.sys/include/ace/Task.h:17,
                 from /dev/Honore/source/SkyFire.548/src/server/shared/Logging/LogWorker.h:25,
                 from /dev/Honore/source/SkyFire.548/src/server/shared/Logging/Log.h:25,
                 from /dev/Honore/source/SkyFire.548/src/server/shared/PrecompiledHeaders/sharedPCH.h:23,
                 from /dev/Honore/source/SkyFire.548/src/server/shared/PrecompiledHeaders/sharedPCH.cpp:20:
/usr/include/c++/7/bits/unique_ptr.h:51:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from /dev/Honore/source/SkyFire.548/src/server/shared/AutoPtr.h:23:0,
                 from /dev/Honore/source/SkyFire.548/src/server/shared/Database/QueryResult.h:23,
                 from /dev/Honore/source/SkyFire.548/src/server/shared/Database/SQLOperation.h:26,
                 from /dev/Honore/source/SkyFire.548/src/server/shared/PrecompiledHeaders/sharedPCH.h:25,
                 from /dev/Honore/source/SkyFire.548/src/server/shared/PrecompiledHeaders/sharedPCH.cpp:20:
/dev/Honore/trinity/.sys/include/ace/Bound_Ptr.h:222:15: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
   void reset (auto_ptr<X> p);
               ^~~~~~~~
In file included from /usr/include/c++/7/memory:80:0,
                 from /dev/Honore/trinity/.sys/include/ace/Auto_Ptr.h:78,
                 from /dev/Honore/trinity/.sys/include/ace/Service_Gestalt.h:25,
                 from /dev/Honore/trinity/.sys/include/ace/Service_Object.h:27,
                 from /dev/Honore/trinity/.sys/include/ace/Task.h:17,
                 from /dev/Honore/source/SkyFire.548/src/server/shared/Logging/LogWorker.h:25,
                 from /dev/Honore/source/SkyFire.548/src/server/shared/Logging/Log.h:25,
                 from /dev/Honore/source/SkyFire.548/src/server/shared/PrecompiledHeaders/sharedPCH.h:23,
                 from /dev/Honore/source/SkyFire.548/src/server/shared/PrecompiledHeaders/sharedPCH.cpp:20:
/usr/include/c++/7/bits/unique_ptr.h:51:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from /dev/Honore/trinity/.sys/include/ace/Bound_Ptr.h:384:0,
                 from /dev/Honore/source/SkyFire.548/src/server/shared/AutoPtr.h:23,
                 from /dev/Honore/source/SkyFire.548/src/server/shared/Database/QueryResult.h:23,
                 from /dev/Honore/source/SkyFire.548/src/server/shared/Database/SQLOperation.h:26,
                 from /dev/Honore/source/SkyFire.548/src/server/shared/PrecompiledHeaders/sharedPCH.h:25,
                 from /dev/Honore/source/SkyFire.548/src/server/shared/PrecompiledHeaders/sharedPCH.cpp:20:
/dev/Honore/trinity/.sys/include/ace/Bound_Ptr.inl:154:58: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
 ACE_Strong_Bound_Ptr<X, ACE_LOCK>::ACE_Strong_Bound_Ptr (auto_ptr<X> p)
                                                          ^~~~~~~~
In file included from /usr/include/c++/7/memory:80:0,
                 from /dev/Honore/trinity/.sys/include/ace/Auto_Ptr.h:78,
                 from /dev/Honore/trinity/.sys/include/ace/Service_Gestalt.h:25,
                 from /dev/Honore/trinity/.sys/include/ace/Service_Object.h:27,
                 from /dev/Honore/trinity/.sys/include/ace/Task.h:17,
                 from /dev/Honore/source/SkyFire.548/src/server/shared/Logging/LogWorker.h:25,
                 from /dev/Honore/source/SkyFire.548/src/server/shared/Logging/Log.h:25,
                 from /dev/Honore/source/SkyFire.548/src/server/shared/PrecompiledHeaders/sharedPCH.h:23,
                 from /dev/Honore/source/SkyFire.548/src/server/shared/PrecompiledHeaders/sharedPCH.cpp:20:
/usr/include/c++/7/bits/unique_ptr.h:51:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from /dev/Honore/trinity/.sys/include/ace/Bound_Ptr.h:384:0,
                 from /dev/Honore/source/SkyFire.548/src/server/shared/AutoPtr.h:23,
                 from /dev/Honore/source/SkyFire.548/src/server/shared/Database/QueryResult.h:23,
                 from /dev/Honore/source/SkyFire.548/src/server/shared/Database/SQLOperation.h:26,
                 from /dev/Honore/source/SkyFire.548/src/server/shared/PrecompiledHeaders/sharedPCH.h:25,
                 from /dev/Honore/source/SkyFire.548/src/server/shared/PrecompiledHeaders/sharedPCH.cpp:20:
/dev/Honore/trinity/.sys/include/ace/Bound_Ptr.inl:309:43: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
 ACE_Strong_Bound_Ptr<X, ACE_LOCK>::reset (auto_ptr<X> p)
                                           ^~~~~~~~
In file included from /usr/include/c++/7/memory:80:0,
                 from /dev/Honore/trinity/.sys/include/ace/Auto_Ptr.h:78,
                 from /dev/Honore/trinity/.sys/include/ace/Service_Gestalt.h:25,
                 from /dev/Honore/trinity/.sys/include/ace/Service_Object.h:27,
                 from /dev/Honore/trinity/.sys/include/ace/Task.h:17,
                 from /dev/Honore/source/SkyFire.548/src/server/shared/Logging/LogWorker.h:25,
                 from /dev/Honore/source/SkyFire.548/src/server/shared/Logging/Log.h:25,
                 from /dev/Honore/source/SkyFire.548/src/server/shared/PrecompiledHeaders/sharedPCH.h:23,
                 from /dev/Honore/source/SkyFire.548/src/server/shared/PrecompiledHeaders/sharedPCH.cpp:20:
/usr/include/c++/7/bits/unique_ptr.h:51:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
make[2]: *** [src/server/shared/CMakeFiles/sharedPCH.cpp_dephelp.dir/PrecompiledHeaders/sharedPCH.cpp.o] Error 1
make[1]: *** [src/server/shared/CMakeFiles/sharedPCH.cpp_dephelp.dir/all] Error 2
make: *** [all] Error 2

**Comment by AriDEV** [comment]
read requirements in the readme

**Comment by HBSNET** [comment]
I have same problem on my Ubuntu 16.04 LTS , everything installed and configured..
..What is missing from "requirements"?! Please help.

/dev/Honore/source/SkyFire.548/src/server/shared/Database/QueryResult.cpp:82:28: error: cannot convert ‘bool*’ to ‘my_bool* {aka char*}’ in assignment
m_rBind[i].is_null = &m_isNull[i];

**Comment by ckjet** [comment]
I have the same problem on my debian 9
