### ISSUE TITLE
Run world

### ISSUE THREAD

**Issue by Shkipper** [ProjectSkyfire/SkyFire.548#813]
DatabasePool world NOT opened. There were errors opening the MySQL connections. Check your SQLDriverLogFile for specific errors.
Cannot connect to world database 127.0.0.1;3306;login;pasword;world

When you run so that's a mistake. Login and password are correct

**Comment by Shkipper** [comment]
Исправил

**Comment by alterego21** [comment]
Try and replace 127.0.0.1 with localhost and let me know if it works
There are some security changes with the latest MySQL..
English. https://dev.mysql.com/doc/refman/8.0/en/connecting.html

**Comment by CarlosCenturion** [comment]
> Fixed

how? u.u
