### ISSUE TITLE
Vehicle system

### ISSUE THREAD

**Issue by Nightprince** [ProjectSkyfire/SkyFire.548#820]
**Description:**

Vehicle system is not work

![wowscrnshot_080218_170815](https://www.yekta-upload.ir/uploads/db2dea6f09991.jpg)

**Expected behaviour:**

Vehicle bar will not be displayed and user can't exit form vehicle

**SF rev. hash/commit:** 

SkyFire 5.x.x rev. f1b78876fcb3+ 2018-07-26 10:10:15 +0200 (master branch) (Win32, Release)

**SFDB version:**  Release 17

**Operating system:** Win 10

**Comment by AriDEV** [comment]
![Panda Puff](http://www.cutestpaw.com/wp-content/uploads/2016/02/Panda-puff..jpg)

**Comment by Artamedes** [comment]
this happens because of SMSG_ON_MONSTER_MOVE

here's my structure
https://gist.github.com/Artamedes/7be5b38eb9f4277ca4c92d6850330ba9 (sub_14F41E1)

and with that ingame now working: https://i.imgur.com/gji6iXX.jpg

maybe can help 😄
